== Bounding box
include::includes/partials-attributes.adoc[]
[#44]

[width="100%",cols="50%,50%",]
|===
|UK GEMINI id |44

|Definition |Rectangle enclosing the extent of the data resource
described in latitude and longitude

|Purpose and meaning |This is to enable the resource to be located
geographically

|Obligation |Mandatory

|Occurrence |Multiple

|Data type |Class

|Domain a|
EX_GeographicBoundingBox

[cols=",,,,",]
!===
!Metadata element name !West bounding longitude !East bounding longitude
!South bounding latitude !North bounding latitude

!Definition !western-most limit of the data resource extent, expressed
in longitude in decimal degrees (positive east) !eastern-most limit of
the data resource extent, expressed in longitude in decimal degrees
(positive east) !southern-most limit of the data resource extent,
expressed in latitude in decimal degrees (positive north) !northern-most
limit of the data resource extent, expressed in latitude in decimal
degrees (positive north)

!Obligation !mandatory !mandatory !mandatory !mandatory

!Occurrence !single !single !single !single

!Data type !Decimal, expressed in degrees to at least two decimal places
! ! !

!Domain !-180.00 <= west bounding longitude <= 180.00 !-180.00 <= east
bounding longitude <= 180.00 !-90.00 <= south bounding latitude <= north
bounding latitude !south bounding latitude <= north bounding latitude <=
90.00

!Other comments !The West bounding coordinate usually has a value less
than the value of the East bounding coordinate, except when the extent
straddles the 180 degree meridian. !The East bounding longitude usually
has a value greater than the value of the West bounding longitude,
except when the extent straddles the 180 degree meridian. ! !
!===

|Guidance a|
. Identify a bounding box slightly larger than the extent of the data
resource, and determine the coordinates of the boundaries. It may be
necessary to convert from another coordinate system (e.g. National Grid)
into lat/long.
. Only approximate values are required, sufficient to identify the
extent on a global basis. The bounding box is implicitly in WGS84.

|Comment |The bounding box will often cover areas that are not directly
related to the area covered by the resource.
# tag::service[]
The bounding box of a service may be larger or smaller than that of the datasets it can return.
# end::service[]
|Examples |-9.23, 2.69, 49.84, 60.85

|Revision date |December 2012
|===

.Corresponding element in other standards...
[%collapsible]
====
|===
|Standard |Name |Comparison

|INSPIRE Metadata |Geographic bounding box |Identical
# tag::dataset[]
|ISO 19115:2003 |MD_DataIdentification.extent > EX_Extent >
EX_GeographicExtent > EX_GeographicBoundingBox |Minor difference in name

|ISO 19139:2007
|/gmd:MD_Metadata/gmd:identificationInfo/gmd:MD_DataIdentification/gmd:extent/gmd:EX_Extent/gmd:geographicElement/gmd:EX_GeographicBoundingBox
# end::dataset[]
# tag::service[]
|ISO 19115:2003 |SV_ServiceIdentification.extent > EX_Extent >
EX_GeographicExtent > EX_GeographicBoundingBox |Minor difference in name

|ISO 19139:2007
|/gmd:MD_Metadata/gmd:identificationInfo/srv:SV_ServiceIdentification/srv:extent/gmd:EX_Extent/gmd:geographicElement/gmd:EX_GeographicBoundingBox
# end::service[]
|
|===
====

.Change history...
[%collapsible]
====
* GEMINI 1 to 2.0: Slight change of name of each element
* GEMINI 2.1 to 2.2: the four separate elements were merged to form
Bounding box, which was made multiple
====

.Encoding guidelines...
[%collapsible]
====
[cols="a,a"]
|===
|Guidelines
|
# tag::service[]
. The encoding is very similar to that used in metadata
instances for datasets or series, except that the extent XML element is
in the srv namespace instead of gmd. This is because extent is a
property of MD_DataIdentification (ISO 19115) and
SV_ServiceIdentification (ISO 19119/Amd 1:2008), not a property of the
parent MD_Identification.
. Note that the EX_Extent XML element is in the gmd namespace, even though it is being used to describe a service.
# end::service[]
. The definition of the equivalent ISO 19115 class,
EX_GeographicBoundingBox, is 'Geographic area of the entire dataset
referenced to WGS 84'. Consequently, the CRS of the coordinates
expressed in metadata is always WGS 84 (identified by the EPSG URI
http://www.opengis.net/def/crs/EPSG/0/4326). This means that the
coordinate values shall be expressed in units of degrees (encoded using
decimal numbers) with axes orientated north and east. The geodetic datum
is WGS 84.
|Example
|
[source,xml]
----
# tag::dataset[]
include::../snippets/dataset-boundingbox.xml[]
# end::dataset[]
# tag::service[]
include::../snippets/service-boundingbox.xml[]
# end::service[]
----
|===
====

.Metadata errors observed...
[%collapsible]
====
|===
|Errors observed a|
*Overly precise bounding box* +
GEMINI states that the bounding latitude and longitude should be stated
to at least two decimal places. The INSPIRE geoportal used to report two
decimal places as an error; it does not now. However, some software
defaults to values that are unnecessarily "precise". For example: +

....
<gmd:westBoundLongitude>
  <gco:Decimal>-8.17548890898914</gco:Decimal>
</gmd:westBoundLongitude>
....

Six decimal places of a degree is something like 1cm, so the longitude
above is being given to roughly the nearest molecule.

|===
====
