== Keyword
include::includes/partials-attributes.adoc[]
[#6]

[width="100%",cols="50%,50%",]
|===
|UK GEMINI id |6

|Definition |Topic of the content of the data resource

|Purpose and meaning |The purpose of this element is to indicate the
general subject area of the data resource using keywords. This enables
searches to eliminate resources that are of no interest. Ideally, a
standardised set of keywords should be used, so that resources can be
identified in any search. This element is similar to link:#5[Topic
category], which has a coded list of high-level categories, whereas
Keyword allows more appropriate terms to describe the data resource.

|Obligation |Mandatory

|Occurrence |Multiple

|Data type |Class

|Domain a|
This class comprises the following elements:

. Keyword value (mandatory)
. Originating controlled vocabulary (conditional - if keywords originate
from a controlled vocabulary)

These are specified as follows:

[width="100%",cols="34%,33%,33%",options="header",]
!===
! !Keyword value !Originating controlled vocabulary
!Definition !topic of the content of the data resource !name of the
formally registered thesaurus or a similar authoritative source of
keywords

!Obligation !mandatory !conditional - required if keywords originate
from a controlled vocabulary

!Occurrence !multiple !single

!Data type !CharacterString !Class CI_Citation (from ISO19115)

!Domain !free text !

!Other Comments !- !a default value will generally be assigned for this
!===

|Guidance a|
. Keyword values should if possible be taken from a list of standard
subject categories, identified in the element 'Originating controlled
vocabulary'.
. Possible vocabularies include http://www.eionet.europa.eu/gemet/en/themes/[GEMET] and the https://inspire.ec.europa.eu/featureconcept[the INSPIRE Feature Concept Dictionary]
. For other Keywords, if drawn from a Controlled Vocabulary, this must
be stated.
. Terms covering the subject of the data resource should be selected.
. For conformance with INSPIRE, the keyword should describe the relevant
INSPIRE spatial data theme, such as those contained in GEMET INSPIRE;
. The formal citation for the vocabulary should be given, including at
least the title and reference date.
. Acronyms and their expanded versions as separate keywords are
acceptable within the Keyword element.
. Other standard subject category areas may be used, and different user
communities may need to create their own lists of subject areas.
. Multiple keywords may be stored in an individual metadata record, and
these may come from more than one originating controlled vocabulary.

|Comment |This element is similar to Topic Category, but allows a
broader range of values.

|Examples a|
* Land cover, General Environmental Multi-Lingual Thesaurus (GEMET)
* Gazetteer service, General Environmental Multi-Lingual Thesaurus
(GEMET)

|Revision date |May 2019
|===

.Corresponding element in other standards...
[%collapsible]
====
|===
|Standard |Name |Comparison

|INSPIRE Metadata |inspire-theme-keyword and additional-keywords
|Equivalent

|ISO 19115:2003 |MD_Identification.descriptiveKeywords > MD_Keywords
|Equivalent

|ISO 19139:2007
|
# tag::dataset[]
/gmd:MD_Metadata/gmd:identificationInfo/gmd:MD_DataIdentification/gmd:descriptiveKeywords/gmd:MD_Keywords
# end::dataset[]
# tag::service[]
/gmd:MD_Metadata/gmd:identificationInfo/srv:SV_ServiceIdentification/gmd:descriptiveKeywords/gmd:MD_Keywords 
# end::service[]
|Equivalent
|===
====

.Change history...
[%collapsible]
====
. GEMINI 1 to 2.0: Change of name from 'Subject'
. GEMINI 2.0 to 2.1: expansion to include keyword value and originating
controlled vocabulary
====

.Encoding guidelines...
[%collapsible]
====
[cols="a,a"]
|===
|Guidelines a|
# tag::dataset[]
[arabic]
. The GEMINI2 keyword item comprises keyword value(s) and,
conditionally, the specification of an originating controlled
vocabulary. If keywords are not selected from a controlled vocabulary
the encoding shown in Example One shall be used.
. Where keywords do originate from a controlled vocabulary the encoding
shown in Example Two shall be used. Note the inclusion of the
gmd:thesaurusName XML element which contains the XML element
gmd:CI_Citation. This element must contain at least a title, reference
date and date type. In the example keywords have been selected from the
GEMET Concepts controlled vocabulary.
. Metadata records which describe a dataset that relates to one or more
of the INSPIRE themes must include the appropriate keyword(s) from the
GEMET INSPIRE themes, as illustrated in Example Two.
. Examples Two and Three show how the GEMET INSPIRE themes and the GEMET
concepts controlled vocabularies should be cited according to the
https://inspire.ec.europa.eu/documents/inspire-metadata-implementing-rules-technical-guidelines-based-en-iso-19115-and-en-iso-1[INSPIRE
guidance] link:component/content/article?id=1047[[9]].
. Note that more than one keyword value may be selected from a single
controlled vocabulary. Note also that keywords may be selected from more
than one controlled vocabulary. In this case the encoding shown in
Example Three.
. For INSPIRE if several keywords come from a single controlled
vocabulary these shall be grouped together.
. For INSPIRE the use of a gmx:Anchor element is recommended over the
use gco:CharacterString for terms from controlled vocabularies
. Recommended best practice is to select a human readable value from a
controlled vocabulary. An example from the Marine Geospatial community
is http://seadatanet.maris2.nl/v_bodc_vocab_v2/search.asp?lib=P02
# end::dataset[]
# tag::service[]
. The GEMINI2 keyword item comprises keyword value(s) and, conditionally, the specification of an originating controlled vocabulary. If keywords are not selected from a controlled vocabulary the encoding shown in Example One shall be used.
. In the context of INSPIRE the presence of at least one keyword is mandated. For service metadata there shall be at least one keyword defining the category or subcategory of the service using its language neutral name as defined in Part D 4 of the Metadata Implementing Rules (the language neutral names are the words in brackets using lower camel case notation). The keyword shown in Example Two is an example of this
. Where keywords do originate from a controlled vocabulary the encoding shown in Example Two shall be used. Note the inclusion of the gmd:thesaurusName XML element which contains the XML element gmd:CI_Citation. This element must contain at least a title, reference date and date type. In the example keywords have been selected from the GEMET Concepts controlled vocabulary.
. Example Three shows how the GEMET INSPIRE themes and the GEMET concepts controlled vocabularies should be cited according to the INSPIRE guidance [9].
. Note that more than one keyword value may be selected from a single controlled vocabulary. Note also that keywords may be selected from more than one controlled vocabulary. In this case the encoding shown in Example One shall be used.
. The srv:SV_ServiceIdentification XML element has an optional property srv:keywords which exhibits the same behaviour as gmd:descriptiveKeywords. Consequently keywords for service metadata could be encoded in the way shown in Example Five. This approach shall not be followed in GEMINI2 metadata instances
. This case arises because the XML element gmd:descriptiveKeywords is a an instance of the property (or role in fact) on the ISO 19115 abstract class MD_Identification, from which both SV_ServiceIdentification and MD_DataIdentification inherit. Therefore, SV_ServiceIdentification inherits the descriptiveKeywords property and adds a similar property called keywords.
. Recommended best practice is to select a human readable value from a controlled vocabulary. An example from the Marine Geospatial community is http://seadatanet.maris2.nl/v_bodc_vocab_v2/search.asp?lib=P02
# end::service[]
# tag::dataset[]
| Example One (datasets/series) - without originating controlled vocabulary
|
[source,xml]
----
include::../snippets/dataset-keyword-freetext.xml[]
----
| Example Two (datasets/series) - INSPIRE theme
|
[source,xml]
----
include::../snippets/dataset-keyword-inspire.xml[]
----
| Example Three (datasets/series) - keywords from 2 controlled vocabularies
|
[source,xml]
----
include::../snippets/dataset-keyword-controlled.xml[]
----
# end::dataset[]
# tag::service[]
|Example One (services) - without controlled vocabulary
|
[source,xml]
----
include::../snippets/service-keyword-freetext.xml[]
----
| Example Two (services) - service keyword from part D4 on the INSPIRE Metadata Implementing Rules
|
[source,xml]
----
include::../snippets/service-keyword-inspire.xml[]
----
| Example Three (services) - GEMET concepts
|
[source,xml]
----
include::../snippets/service-keyword-gemet.xml[]
----
| Example Four (services) - keywords from two controlled vocabularies
|
[source,xml]
----
include::../snippets/service-keyword-controlled.xml[]
----
# end::service[]
|===
====

.Metadata errors observed...
[%collapsible]
====
|===
|Errors observed |*Incorrect INSPIRE keywords* - +
Putting in more than one INSPIRE keyword, where the first keyword in the
list is not the correct Annex/Theme
|===
====
