== Limitations on public access
include::includes/partials-attributes.adoc[]
[#25]

[width="100%",cols="50%,50%",]
|===
|UK GEMINI id |25

|Definition |Restrictions imposed on accessing the data resource for
security and other reasons

|Purpose and meaning |The purpose of this element is to identify any
external restrictions on access to the data such as licence
arrangements.

|Obligation |Mandatory

|Occurrence |Multiple

|Data type |CharacterString

|Domain |Free text

|Guidance a|
. Provide information on any limitations.
. The most common access restriction should be identified.
. Where there are no limitations on public access, this should be
stated.
. More than one value may be included.
. For INSPIRE: If no limitations apply, enter 'No limitations'.
. INSPIRE recognises the following kinds of reasons for limiting public
access, listed in Article 13(1):
* (a) confidentiality of the proceedings of public authorities +
https://www.legislation.gov.uk/uksi/2009/3157/regulation/9[Regulation 9(5)(d) of the UK INSPIRE Regulations 2009]
* (b) international relations, public security or national defence +
https://www.legislation.gov.uk/uksi/2009/3157/regulation/9[Regulation 9(5)(a) of the UK INSPIRE Regulations 2009]
* (c) the course of justice +
https://www.legislation.gov.uk/uksi/2009/3157/regulation/9[Regulation 9(5)(b) of the UK INSPIRE Regulations 2009]
* (d) confidentiality of commercial or industrial information +
https://www.legislation.gov.uk/uksi/2009/3157/regulation/9[Regulation 9(5)(e) of the UK INSPIRE Regulations 2009]
* (e) intellectual property rights +
https://www.legislation.gov.uk/uksi/2009/3157/regulation/9[Regulation 9(5)(c) of the UK INSPIRE Regulations 2009]
* (f) confidentiality of personal data +
https://www.legislation.gov.uk/uksi/2009/3157/regulation/9[Regulation 9(2) of the UK INSPIRE Regulations 2009]
* (g) interests of a person who supplied the data on a voluntary basis +
https://www.legislation.gov.uk/uksi/2009/3157/regulation/9[Regulation 9(5)(f) of the UK INSPIRE Regulations 2009]
* (h) protection of the environment +
https://www.legislation.gov.uk/uksi/2009/3157/regulation/9[Regulation 9(5)(g) of the UK INSPIRE Regulations 2009]
+
Each has an entry with the full text, in the INSPIRE registry,
http://inspire.ec.europa.eu/metadata-codelist/LimitationsOnPublicAccess
. At least one limitation on public access shall give an INSPIRE reason

|Comment |Limitations on public access are different from Use
constraints which are warnings about its suitability for particular
types of usage, or constraints on the use that can be made of the data.

|Examples |No restriction on public access.

|Revision date |June 2021
|===

.Corresponding element in other standards...
[%collapsible]
====
|===
|Standard |Name |Comparison

|INSPIRE Metadata |Limitations on public access |Equivalent

|ISO 19115:2003 |MD_Identification.resourceConstraints >
MD_LegalConstraints.accessConstraints & otherConstraints |Equivalent

|ISO 19139:2007
# tag::dataset[]
|/gmd:MD_Metadata/gmd:identificationInfo/gmd:MD_DataIdentification/gmd:resourceConstraints/gmd:MD_LegalConstraints/gmd:accessConstraints
& otherConstraints |Equivalent
# end::dataset[]
# tag::service[]
|/gmd:MD_Metadata/gmd:identificationInfo/srv:SV_ServiceIdentification/gmd:resourceConstraints/gmd:MD_LegalConstraints/gmd:accessConstraints
& otherConstraints |Equivalent
# end::service[]
|===
====

.Change history...
[%collapsible]
====
. GEMINI 1 to 2.0: Change of name from 'access constraint', and
modification of definition. +
Made mandatory, to conform to INSPIRE.
. GEMINI 2.0 to 2.1: Change to equivalent ISO 19115 element from
accessConstraint making domain free text.
. GEMINI 2.2 to 2.3: Change of encoding
. GEMINI 2.3 June 2021 fixed typo in Guidance 6 (a) and (f)
====

.Encoding guidelines...
[%collapsible]
====
[cols="a,a"]
|===
|Guidelines
|
. This element shall be encoded in a different
resourceConstraints/MD_LegalConstraints XML element to GEMINI element 26
Use constraints
. The LegalConstraints element shall contain a
accessConstraints/MD_RestrictionCode element with code list value
"otherRestrictions"
. The LegalConstraints element shall also contain a gmd:otherConstraints
element, with free text.
. If there are no limitations the value of gmd:otherConstraints shall be
'no limitations' (see Example Two).
. The free text shall be encoded in a gmx:Anchor element, with
xlink:href pointing to the relevant kind of limitation from the INSPIRE
Metadata registry:
http://inspire.ec.europa.eu/metadata-codelist/LimitationsOnPublicAccess
. Free text content cannot be empty
. To encode multiple limitations, include more than one
gmd:otherConstraints element
|Example One
|
[source,xml]
----
# tag::dataset[]
include::../snippets/dataset-limitationsonpublicaccess.xml[]
# end::dataset[]
# tag::service[]
include::../snippets/service-limitationsonpublicaccess.xml[]
# end::service[]
----
| Example Two - no limitations
|
[source,xml]
----
include::../snippets/limitationsonpublicaccess-nolimitations.xml[]      
----
| Example Three - two limitations
|
[source,xml]
----
include::../snippets/limitationsonpublicaccess-twolimitations.xml[]   
----
|===
====

.Metadata errors observed...
[%collapsible]
====
|===
|Errors observed |*Missing or incorrect information* +
Licence information should be provided, preferably by a URL. +
It is an error to state 'no limitations' in Limitations on Public
Access, when the resource is not open access. +
Defra metadata audit, October 2015: In many cases either this field has
been left empty or where the PSMA (or similar) licensing arrangements
are referenced there is either a lack of detail or no links to the
appropriate sites.
|===
====
