= Name : Metadata standard name
include::includes/partials-attributes.adoc[]
ifdef::variant-dataset[]
:outfilesuffix: datasets-title{outfilesuffix}
endif::[]
ifdef::variant-service[]
:outfilesuffix: services-title{outfilesuffix}
endif::[]

[width="100%",cols="50%,50%",]
|===
|UK GEMINI id |54

|Definition |Name of the metadata standard or profile used. +
The relevant standard shall be cited with a reference to the appropriate
register entry.

|Purpose and meaning |The purpose of this element is to record the
metadata standard (profile) followed when creating the metadata. This
will be important when metadata is passed from one metadata system to
another.

|Obligation |Optional

|Occurrence |Single

|Data type |CharacterString

|Domain |Free text

|Guidance |See also link:#58[Metadata standard version]

|Comment |In order to add a new metadata (profile) standard name to the
NERC vocab server, contact GEMINI at AGI

|Examples a|
* ISO 19115
* UK GEMINI
* NERC profile of ISO19115:2003

|Revision date |January 2020
|===

Corresponding element in other standards...

[%collapsible]
====
|===
|Standard |Name |Comparison

|INSPIRE Metadata | |not specified

|ISO 19115:2003 |MD_Metadata.metadataStandardName |added guidance

|ISO 19139:2007 |/gmd:MD_Metadata/gmd:metadataStandardName |added
guidance
|===
====

Change history...

[%collapsible]
====
* GEMINI 1 to 2.0: deleted
* GEMINI 2.3 September 2020: reinstated
====

Encoding guidelines...

[%collapsible]
====
|===
|Guidelines |GEMINI is supported by a
https://www.bodc.ac.uk/resources/vocabularies/vocabulary_search/M25/[register
of metadata standard and profile names], hosted on the NERC vocab
server. +
The relevant standard shall be cited with a reference to the appropriate
register entry, using an Anchor.

|Example a|
`                   Example One – UK GEMINI 2.3

....
include::../snippets/metadatastandardname-gemini.xml[]
            
Example Two – MEDIN profile of GEMINI 2.3 
...
include::../snippets/metadatastandardname-medin.xml[]
...
         
....

|===
====

Metadata errors observed...

[%collapsible]
====
No error information available
====