= Name : Spatial reference system
include::includes/partials-attributes.adoc[]
ifdef::variant-dataset[]
:outfilesuffix: datasets-title{outfilesuffix}
endif::[]
ifdef::variant-service[]
:outfilesuffix: services-title{outfilesuffix}
endif::[]

[width="100%",cols="50%,50%",]
|===
|UK GEMINI id |17

|Definition |Identifier, name or description of the system of spatial
referencing, whether by coordinates or geographic identifiers, used in
the data resource

|Purpose and meaning |The purpose of this element is to identify the way
in which the data is spatially referenced in the data resource. This may
be by coordinates (e.g. the National Grid of Great Britain) or
geographic identifiers (e.g. unit postcodes).

|Obligation |At least one coordinate reference system shall be given

|Occurrence |Multiple

|Data type |Class

|Domain a|
The class comprises two elements:

* Code identifying the spatial reference system
* (Conditional) codeSpace, +
- to be used if the code alone does not uniquely identify the referred
spatial reference system. +
- not to be used if the spatial reference system is listed in the
Default Coordinate Reference Systems

|Guidance a|
. For each spatial reference system
* Identify the spatial reference systems used to spatially reference the
data in the data resource;
* Check if the spatial reference system is listed in Annex D.4 (Default
Coordinate Reference Systems) of the INSPIRE
https://inspire.ec.europa.eu/Technical-Guidelines2/Metadata/[Metadata
Technical Guidelines]
. If the spatial reference system is not listed in the defaults,
identify a well-known register that defines the coordinate reference
system or, if the spatial reference system is using geographic
identifiers (such as Post Codes, NUTS, what3words, Geohashing), supply a
resolveable HTTP-URI that provides more information about the geographic
identifier system.
. Where there appears to be more than one spatial reference system used,
take the one that is used in resolving any conflict between the spatial
referencing systems (e.g. if the data is recorded referenced by unit
postcodes, and a coordinate is then associated, then unit postcode is
the spatial reference system, whereas if the data is recorded by
coordinate, and unit postcodes are added as an attribute, then it is
'National Grid of Great Britain').

|Comment a|
. Only coordinate reference systems identifiers specified in a
well-known common register shall be used
. Note that the data resource may be supplied in a range of other
reference systems in addition to that in which it is recorded.

|Examples |British National Grid

|Revision date |March 2019
|===

Corresponding element in other standards...

[%collapsible]
====
|===
|Standard |Name |Comparison
ifdef::variant-dataset[]
|INSPIRE Metadata |crs coordinate reference system |Equivalent
endif::[]
ifdef::variant-service[]
|INSPIRE Metadata |crs coordinate reference system |In INSPIRE it is
only mandatory for interoperable spatial data services
endif::[]
|ISO 19115:2003 |MD_ReferenceSystem.referenceSystemIdentifier >
RS_Identifier.code |Equivalent

|ISO 19139:2007
|gmd:referenceSystemInfo/gmd:MD_ReferenceSystem/gmd:referenceSystemIdentifier/gmd:RS_identifier
|Equivalent
|===
====

Change history...

[%collapsible]
====
GEMINI 1 to 2.0: Changed from enumerated list
====

Encoding guidelines...

[%collapsible]
====
|===
|Guidelines a|
* When the provided text is a term or code from an externally defined
explanation or registry value, gmx:Anchor should be used instead of
gco:CharacterString
* The content of gmx:Anchor or gco:CharacterString must not be empty

|Example a|
Example One - using gmx:Anchor for a default Coordinate Reference System (as defined                   in Annex D.4 of the INSPIRE metadata technical guidance v.2)

....
include::../snippets/spatialreferencesystem-default-anchor.xml[]
....

Example Two - using gmx:Anchor for a non default CRS.

....
include::../snippets/spatialreferencesystem-nondefault-anchor.xml[]
....

Example Three - encoding example with authority

....
include::../snippets/spatialreferencesystem-authority.xml[]
....

Example Four - encoding example for spatial reference systems using
geographic identifiers

....
include::../snippets/spatialreferencesystem-identifiers.xml[]
....

|===
====

Metadata errors observed...

[%collapsible]
====
No error information available
====
