= Name : Spatial resolution
include::includes/partials-attributes.adoc[]
ifdef::variant-dataset[]
:outfilesuffix: datasets-title{outfilesuffix}
endif::[]
ifdef::variant-service[]
:outfilesuffix: services-title{outfilesuffix}
endif::[]

[width="100%",cols="50%,50%",]
|===
|UK GEMINI id |18

|Definition |Measure of the granularity of the data (in metres)

|Purpose and meaning |The purpose of this element is to provide an
indication of how detailed the spatial data is. It is equivalent to the
ground sample distance. It should not be confused with the scale of a
map which is purely a display attribute (the spatial resolution should
be defined in the specification of the data resource).

|Obligation |Conditional - where a resolution distance can be specified

|Occurrence |Multiple

|Data type |Real

|Domain |Value > 0

|Guidance a|
. For data capture in the field, it is the precision at which the data
is captured. This may be the accuracy for topographic surveys, or the
average sampling distance in an environmental survey.
. For data taken from maps, it is the positional accuracy of the map
(defined in the specification of the map series).
. For image data, it is the resolution of the image.
. In many given cases, only approximate values can be given.

|Comment |This should not be confused with precision which refers to the
resolution of the measurements themselves. Thus for a buildings dataset,
a building seed could be recorded to a precision of 0.1 metres, but
since the requirement is for the seed only to be within the building
footprint for the purpose of discriminating between buildings, the
spatial resolution of the buildings dataset would be the typical size of
the building, i.e. about 10 metres.

|Examples a|
* 10.0
* 0.001

|Revision date |March 2019
|===

Corresponding element in other standards...

[%collapsible]
====
|===
|Standard |Name |Comparison

|INSPIRE Metadata |Spatial resolution |INSPIRE allows the option of
either Distance or Equivalent scale.
ifdef::variant-dataset[]
|ISO 19115:2003 |MD_DataIdentification.spatialResolution >
MD_Resolution.distance |Equivalent

|ISO 19139:2007
|/gmd:MD_Metadata/gmd:identificationInfo/gmd:MD_DataIdentification/gmd:spatialResolution
|Equivalent
endif::[]
ifdef::variant-service[]
|ISO 19115:2003 |Describe in the Abstract |no direct equivalent
endif::[]
|===

===

Change history...

[%collapsible]
====
GEMINI 1 to 2.0: made conditional
====

Encoding guidelines...

[%collapsible]
====
|===
|Guidelines a|
ifdef::variant-dataset[]
. The encoding example for spatial resolution is shown in the example
below.
. A distance measurement shall be encoded and the unit of measurement
shall be identified. The unit of measurement is identified using the uom
attribute of the XML element gco:Distance. In the case of GEMINI2 all
spatial resolution distance measurements shall be in metres. The value
of the uom attribute shall be: urn:ogc:def:uom:EPSG::9001
. This defines the unit of measure as metres by reference to the
http://www.epsg-registry.org/[EPSG registry]
link:component/content/article?id=1047[[12]].
endif::[]
ifdef::variant-service[]
. For services, it is not possible to express the restriction of a
service concerning the spatial resolution in using the ISO 19139 XML
Schema.
. It shall be expressed in the Abstract.
. The spatial resolution restriction text shall include either an
equivalent scale as integer valued scale denominator or a resolution
distance using a numerical length value and with a unit of length.
endif::[]

ifdef::variant-dataset[]
|Example a|

....
include::../snippets/spatialresolution.xml[]
....

|===
endif::[]
====

Metadata errors observed...

[%collapsible]
====
No error information available
====