== Use constraints
include::includes/partials-attributes.adoc[]
[#26]


[width="100%",cols="50%,50%",]
|===
|UK GEMINI id |26

|Definition |Restrictions and legal restraints on using the data
resource

|Purpose and meaning |The purpose of this element is to describe any
restrictions on usage of the data (as opposed to access)

|Obligation |Mandatory

|Occurrence |Multiple

|Data type |CharacterString

|Domain |Free text

|Guidance a|
. Provide information on any constraints to using the resource, e.g.
licensing, fees, usage restrictions, or refer to a URL where this
information is available, e.g. a licence document. If entering a URL,
enter this as a sub-element, not as part of free text. Where relevant,
Data Provider licence information should be provided in the form of a
Licence Title, and where possible, a licence URL. If more than one type
of licence is included then the URL should point to a Data Providers
page.
. Any known constraints should be identified. If no conditions apply,
then 'no conditions apply' should be recorded.

|Comment |Use constraints are different from Restrictions on public
access which describe limitations on access to the data. A data resource
can have open access (e.g. to look at it), but restricted use.

|Examples |Should not be used for navigation purposes.

|Revision date |September 2018
|===

.Corresponding element in other standards...
[%collapsible]
====
|===
|Standard |Name |Comparison

|INSPIRE Metadata |Conditions applying to access and use |Equivalent

|ISO 19115:2003 |MD_Identification.resourceConstraints >
MD_LegalConstraints.useConstraints & otherConstraints |Equivalent

|ISO 19139:2007
# tag::dataset[]
|/gmd:MD_Metadata/gmd:identificationInfo/gmd:MD_DataIdentification/gmd:resourceConstraints/gmd:MD_LegalConstraints/gmd:useConstraints
& gmd:otherConstraints |Equivalent
# end::dataset[]
# tag::service[]
|/gmd:MD_Metadata/gmd:identificationInfo/srv:SV_ServiceIdentification/gmd:resourceConstraints/gmd:MD_LegalConstraints/gmd:useConstraints
& gmd:otherConstraints |Equivalent
# end::service[]
|===
====

.Change history...
[%collapsible]
====
* GEMINI 1 to 2.0: Change to free text field from enumerated list, and
making mandatory to conform with INSPIRE.
* GEMINI 2.2 to 2.3: Change of encoding
====

.Encoding guidelines...
[%collapsible]
====
[cols="a,a"]
|===
|Guidelines
|
. This element shall be encoded in a different
resourceConstraints/MD_LegalConstraints XML element to GEMINI element 25
Limitations on public access
. The MD_LegalConstraints element shall contain a useConstraints element
. Note: INSPIRE allows an accessConstraints element here; GEMINI
recommends using Limitations on public access for these
. The useConstraints element shall contain an MD_RestrictionCode element
with code list value "otherRestrictions"
. The LegalConstraints element shall also contain a gmd:otherConstraints
element, with free text.
. "No conditions" and "conditions unknown" shall be specified using a
gmx:Anchor link to the relevant entry in the INSPIRE metadata registry,
http://inspire.ec.europa.eu/metadata-codelist/ConditionsApplyingToAccessAndUse
. In certain circumstances it might be appropriate to refer to an
external document describing constraints. In this case the encoding
shown in Example Two may be used. This is recommended for licenses, even
the use of ISO 19115 otherRestrictions would not generally include
license restrictions, as they have their own term in the ISO 19115 code
list.
. If there are no limitations the value of gmd:otherConstraints shall be
'no limitations' (see Example Three).
. There may be more than one gmd:otherConstraints element
|Example One
|
[source,xml]
----
# tag::dataset[]
include::../snippets/dataset-useconstraints.xml[]
# end::dataset[]
# tag::service[]
include::../snippets/service-useconstraints.xml[]
# end::service[]
----
| Example Two - with external file
|
[source,xml]
----
include::../snippets/useconstraints-externalfile.xml[]        
----
| Example Three - no conditions apply
|
[source,xml]
----
include::../snippets/useconstraints-noconditions.xml[]           
----
|===
====

.Metadata errors observed...
[%collapsible]
====
[width="100%",cols="50%,50%",]
|===
|Errors observed |*Missing or incorrect constraints information* +
Licence information should be provided, preferably by a URL. +
It is an error to state 'no conditions apply' in Use Constraints, when
restrictions do in fact exist.
|===
====
