== UK GEMINI 2.3 2020-06-29 dataset or series

== Contents

[width="100%",cols="50%,50%",options="header",]
|===
|Metadata about the metadata record |Metadata about the resource
|link:#45[File Identifier] +
link:#47[Hierarchy level name] +
link:#30[Metadata date] +
link:#33[Metadata language] +
link:#35[Metadata point of contact] +
link:#54[Metadata standard name] +
link:#55[Metadata standard version] +
link:#49[Parent identifier] +
link:#39[Resource type] + |link:#4[Abstract] +
link:#27[Additional information] +
link:#2[Alternative title] +
link:#44[Bounding box] +
link:#51[Character encoding] +
link:#41[Conformity] +
link:#21[Data format] +
link:#52[Data quality] +
link:#3[Dataset language] +
link:#8[Dataset reference date] +
link:#43[Equivalent scale] +
link:#15[Extent] +
link:#6[Keyword] +
link:#25[Limitations on public access] +
link:#10[Lineage] +
link:#53[Maintenance information] +
link:#48[Quality scope] +
link:#36[Resource identifier] +
link:#19[Resource locator] +
link:#23[Responsible organisation] +
link:#17[Spatial reference system] +
link:#50[Spatial representation type] +
link:#18[Spatial resolution] +
link:#7[Temporal extent] +
link:#1[Title] +
link:#5[Topic Category] +
link:#26[Use constraints] +
link:#16[Vertical extent information] +
|===

Return to
https://www.agi.org.uk/gemini/40-gemini/1037-uk-gemini-standard-and-inspire-implementing-rules[GEMINI
2.3 home page]

'''''

Expand all

Collapse all

== Metadata about the metadata record

[[30]]

Name : Metadata date

[[requirements30]]
[width="100%",cols="50%,50%",]
|===
|UK GEMINI id |30

|Definition |Date on which the metadata was last updated, or was
confirmed as being up-to-date, or if not updated, then the date it was
created

|Purpose and meaning |This is the date at which the metadata can be
considered current (rather than the dataset itself). It may be the date
at which the metadata was reviewed and confirmed as being 'current'. It
is used to distinguish which of two records with the same fileIdentifier
the system will keep.

|Obligation |Mandatory

|Occurrence |Single

|Data type |Date

|Domain |Single date as specified by BS ISO 8601 in the extended date
format (YYYY-MM-DD), where YYYY is the year, MM is the month and DD is
the day. Time (HH:MM:SS, where HH is the hour, MM the minutes and SS the
seconds) may be added if required, separated from the day by 'T'.

|Guidance a|
. This should be updated whenever the metadata is updated due to a
change in the dataset, or when it is reviewed and confirmed as wholly
correct.
. The date should be at an appropriate level of resolution (e.g. the
day, or the day and month).
. The date should not be in the future.

|Comment |If the metadata has not been updated, then this should be the
date when it was created.

|Examples |2001-09-02

|Revision date |May 2018
|===

Corresponding element in other standards...

[[compare30]]
[cols=",,",]
|===
|Standard |Name |Comparison
|INSPIRE Metadata |Metadata date |Equivalent
|ISO 19115:2003 |MD_Metadata.dateStamp |Equivalent
|ISO 19139:2007 |/gmd:MD_Metadata/gmd:dateStamp/gco:Date |Equivalent
|===

Change history...

[[history30]]
GEMINI 1 to 2.0: Change of name from Date of last update of metadata

Encoding guidelines...

[[coding30]]
[width="100%",cols="50%,50%",]
|===
|Guidelines |The encoding example for metadata date is shown in Example
One. Note that it is possible to record the date and time of the
metadata instance using the encoding shown in Example Two.

|Example a|
`Example One                   `

....
<gmd:MD_Metadata>
  ...
  <gmd:dateStamp>
    <gco:Date>2009-10-15</gco:Date>
  </gmd:dateStamp>
  ...
</gmd:MD_Metadata>
....

Example Two (date and time)

....
<gmd:MD_Metadata>
  ...
  <gmd:dateStamp>
    <gco:DateTime>2009-10-15T12:01:30</gco:DateTime>
  </gmd:dateStamp>
  ...
</gmd:MD_Metadata>
....

|===

Metadata errors observed...

[[errors30]]
[cols=",",]
|===
|Errors observed |This is used to distinguish which of two records with
the same fileIdentifier the system will keep. Even if the records are
moved to a different server, if the fileIdentifier and metadata date are
the same, the harvester will not collect the new files.
|===

[[33]]

Name : Metadata language

[[requirements33]]
[width="100%",cols="50%,50%",]
|===
|UK GEMINI id |33

|Definition |Language used for documenting the metadata

|Purpose and meaning |The purpose of this is to identify the language
used in a multi-lingual metadata service, for example in the INSPIRE
geo-portal.

|Obligation |Mandatory

|Occurrence |Single

|Data type |CharacterString

|Domain |Free text

|Guidance a|
. It is recommended to select a value from a controlled vocabulary, for
example that provided by ISO 639-2 which uses three-letter primary tags
with optional subtags.
. The values for the UK are:
+
[cols=",",]
!===
!English !eng
!Welsh !cym^*^
!Irish !gle
!Gaelic (Scottish) !gla
!Cornish !cor
!Ulster Scots !sco
!===
+
^*^ISO 639/2 has two codes for Welsh: textual ('cym') and bibliographic
('wel'). For GEMINI we recommend using cym, which abbreviates that
language's own name for itself.
. Other official European languages are listed at
http://ec.europa.eu/languages/policy/linguistic-diversity/official-languages-eu_en.htm[Official
languages of the EU].
. In general, a default value of 'eng' can be applied.
. If there is only a small amount of metadata in a second language, e.g.
Alternative title, then Metadata language should still indicate the main
language.

|Comment |For INSPIRE, the metadata itself must be in one of the
official European languages, such as English or Irish.

|Examples |eng

|Revision date |September 2018
|===

Corresponding element in other standards...

[[compare33]]
[cols=",,",]
|===
|Standard |Name |Comparison

|INSPIRE Metadata |Metadata language |Equivalent

|ISO 19115:2003 |MD_Metadata.language |Equivalent

|ISO 19139:2007 |/gmd:MD_Metadata/gmd:language/gmd:LanguageCode
|Equivalent
|===

Change history...

[[history33]]
GEMINI 1 to 2.0: New element

Encoding guidelines...

[[coding33]]
[width="100%",cols="50%,50%",]
|===
|Guidelines |INSPIRE recommends providing the name of the language as
content of the gmd:LanguageCode element

|Example a|
`                   `

....
<gmd:MD_Metadata>
  ...
  <gmd:language>
    <gmd:LanguageCode 
      codeList='http://www.loc.gov/standards/iso639-2/php/code_list.php' 
      codeListValue='eng'>English</gmd:LanguageCode>
  </gmd:language>
  ...
</gmd:MD_Metadata>
     
....

|===

Metadata errors observed...

[[errors33]]
[width="100%",cols="50%,50%",]
|===
|Errors observed |*Metadata language missing* +
Metadata language is optional in ISO 19115 and GEMINI 2.2, but mandatory
for INSPIRE and therefore in GEMINI 2.3. This is now checked by the UK
Location GEMINI schematron.
|===

[[35]]

Name : Metadata point of contact

[[requirements35]]
[cols=",",]
|===
|UK GEMINI id |35

|Definition |Party responsible for the creation and maintenance of the
metadata

|Purpose and meaning |This is the organisation or role in an
organisation responsible for this metadata.

|Obligation |Mandatory

|Occurrence |Multiple

|Data type |CharacterString

|Domain |Free text

|Guidance |Should include organisation name and contact email address,
as described under Responsible party.

|Comment |

|Examples |Large-scale Topographic Data Manager, Ordnance Survey.

|Revision date |July 2009
|===

Corresponding element in other standards...

[[compare35]]
[cols=",,",]
|===
|Standard |Name |Comparison

|INSPIRE Metadata |Metadata point of contact |Equivalent

|ISO 19115:2003 |MD_Metadata.contact > CI_ResponsibleParty |ISO 19115
has a general class

|ISO 19139:2007 |/gmd:MD_Metadata/gmd:contact/gmd:CI_ResponsibleParty |
|===

Change history...

[[history35]]
GEMINI 1 to 2.0: New element

Encoding guidelines...

[[coding35]]
[width="100%",cols="50%,50%",]
|===
|Guidelines a|
* The encoding example for metadata point of contact is shown below.
Note that the example shows the minimum required information.
* The format of address and contact information is described at
link:component/content/article?id=1048#2.2.8[Responsible party], with a
more fully populated example.
* More than one metadata point of contact may be expressed in metadata.
The role of at least one metadata point of contact shall be
'pointOfContact'.

|Example a|
`Example showing minimum required information                   `

....
<gmd:MD_Metadata>
  ...
  <gmd:contact>
    <gmd:CI_ResponsibleParty>
      <gmd:organisationName>
        <gco:CharacterString>SeaZone Solutions</gco:CharacterString>
      </gmd:organisationName>
      <gmd:contactInfo>
        <gmd:CI_Contact>
          <gmd:address>
            <gmd:CI_Address>
              <gmd:electronicMailAddress>
                <gco:CharacterString>info@seazone.com</gco:CharacterString>
              </gmd:electronicMailAddress>
            </gmd:CI_Address>
          </gmd:address>
        </gmd:CI_Contact>
      </gmd:contactInfo>
      <gmd:role>
        <gmd:CI_RoleCode 
          codeList='https://schemas.isotc211.org/schemas/19139/resources/codelist/gmxCodelists.xml#CI_RoleCode' 
          codeListValue='pointOfContact'>pointOfContact</gmd:CI_RoleCode>
      </gmd:role>
    </gmd:CI_ResponsibleParty>
  </gmd:contact>
  ...
</gmd:MD_Metadata>
     
....

|===

Metadata errors observed...

[[errors35]]
No error information available

[[39]]

Name : Resource type

[[requirements39]]
[width="100%",cols="50%,50%",]
|===
|UK GEMINI id |39

|Definition |Scope to which metadata applies

|Purpose and meaning |To distinguish between datasets, series, and
services

|Obligation |Mandatory

|Occurrence |Single

|Data type |CodeList

|Domain a|
MD_ScopeCode from ISO 19115. Codes to be used for datasets and dataset
series are:

* dataset
* series

|Guidance |Identify whether resource is a dataset or a series
(collection of datasets with a common specification).

|Comment |

|Examples |dataset

|Revision date |July 2009
|===

Corresponding element in other standards...

[[compare39]]
[cols=",,",]
|===
|Standard |Name |Comparison
|INSPIRE Metadata |Resource type |Identical
|ISO 19115:2003 |MD_Metadata.hierarchyLevel |Equivalent
|ISO 19139:2007 |/gmd:MD_Metadata/gmd:hierarchyLevel |Equivalent
|===

Change history...

[[history39]]
GEMINI 1 to 2.0: New element, required for INSPIRE

Encoding guidelines...

[[coding39]]
[width="100%",cols="50%,50%",]
|===
|Guidelines |No specific rules for this metadata element

|Example a|
`                   `

....
<gmd:MD_Metadata>
  ...
  <gmd:hierarchyLevel>
            <gmd:MD_ScopeCode codeListValue='dataset' 
              codeList='https://schemas.isotc211.org/schemas/19139/resources/codelist/gmxCodelists.xml#MD_ScopeCode'>dataset</gmd:MD_ScopeCode>
  </gmd:hierarchyLevel>
  ...
</gmd:MD_Metadata>
....

|===

Metadata errors observed...

[[errors39]]
No error information available

[[45]]

Name : File Identifier

[[requirements45]]
[width="100%",cols="50%,50%",]
|===
|UK GEMINI id |45

|Definition |Unique identifier for this metadata file

|Purpose and meaning |To support the operation of UK Location and
INSPIRE, discovery metadata records must include a File Identifier for
the resource.

|Obligation |Mandatory

|Occurrence |Single

|Data type |CharacterString

|Domain |Free text

|Guidance a|
. File Identifier must be populated with a unique identifier. This may
be a UUID generated by a metadata creation tool. +
*Once created and published to UK Location, the File Identifier must not
be changed.* +
A change to the File Identifier would represent the creation of a new
resource. +
If the UK Catalogue receives two records with the same File Identifier,
the one with the more recent metadata date will be retained.
. Persistence and uniqueness across the metadata infrastructure are key
. Only use characters that are allowed in URIs
(https://www.ietf.org/rfc/rfc3986.txt[RFC3986]), in particular, do not
use curly brackets
. http://www.opengeospatial.org/standards/cat[ISO AP 1.0] recommends
that it is a UUID

|Comment |File Identifier should not be confused with the UK GEMINI2
metadata item link:#36[Resource identifier], which identifies the data
resource being described. +

|Examples |

|Revision date |March 2019
|===

Corresponding element in other standards...

[[compare45]]
[cols=",,",]
|===
|Standard |Name |Comparison
|INSPIRE Metadata |metadata/2.0/rec/common/fileIdentifier |Equivalent
|ISO 19115:2003 |MD_Metadata.fileIdentifier |Equivalent
|ISO 19139:2007 |/gmd:MD_Metadata/gmd:fileIdentifier |Equivalent
|===

Change history...

[[history45]]
* introduced in the UK Location application profile and XML encoding
* New element in GEMINI 2.3

Encoding guidelines...

[[coding45]]
[width="100%",cols="50%,50%",]
|===
|Guidelines a|
. The first XML child element of any GEMINI2 metadata instance shall be
gmd:fileIdentifier. The content of this XML element is the identifier of
the metadata instance. File identifier is not a metadata item of
GEMINI2. It is not to be confused with the metadata item
link:#36[Resource identifier].
. The content of the XML element shall be a unique managed identifier,
such as a system generated UUID. Once the identifier has been set for a
metadata instance it shall not change.

|Example a|
`                   `

....
<gmd:MD_Metadata>
  <gmd:fileIdentifier>
    <gco:CharacterString>98e25be5-388d-4be3-bc5f-ba07ef6009b2</gco:CharacterString>
  </gmd:fileIdentifier>
  ...
</gmd:MD_Metadata>
....

|===

Metadata errors observed...

[[errors45]]
[width="100%",cols="50%,50%",]
|===
|Errors observed a|
. Two records with the same identifier, resulting in only one being
harvested
. New identifier for an existing record, leading to duplicate records
. Identifiers wrapped in curly brackets

|===

[[47]]

Name : Hierarchy level name

[[requirements47]]
[width="100%",cols="50%,50%",]
|===
|UK GEMINI id |47

|Definition |Name of the hierarchy level for which the metadata is
provided

|Purpose and meaning |Required in the ISO 19115 encoding of GEMINI 2.3
metadata records, where it allows for multiple scoped sections in the
metadata.

|Obligation |Conditional, required when Resource type (ISO
hierarchyLevel) is not "dataset".

|Occurrence |Single

|Data type |CharacterString

|Domain |Free text

|Guidance |Set to "service", "series" as appropriate. Can be set
"dataset", but in that case it is optional

|Comment |

|Examples a|
* series

|Revision date |April 2020
|===

Corresponding element in other standards...

[[compare47]]
[cols=",,",]
|===
|Standard |Name |Comparison

|INSPIRE Metadata |see metadata/2.0/req/sds/resource-type, even for
series |Equivalent

|ISO 19115:2003 |MD_Metadata.hierarchyLevelName |Equivalent

|ISO 19139:2007 |/gmd:MD_Metadata/gmd:hierarchyLevelName |Equivalent
|===

Change history...

[[history47]]
New element in GEMINI 2.3

Encoding guidelines...

[[coding47]]
[width="100%",cols="50%,50%",]
|===
|Guidelines |No specific rules for this metadata element
|Example a|
`                                      `

Example 1 - dataset, where hierarchyLevelName could just be omitted

....
<gmd:MD_Metadata>
  ...
  <gmd:hierarchyLevelName gco:nilReason="inapplicable"/>
  ...
  <gmd:identificationInfo>
    <gmd:MD_DataIdentification id="BGS-13607137">
      ...
    </gmd:MD_DataIdentification>
  </gmd:identificationInfo>
  ...
</gmd:MD_Metadata>
          
....

Example 2 - series, where hierarchyLevelName is required

....
<gmd:MD_Metadata>
  ...
  <gmd:hierarchyLevelName>
    <gco:CharacterString>series</gco:CharacterString>
  </gmd:hierarchyLevelName>
  ...
  <gmd:identificationInfo>
    <gmd:MD_DataIdentification id="OSTerrain50">
      ...
    </gmd:MD_DataIdentification>
  </gmd:identificationInfo>
  ...
</gmd:MD_Metadata>
....

|===

Metadata errors observed...

[[errors47]]
No error information available

[[49]]

Name : Parent identifier

[[requirements49]]
[cols=",",]
|===
|UK GEMINI id |49

|Definition |File identifier of the metadata that is a parent to this
child metadata

|Purpose and meaning |Supports parent-child relationships in metadata.
Allows navigation from a dataset record to the series record of which it
forms a part.

|Obligation |Optional

|Occurrence |Single

|Data type |CharacterString

|Domain |free text

|Guidance |Only to be used if the dataset is part of a series

|Comment |

|Examples |

|Revision date |May 2018
|===

Corresponding element in other standards...

[[compare49]]
[cols=",,",]
|===
|Standard |Name |Comparison
|ISO 19115:2003 |MD_parentidentifier.scope |Equivalent
|ISO 19139:2007 |/gmd:MD_Metadata/gmd:parentIdentifier |Equivalent
|===

Change history...

[[history49]]
New element in GEMINI 2.3

Encoding guidelines...

[[coding49]]
[width="100%",cols="50%,50%",]
|===
|Guidelines |No specific rules for this metadata element

|Example a|
`                   `

....
<gmd:MD_Metadata>
  ...
  <gmd:language>
    ...
  </gmd:language>
  <gmd:parentIdentifier>
    <gco:CharacterString>d442b64c-c8c8-11e4-8731-1681e6b88999</gco:CharacterString>
  </gmd:parentIdentifier>
  <gmd:hierarchyLevel>
  ...
  </gmd:hierarchyLevel>
  ...
</gmd:MD_Metadata>
....

|===

Metadata errors observed...

[[errors49]]
No error information available

[[54]]

Name : Metadata standard name

[[requirements54]]
[width="100%",cols="50%,50%",]
|===
|UK GEMINI id |54

|Definition |Name of the metadata standard or profile used. +
The relevant standard shall be cited with a reference to the appropriate
register entry.

|Purpose and meaning |The purpose of this element is to record the
metadata standard (profile) followed when creating the metadata. This
will be important when metadata is passed from one metadata system to
another.

|Obligation |Optional

|Occurrence |Single

|Data type |CharacterString

|Domain |Free text

|Guidance |See also link:#58[Metadata standard version]

|Comment |In order to add a new metadata (profile) standard name to the
NERC vocab server, contact GEMINI at AGI

|Examples a|
* ISO 19115
* UK GEMINI
* NERC profile of ISO19115:2003

|Revision date |January 2020
|===

Corresponding element in other standards...

[[compare54]]
[cols=",,",]
|===
|Standard |Name |Comparison

|INSPIRE Metadata | |not specified

|ISO 19115:2003 |MD_Metadata.metadataStandardName |added guidance

|ISO 19139:2007 |/gmd:MD_Metadata/gmd:metadataStandardName |added
guidance
|===

Change history...

[[history54]]
* GEMINI 1 to 2.0: deleted
* GEMINI 2.3 September 2020: reinstated

Encoding guidelines...

[[coding54]]
[width="100%",cols="50%,50%",]
|===
|Guidelines |GEMINI is supported by a
https://www.bodc.ac.uk/resources/vocabularies/vocabulary_search/M25/[register
of metadata standard and profile names], hosted on the NERC vocab
server. +
The relevant standard shall be cited with a reference to the appropriate
register entry, using an Anchor.

|Example a|
`                   Example One – UK GEMINI 2.3                   `

....
<gmd:MD_Metadata>
  ...
  <gmd:metadataStandardName>
      <gmx:Anchor xlink:href="http://vocab.nerc.ac.uk/collection/M25/current/GEMINI/">UK GEMINI</gmx:Anchor>
  </gmd:metadataStandardName>
  <gmd:metadataStandardVersion>
      <gco:CharacterString>2.3</gco:CharacterString>
  </gmd:metadataStandardVersion>
  ...
</gmd:MD_Metadata>
            
Example Two – MEDIN profile of GEMINI 2.3 
...
  <gmd:metadataStandardName>
     <gmx:Anchor xlink:href="http://vocab.nerc.ac.uk/collection/M25/current/MEDIN/">MEDIN</gmx:Anchor>
  </gmd:metadataStandardName>
  <gmd:metadataStandardVersion>
      <gco:CharacterString>3.0</gco:CharacterString>
  </gmd:metadataStandardVersion>
...
         
....

|===

Metadata errors observed...

[[errors54]]
No error information available

[[55]]

Name : Metadata standard version

[[requirements55]]
[width="100%",cols="50%,50%",]
|===
|UK GEMINI id |55

|Definition |Version of the metadata standard (profile) used

|Purpose and meaning |The purpose of this element is to record the
version of the metadata standard (profile) followed when creating the
metadata

|Obligation |Optional

|Occurrence |Single

|Data type |CharacterString

|Domain |Free text

|Guidance |The relevant version or edition number of the standard shall
be given, with any profile version in brackets. +
See also link:#57[Metadata standard name]

|Comment |This will be important when metadata is passed from one
metadata system to another.

|Examples a|
* 2003
* 2.3

|Revision date |June 2021
|===

Corresponding element in other standards...

[[compare55]]
[cols=",,",]
|===
|Standard |Name |Comparison

|INSPIRE Metadata | |not specified

|ISO 19115:2003 |MD_Metadata.metadataStandardVersion |added guidance

|ISO 19139:2007 |/gmd:MD_Metadata/gmd:metadataStandardVersion |added
guidance
|===

Change history...

[[history55]]
* GEMINI 1 to 2.0: deleted
* GEMINI 2.3 September 2020: reinstated
* GEMINI 2.3 June 2021: text of XML example changed to match
link:#54[Metadata standard name]

Encoding guidelines...

[[coding55]]
[width="100%",cols="50%,50%",]
|===
|Guidelines |No specific rules for this metadata element

|Example a|
`                   Example One – GEMINI 2.3                   `

....
<gmd:MD_Metadata>
  ...
  <gmd:metadataStandardName>
      <gmx:Anchor xlink:href="http://vocab.nerc.ac.uk/collection/M25/current/GEMINI/">UK GEMINI</gmx:Anchor>
  </gmd:metadataStandardName>
  <gmd:metadataStandardVersion>
      <gco:CharacterString>2.3</gco:CharacterString>
  </gmd:metadataStandardVersion>
  ...
</gmd:MD_Metadata>
          
....

|===

Metadata errors observed...

[[errors55]]
No error information available

'''''

== Metadata about the resource

[[1]]

Name : Title

[[requirements1]]
[width="100%",cols="50%,50%",]
|===
|UK GEMINI id |1

|Definition |Name given to the resource

|Purpose and meaning |The purpose of this element is to provide a
readily recognisable name for the resource.

|Obligation |Mandatory

|Occurrence |Single

|Data type |CharacterString

|Domain |Free text

|Guidance a|
. The name should be readily recognisable
. The title should be the formal or product name for the data resource,
if existing.
. If no name exists, then a title should be created that is short,
encapsulates the subject, temporal and spatial coverage of the data
resource, and does not contain terms or jargon that make it
incomprehensible.
. Acronyms are acceptable in the Title providing they are fully expanded
in the abstract or Alternative Title.

|Comment |

|Examples a|
* OS MasterMap Topography Layer
* Voter participation in Liverpool local elections, 1994, by ward

|Revision date |March 2019
|===

Corresponding element in other standards...

[[compare1]]
[cols=",,",]
|===
|Standard |Name |Comparison

|INSPIRE Metadata |Resource title |Equivalent

|ISO 19115:2003 |MD_Identification.citation > CI_Citation.title
|Equivalent

|ISO 19139:2007
|/gmd:MD_Metadata/gmd:identificationInfo/gmd:MD_DataIdentification/gmd:citation/gmd:CI_Citation/gmd:title
|Equivalent
|===

Change history...

[[history1]]

Encoding guidelines...

[[coding1]]
[width="100%",cols="50%,50%",]
|===
|Guidelines |Cannot be empty

|Example a|
`                   `

....
<gmd:MD_Metadata>
...
<gmd:identificationInfo>
  <gmd:MD_DataIdentification id="BGS-13606338">
    <gmd:citation>
      <gmd:CI_Citation>
        <gmd:title>
          <gco:CharacterString>Digital Geological Map Data of Great Britain - 625k</gco:CharacterString>
        </gmd:title>
        ...
      </gmd:CI_Citation>
    </gmd:citation>
  </gmd:MD_DataIdentification>
</gmd:identificationInfo>
...
</gmd:MD_Metadata>
....

|===

Metadata errors observed...

[[errors1]]
No error information available

[[2]]

Name : Alternative title

[[requirements2]]
[width="100%",cols="50%,50%",]
|===
|UK GEMINI id |2

|Definition |Short name, other name, acronym or alternative language
title for the data resource

|Purpose and meaning |The purpose of this element is to record any
alternative titles by which the data resource is known.

|Obligation |Optional

|Occurrence |Multiple

|Data type |CharacterString

|Domain |Free text

|Guidance a|
. Should be provided when the data resource has more than one title.
. There is no need to fill in this entry unless there are other names
used for the dataset, for example historic names.
. Commonly used abbreviations or acronyms should be recorded. If the
acronym or abbreviation has been used in the main Title, then use the
full name in the Alternative Title.
. Other language equivalents should be recorded where they exist, for
example the Welsh language title (although this title may refer to a
different data resource).
. Entries should be short and concise.

|Comment |

|Examples |OS large-scale data

|Revision date |May 2021
|===

Corresponding element in other standards...

[[compare2]]
[cols=",,",]
|===
|Standard |Name |Comparison

|INSPIRE Metadata |None |INSPIRE has no Alternative title, only a single
title

|ISO 19115:2003 |MD_Identification.citation > CI_Citation.alternateTitle
|Equivalent

|ISO 19139:2007
|/gmd:MD_Metadata/gmd:identificationInfo/gmd:MD_DataIdentification/gmd:citation/gmd:CI_Citation/gmd:alternateTitle
|Equivalent
|===

Change history...

[[history2]]

Encoding guidelines...

[[coding2]]
[width="100%",cols="50%,50%",]
|===
|Guidelines |Note that more than one alternative title may be presented,
as shown in the example below.

|Example a|
`Example one                   `

....
<gmd:MD_Metadata>
...
<gmd:identificationInfo>
  <gmd:MD_DataIdentification id="BGS-13480426">
    <gmd:citation>
      <gmd:CI_Citation>
    ...
    <gmd:alternateTitle>
      <gco:CharacterString>Geology onshore digital maps 1:625 000 scale</gco:CharacterString>
    </gmd:alternateTitle>
    <gmd:alternateTitle>
      <gco:CharacterString>DiGMapGB-625</gco:CharacterString>
    </gmd:alternateTitle>
    ...
      </gmd:CI_Citation>
    </gmd:citation>
  </gmd:MD_DataIdentification>
</gmd:identificationInfo>
...
</gmd:MD_Metadata>
....

Example two

....
<gmd:MD_Metadata>
...
<gmd:identificationInfo>
  <gmd:MD_DataIdentification id="CEH-LCM2007">
    <gmd:citation>
      <gmd:CI_Citation>
    ...
    <gmd:alternateTitle>
      <gco:CharacterString>Land Cover Map 2007 (1km raster, percentage aggregate class, N.Ireland)</gco:CharacterString>
    </gmd:alternateTitle>
    ...
      </gmd:CI_Citation>
    </gmd:citation>
  </gmd:MD_DataIdentification>
</gmd:identificationInfo>
...
</gmd:MD_Metadata>
....

|===

Metadata errors observed...

[[errors2]]
No error information available

[[3]]

Name : Dataset language

[[requirements3]]
[width="100%",cols="50%,50%",]
|===
|UK GEMINI id |3

|Definition |Language used in the data resource

|Purpose and meaning |This is the written language used for any text in
the dataset.

|Obligation |Mandatory

|Occurrence |Multiple

|Data type |CharacterString

|Domain |Free text

|Guidance a|
. A code should be selected from ISO 639-2, which uses three-letter
primary tags with optional subtags – see
http://www.loc.gov/standards/iso639-2/php/code_list.php
. The values for the UK languages are:
+
[cols=",",]
!===
!*English* !eng
!*Welsh* !cym
!*Irish* !gle
!*Gaelic (Scottish)* !gla
!*Cornish* !cor
!*Ulster Scots* !sco
!===
+
ISO 639-2 allows either 'cym' or 'wel' for Welsh, but two values for the
same language causes confusion, and it is recommended that 'cym' be
used.
. In many cases, a default value of 'eng' can be applied.
. Other official European languages are listed at
http://ec.europa.eu/languages/policy/linguistic-diversity/official-languages-eu_en.htm[Official
languages of the EU].
. If there is no textual information in the data resource, then the
special code value *zxx* of ISO 639-2/B reserved for "no linguistic
content; not applicable" shall be used.

|Comment |

|Examples |eng

|Revision date |September 2018
|===

Corresponding element in other standards...

[[compare3]]
[cols=",,",]
|===
|Standard |Name |Comparison

|INSPIRE Metadata |Resource language |Equivalent

|ISO 19115:2003 |MD_DataIdentification.language |Equivalent, but ISO
19115 only allows a single value

|ISO 19139:2007
|/gmd:MD_Metadata/gmd:identificationInfo/gmd:MD_DataIdentification/gmd:language/gmd:LanguageCode
|Equivalent
|===

Change history...

[[history3]]
. GEMINI 1 to 2: Obligation changed from mandatory
. GEMINI 2 to 2.2: Obligation changed (back) to mandatory

Encoding guidelines...

[[coding3]]
[width="100%",cols="50%,50%",]
|===
|Guidelines a|
. Note that according to the ISO 19115 logical model the language
property is typed as a CharacterString. The use of the
gco:CharacterString type is permitted by the ISO 19139 schemas but this
approach shall not be used to encode GEMINI2 metadata. Instead the XML
element gmd:LanguageCode, which substitutes for gco:CharacterString,
shall be used.
. The XML element gmd:LanguageCode is implemented as a code list
element. Note that the codeList attribute should have the following
value in GEMINI2 metadata instances:
http://www.loc.gov/standards/iso639-2/php/code_list.php
. Note however, that this URL resolves to an HTML web page rather than a
service endpoint providing ISO 639-2 language codes.

|Example a|
`Example following the INSPIRE recommendation of using the name of the language as                   the                   content of the gmd:LanguageCode                   `

....
<gmd:MD_Metadata>
  ...
  <gmd:identificationInfo>
    <gmd:MD_DataIdentification id="DS-123456">
      ...
      <gmd:language>
        <gmd:LanguageCode codeList="http://www.loc.gov/standards/iso639-2/php/code_list.php"
            codeListValue="eng">
          English
        </gmd:LanguageCode>
      </gmd:language>
      ...
    </gmd:MD_DataIdentification>
  </gmd:identificationInfo>
  ...
</gmd:MD_Metadata>
....

|===

Metadata errors observed...

[[errors3]]
No error information available

[[4]]

Name : Abstract

[[requirements4]]
[width="100%",cols="50%,50%",]
|===
|UK GEMINI id |4

|Definition |Brief narrative summary of the resource

|Purpose and meaning |The abstract should provide a clear and concise
statement that enables the reader to understand the content of the data
or service

|Obligation |Mandatory

|Occurrence |Single

|Data type |CharacterString

|Domain |Free text

|Guidance a|
The abstract should provide a clear statement of the content of the data
and not general background information.

. State what the 'things' are that are recorded.
. State the key aspects recorded about these things.
. State what form the data takes.
. State any other limiting information, such as time period of validity
of the data.
. Add purpose of data resource where relevant (e.g. for survey data).
. Include a description of the extent or location.
. Include legal references.
. Aim to be understood by non-experts.
. Do not include general background information.
. Avoid jargon and unexplained abbreviations.
. Acronyms should be expanded to the full name along with the
abbreviated version at the beginning of the abstract. The abbreviated
version can then be used (see examples below).

Note: the Schematron validation will raise an error if the abstract is
less than 100 characters, or is the same as the title.

|Comment |The most important details of the description should be
summarised in the first sentence, or the first 256 characters.

|Examples a|
. This file contains the digital vector boundaries for Lower Layer Super
Output Areas (LSOA) as at 31 December 2011 in England and Wales.
. This file contains the National Statistics Postcode Lookup (NSPL) for
the United Kingdom as at February 2017.

|Revision date |March 2019
|===

Corresponding element in other standards...

[[compare4]]
[cols=",,",]
|===
|Standard |Name |Comparison

|INSPIRE Metadata |Resource abstract |Equivalent

|ISO 19115:2003 |MD_Identification.abstract |Equivalent

|ISO 19139:2007
|/gmd:MD_Metadata/gmd:identificationInfo/gmd:MD_DataIdentification/gmd:abstract
|Equivalent
|===

Change history...

[[history4]]

Encoding guidelines...

[[coding4]]
[width="100%",cols="50%,50%",]
|===
|Guidelines |Cannot be empty

|Example a|
`                   `

....
<gmd:MD_Metadata>
  ...
  <gmd:identificationInfo>
    <gmd:MD_DataIdentification id="BGS-13603180">
      ...
      <gmd:abstract>
        <gco:CharacterString>The data shows polygonal and selected linear geological information, sourced from published 
          BGS 1:625 000 scale maps of Great Britain. 
          However, geological units are identified using the most up-to-date nomenclature that may differ from that on the 
          printed maps. The maps are generally based on published material at 1:50 000 scale and compiled using techniques of 
          selection, generalisation and exaggeration. The geology is fitted to a relevant topographic base at the time of 
          production. Full UK coverage is available. The data is available in vector format. BGS licensing terms and 
          conditions apply to external use of the data.
        </gco:CharacterString>
      </gmd:abstract>
      ...
    </gmd:MD_DataIdentification>
  </gmd:identificationInfo>
  ...
</gmd:MD_Metadata>
....

|===

Metadata errors observed...

[[errors4]]
No error information available

[[5]]

Name : Topic Category

[[requirements5]]
[width="100%",cols="50%,50%",]
|===
|UK GEMINI id |5

|Definition |Main theme(s) of the data resource

|Purpose and meaning |The purpose of this element is to provide a basic
classification for the data resource for use in initial searches

|Obligation |Mandatory when the data resource is a dataset or dataset
series. Not applicable to services.

|Occurrence |Multiple

|Data type |Class

|Domain a|
Enumeration MD_TopicCategoryCode taken from ISO 19115:

[width="100%",cols="34%,33%,33%",options="header",]
!===
!Name !Domain code !Definition
!farming !001 !rearing of animals and/or cultivation of plants +
Examples: agriculture, plantations, herding, pests and diseases
affecting crops and livestock

!biota !002 !flora and/or fauna in natural environment +
Examples: wildlife, vegetation, biological sciences, ecology, sea-life,
habitat

!boundaries !003 !legal land descriptions +
Examples: political and administrative boundaries

!climatologyMeteorologyAtmosphere !004 !processes and phenomena of the
atmosphere +
Examples: weather, climate, atmospheric conditions

!economy !005 !economic activities, conditions and employment +
Examples: production, labour, revenue, commerce, industry

!elevation !006 !height above or below sea level +
Examples: altitude, bathymetry, digital elevation models, slope

!environment !007 !environmental resources, protection and
conservation +
Examples: environmental pollution, waste storage and treatment,
environmental impact assessment, monitoring environmental risk, nature
reserves, landscape

!geoscientificInformation !008 !information pertaining to earth
sciences +
Examples: geophysical features and processes, geology, minerals, soils

!health !009 !health, health services, human ecology, and safety +
Examples: disease and illness, factors affecting health, health services

!imageryBaseMapsEarthCover !010 !base maps +
Examples: land cover, topographic maps, imagery, unclassified images

!intelligenceMilitary !011 !military bases, structures, activities +
Examples: barracks, training grounds, military transportation

!inlandWaters !012 !inland water features, drainage systems and their
characteristics +
Examples: rivers, salt lakes, dams, floods, water quality, hydrographic
charts

!location !013 !positional information and services +
Examples: addresses, geodetic networks, control points, postal zones and
services, place names

!oceans !014 !features and characteristics of salt water bodies +
(excluding inland waters) +
Examples: tides, tidal waves, coastal information, reefs

!planningCadastre !015 !information used for appropriate actions for
future use of the land +
Examples: land use maps, zoning maps, cadastral surveys, land ownership

!society !016 !characteristics of society and cultures +
Examples: settlements, anthropology, archaeology, education, demographic
data, recreational areas and activities, social impact assessments,
crime and justice, census information

!structure !017 !man-made construction +
Examples: buildings, museums, churches, factories, housing, monuments,
shops

!transportation !018 !means and aids for conveying persons and/or
goods +
Examples: roads, airports/airstrips, shipping routes, tunnels, nautical
charts, vehicle or vessel location, aeronautical charts, railways

!utilitiesCommunication !019 !energy, water and waste systems and
communications infrastructure and services +
Examples: sources of energy, water purification and distribution, sewage
collection and disposal, electricity and gas distribution, data
communication, telecommunication, radio
!===

|Guidance a|
. Select one or more categories that most closely represent the topic of
the data resource.
. If in doubt, go by the topic categories rather than the examples.
. It is not necessary to include all categories which may be applicable,
but only a limited number of most relevant should be chosen (e.g.
topographic maps should not be classified as farming).

|Comment |For greater detail within a topic, use the element
link:#6[Keyword]

|Examples |location

|Revision date |March 2019
|===

Corresponding element in other standards...

[[compare5]]
[cols=",,",]
|===
|Standard |Name |Comparison

|INSPIRE Metadata |Topic category |Equivalent

|ISO 19115:2003 |MD_DataIdentification.topicCategory |Equivalent

|ISO 19139:2007
|/gmd:MD_Metadata/gmd:identificationInfo/gmd:MD_DataIdentification/gmd:topicCategory/gmd:MD_TopicCategoryCode
|Equivalent
|===

Change history...

[[history5]]

Encoding guidelines...

[[coding5]]
[width="100%",cols="50%,50%",]
|===
|Guidelines a|
. The encoding example for topic category is shown in Example One. Note
that it is possible to include more than one topic category.
. The value of the XML element gmd:MD_TopicCategoryCode must not contain
whitespace because the values are specified by an enumerated list in the
XSD schemas. The encoding shown in Example Two, for example, will result
in an XSD schema validation error because the element content will be
parsed as shown in Example 3 (excluding the square brackets denoting the
start and end) resulting in a value that does not exist in the
enumerated list.

|Example a|
`                   `

....
<gmd:MD_Metadata>
  ...
  <gmd:identificationInfo>
    <gmd:MD_DataIdentification id="OS-234567">
      ...
      <gmd:topicCategory>
    <gmd:MD_TopicCategoryCode>geoscientificInformation</gmd:MD_TopicCategoryCode>
      </gmd:topicCategory>
      <gmd:topicCategory>
        <gmd:MD_TopicCategoryCode>environment</gmd:MD_TopicCategoryCode>
      </gmd:topicCategory>
      ...
    </gmd:MD_DataIdentification>
  </gmd:identificationInfo>
  ...
</gmd:MD_Metadata>
....

|===

Metadata errors observed...

[[errors5]]
[width="100%",cols="50%,50%",]
|===
|Errors observed a|
The topic category is a schema controlled list, not plain text. The
following example is not valid:

....
...
<gmd:topicCategory>
  <gmd:MD_TopicCategoryCode>
    environment
  </gmd:MD_TopicCategoryCode>
</gmd:topicCategory>
...
....

|===

[[6]]

Name : Keyword

[[requirements6]]
[width="100%",cols="50%,50%",]
|===
|UK GEMINI id |6

|Definition |Topic of the content of the data resource

|Purpose and meaning |The purpose of this element is to indicate the
general subject area of the data resource using keywords. This enables
searches to eliminate resources that are of no interest. Ideally, a
standardised set of keywords should be used, so that resources can be
identified in any search. This element is similar to link:#5[Topic
category], which has a coded list of high-level categories, whereas
Keyword allows more appropriate terms to describe the data resource.

|Obligation |Mandatory

|Occurrence |Multiple

|Data type |Class

|Domain a|
This class comprises the following elements:

. Keyword value (mandatory)
. Originating controlled vocabulary (conditional - if keywords originate
from a controlled vocabulary)

These are specified as follows:

[width="100%",cols="34%,33%,33%",options="header",]
!===
! !Keyword value !Originating controlled vocabulary
!Definition !topic of the content of the data resource !name of the
formally registered thesaurus or a similar authoritative source of
keywords

!Obligation !mandatory !conditional - required if keywords originate
from a controlled vocabulary

!Occurrence !multiple !single

!Data type !CharacterString !Class CI_Citation (from ISO19115)

!Domain !free text !

!Other Comments !- !a default value will generally be assigned for this
!===

|Guidance a|
. Keyword values should if possible be taken from a list of standard
subject categories, identified in the element 'Originating controlled
vocabulary'.
. Possible vocabularies include the
http://www.esd.org.uk/standards/ipsv/[Integrated Public Sector
Vocabulary (IPSV)] from the esd-toolkit, which should be used by public
sector bodies, and http://www.eionet.europa.eu/gemet/en/themes/[GEMET]
. For other Keywords, if drawn from a Controlled Vocabulary, this must
be stated.
. Terms covering the subject of the data resource should be selected.
. For conformance with INSPIRE, the keyword should describe the relevant
INSPIRE spatial data theme, such as those contained in GEMET INSPIRE;
. The formal citation for the vocabulary should be given, including at
least the title and reference date.
. Acronyms and their expanded versions as separate keywords are
acceptable within the Keyword element.
. Other standard subject category areas may be used, and different user
communities may need to create their own lists of subject areas.
. Multiple keywords may be stored in an individual metadata record, and
these may come from more than one originating controlled vocabulary.

|Comment |This element is similar to Topic Category, but allows a
broader range of values.

|Examples a|
* Land cover, General Environmental Multi-Lingual Thesaurus (GEMET)
* Gazetteer service, General Environmental Multi-Lingual Thesaurus
(GEMET)

|Revision date |May 2019
|===

Corresponding element in other standards...

[[compare6]]
[cols=",,",]
|===
|Standard |Name |Comparison

|INSPIRE Metadata |inspire-theme-keyword and additional-keywords
|Equivalent

|ISO 19115:2003 |MD_Identification.descriptiveKeywords > MD_Keywords
|Equivalent

|ISO 19139:2007
|/gmd:MD_Metadata/gmd:identificationInfo/gmd:MD_DataIdentification/gmd:descriptiveKeywords/gmd:MD_Keywords
|Equivalent
|===

Change history...

[[history6]]
. GEMINI 1 to 2.0: Change of name from 'Subject'
. GEMINI 2.0 to 2.1: expansion to include keyword value and originating
controlled vocabulary

Encoding guidelines...

[[coding6]]
[width="100%",cols="50%,50%",]
|===
|Guidelines a|
. The GEMINI2 keyword item comprises keyword value(s) and,
conditionally, the specification of an originating controlled
vocabulary. If keywords are not selected from a controlled vocabulary
the encoding shown in Example One shall be used.
. Where keywords do originate from a controlled vocabulary the encoding
shown in Example Two shall be used. Note the inclusion of the
gmd:thesaurusName XML element which contains the XML element
gmd:CI_Citation. This element must contain at least a title, reference
date and date type. In the example keywords have been selected from the
GEMET Concepts controlled vocabulary.
. Metadata records which describe a dataset that relates to one or more
of the INSPIRE themes must include the appropriate keyword(s) from the
GEMET INSPIRE themes, as illustrated in Example Two.
. Examples Two and Three show how the GEMET INSPIRE themes and the GEMET
concepts controlled vocabularies should be cited according to the
https://inspire.ec.europa.eu/documents/inspire-metadata-implementing-rules-technical-guidelines-based-en-iso-19115-and-en-iso-1[INSPIRE
guidance] link:component/content/article?id=1047[[9]].
. Note that more than one keyword value may be selected from a single
controlled vocabulary. Note also that keywords may be selected from more
than one controlled vocabulary. In this case the encoding shown in
Example Three.
. For INSPIRE if several keywords come from a single controlled
vocabulary these shall be grouped together.
. For INSPIRE the use of a gmx:Anchor element is recommended over the
use gco:CharacterString for terms from controlled vocabularies
. Recommended best practice is to select a human readable value from a
controlled vocabulary. An example from the Marine Geospatial community
is http://seadatanet.maris2.nl/v_bodc_vocab_v2/search.asp?lib=P02

|Example a|
` Example One (datasets/series) - without originating controlled vocabulary                   `

....
<gmd:MD_Metadata>
  ...
  <gmd:identificationInfo>
    <gmd:MD_DataIdentification id="NERC-54321">
      ...
      <gmd:descriptiveKeywords>
        <gmd:MD_Keywords>
          <gmd:keyword>
            <gco:CharacterString>satellite imagery</gco:CharacterString>
          </gmd:keyword>
          <gmd:keyword>
            <gco:CharacterString>earth observation</gco:CharacterString>
          </gmd:keyword>
        </gmd:MD_Keywords>
      </gmd:descriptiveKeywords>
      ...
    </gmd:MD_DataIdentification>
  </gmd:identificationInfo>
  ...
</gmd:MD_Metadata>
....

Example Two (datasets/series) - INSPIRE theme

....
<gmd:MD_Metadata>
  ...
  <gmd:identificationInfo>
    <gmd:MD_DataIdentification id="EA-100100">
      ...
      <gmd:descriptiveKeywords>
        <gmd:MD_Keywords>
          <gmd:keyword>
            <gmx:Anchor xlink:href='http://inspire.ec.europa.eu/theme/mf'>Meteorological geographical features</gmx:Anchor>
          </gmd:keyword>
          <gmd:thesaurusName>
            <gmd:CI_Citation>
              <gmd:title>
                <gmx:Anchor xlink:href='https://www.eionet.europa.eu/gemet/inspire_themes/'>GEMET - INSPIRE themes, version 1.0</gmx:Anchor>
              </gmd:title>
              <gmd:date>
                <gmd:CI_Date>
                  <gmd:date>
                    <gco:Date>2008-06-01</gco:Date>
                  </gmd:date>
                  <gmd:dateType>
                    <gmd:CI_DateTypeCode 
                      codeList='https://schemas.isotc211.org/schemas/19139/resources/codelist/gmxCodelists.xml#CI_DateTypeCode' 
                      codeListValue='publication'>publication</gmd:CI_DateTypeCode>
                  </gmd:dateType>
                </gmd:CI_Date>
              </gmd:date>
            </gmd:CI_Citation>
          </gmd:thesaurusName>
        </gmd:MD_Keywords>
      </gmd:descriptiveKeywords>
      ...
    </gmd:MD_DataIdentification>
  </gmd:identificationInfo>
  ...
</gmd:MD_Metadata>
....

Example Three (datasets/series) - keywords from 2 controlled
vocabularies

....
<gmd:MD_Metadata>
  ...
  <gmd:identificationInfo>
    <gmd:MD_DataIdentification id="CEH-111111">
      ...
      <gmd:descriptiveKeywords>
        <gmd:MD_Keywords>
          <gmd:keyword>
            <gmx:Anchor xlink:href='http://www.eionet.europa.eu/gemet/en/concept/9196'>water monitoring</gmx:Anchor>
          </gmd:keyword>
          <gmd:keyword>
             <gmx:Anchor xlink:href='http://www.eionet.europa.eu/gemet/en/concept/9214'>water quality</gmx:Anchor>
          </gmd:keyword>
          <gmd:thesaurusName>
            <gmd:CI_Citation>
              <gmd:title>
                <gmx:Anchor xlink:href='https://www.eionet.europa.eu/gemet/en/themes/'>GEMET - Concepts, version 2.4</gmx:Anchor>
              </gmd:title>
              <gmd:date>
                <gmd:CI_Date>
                  <gmd:date>
                    <gco:Date>2010-01-13</gco:Date>
                  </gmd:date>
                  <gmd:dateType>
                    <gmd:CI_DateTypeCode 
                      codeList='https://schemas.isotc211.org/schemas/19139/resources/codelist/gmxCodelists.xml#CI_DateTypeCode' 
                      codeListValue='publication'>publication</gmd:CI_DateTypeCode>
                  </gmd:dateType>
                </gmd:CI_Date>
              </gmd:date>
            </gmd:CI_Citation>
          </gmd:thesaurusName>
        </gmd:MD_Keywords>
      </gmd:descriptiveKeywords>
      <gmd:descriptiveKeywords>
        <gmd:MD_Keywords>
          <gmd:keyword>
            <gmx:Anchor xlink:href="http://inspire.ec.europa.eu/theme/lc">Land cover</gmx:Anchor>
          </gmd:keyword>
          <gmd:thesaurusName>
            <gmd:CI_Citation>
              <gmd:title>
                <gmx:Anchor xlink:href='https://www.eionet.europa.eu/gemet/en/inspire-themes/'>GEMET - INSPIRE themes, version 1.0</gmx:Anchor>
              </gmd:title>
              <gmd:date>
                <gmd:CI_Date>
                  <gmd:date>
                    <gco:Date>2008-06-01</gco:Date>
                  </gmd:date>
                  <gmd:dateType>
                    <gmd:CI_DateTypeCode 
                      codeList='https://schemas.isotc211.org/schemas/19139/resources/codelist/gmxCodelists.xml#CI_DateTypeCode' 
                      codeListValue='publication'>publication</gmd:CI_DateTypeCode>
                  </gmd:dateType>
                </gmd:CI_Date>
              </gmd:date>
            </gmd:CI_Citation>
          </gmd:thesaurusName>
        </gmd:MD_Keywords>
      </gmd:descriptiveKeywords>
      ...
    </gmd:MD_DataIdentification>
  </gmd:identificationInfo>
  ...
</gmd:MD_Metadata>
....

|===

Metadata errors observed...

[[errors6]]
[width="100%",cols="50%,50%",]
|===
|Errors observed |*Incorrect INSPIRE keywords* - +
Putting in more than one INSPIRE keyword, where the first keyword in the
list is not the correct Annex/Theme
|===

[[7]]

Name : Temporal extent

[[requirements7]]
[width="100%",cols="50%,50%",]
|===
|UK GEMINI id |7

|Definition |Date for the content of the data resource

|Purpose and meaning |This is the date or date range that identifies the
currency of the data. It may refer to the period of collection, or the
date at which it is deemed to be current.

|Obligation |Mandatory for datasets and dataset series

|Occurrence |Multiple

|Data type |Date

|Domain |Date, or two dates defining the duration of the period, as
defined by BS ISO 8601.

|Guidance a|
. Dates may be to any degree of precision, from year (YYYY) to full date
and time.
. The extended date format (YYYY-MM-DD) should be used, where YYYY is
the year, MM the month and DD the day.
. If required, time (HH:MM:SS, where HH is the hour, MM the minute and
SS the second) may be added, with T separating the two parts.
. Periods are recorded as \{fromdate/todate} (e.g.
2006-04-01/2007-03-31). Either fromdate or todate (but not both) may be
left blank to indicate uncertainty.
. There may be more than one Temporal Extent.
. The coarsest resolution allowable is 'year'.

|Comment a|
. If the data resource relates to a historic period, then this is part
of the subject, e.g. 'cretaceous period'. In this case the date is the
date of discovery or observation.
. This element should not be confused with Dataset reference date which
is an identifying date for the data resource.
. Temporal extent is the date of the validity of the data and is
different from link:#8[Dataset reference date] which is an identifying
date for the data resource. For example, an atlas might represent data
collected up to the end of one year, but have a reference date of the
following year.

|Examples a|
* 2001-01-01
* 2009-05-02T09:10:01
* 1939/1945
* /2003-03-31
* 2000/
* 19

|Revision date |May 2018
|===

Corresponding element in other standards...

[[compare7]]
[cols=",,",]
|===
|Standard |Name |Comparison

|INSPIRE Metadata |Temporal Extent |Similar, but in INSPIRE it is
optional if another temporal reference is provided.

|ISO 19115:2003 |EX_Extent > EX_TemporalExtent.extent |Identical

|ISO 19139:2007
|/gmd:MD_Metadata/gmd:identificationInfo/gmd:MD_DataIdentification/gmd:extent/gmd:EX_Extent/gmd:temporalElement
|Identical
|===

Change history...

[[history7]]
. GEMINI 1 to 2.0: Name changed from Date
. GEMINI 2.1 to 2.2: Coarsest resolution changed from 'century' to
'year'

Encoding guidelines...

[[coding7]]
[width="100%",cols="50%,50%",]
|===
|Guidelines a|
. The basic encoding for temporal extent is shown in Example One
(datasets/series). The temporal extent data shall be encoded using the
gml:TimePeriod type from the gml namespace. The underlying schemas and
standards in fact allow greater flexibility here but for the purposes of
GEMINI2 only the gml:TimePeriod XML element and the gml:TimeInstant XML
element (for single dates) shall be used. In addition gml:TimePeriod
shall contain only gml:beginPosition followed by gml:endPosition. Time
positions shall be expressed in the Gregorian calendar and UTC as per BS
ISO 8601.
. The gml:TimePeriod and gml:TimeInstant XML elements must have an
identifier in order to be schema valid. A UUID can be used, as is shown
in the Example One (datasets/series). The identifier only needs to be
unique in the scope of the metadata instance so a value of 't1' (see
Example Two - datasets/series) is acceptable. Allowable content of id
attributes:
* GML XML elements which are used in metadata have a mandatory gml:id
attribute. The value domain of the identifier is referred to as XML
name. XML names have certain restrictions. They may contain any
alphanumeric character, non-English alphanumeric characters, ideograms
and the underscore, hyphen and period. They may not contain any other
punctuation characters. The colon is allowed, but its use is reserved
for namespaces, so it cannot appear in an identifier. XML names may not
include any whitespace including spaces and carriage returns. All names
beginning with the letters XML (in uppercase, lowercase or any mixture
thereof) are reserved.
* XML names may only start with letters, ideograms and the underscore
character. Consequently, care must be taken when using the value of a
UUID as the value of an identifier because these can begin with numeric
characters. It is normal to append an underscore to the beginning of
identifier values where they begin with numbers.
* Furthermore, an identifier must be unique within the scope of the XML
document (i.e. there shall not be more than one id type attribute with a
particular identifier value).
* If an id type attribute contains an illegally formed XML name the
result will be a schema validation error.
. For format of date and date-time values:
* Dates and date-time shall be expressed in the Gregorian calendar and
UTC as per BS ISO 8601. The formatting shall be as follows, in order of
increasing precision:
** yyyy (e.g. 1995)
** yyyy-MM (e.g. 1995-01)
** yyyy-MM-dd (e.g. 1995-01-25)
** yyyy-MM-ddThh:mm:ss (e.g. 1995-01-25T12:01:55)
* The BS ISO 8601 encoding also allows negative dates to represent BC.
However, gco:Date and gco:DateTime XML elements do not accept negative
values.
* The GEMINI2 standard states that temporal extents may be given with as
coarse a granularity as century (e.g. yy or 19). However, unfortunately
this cannot be encoded in ISO 19139 XML and will result in a schema
validation error. The lowest level of granularity allowable is the year.
. GEMINI2 allows for uncertainty in the temporal extent so that one or
other, but not both, begin position or end position may be blank. The
corresponding encoding in this case makes use of the
indeterminatePosition attribute which may take a value of 'unknown'
(Example Three for datasets/series). The indeterminatePosition attribute
may also take the following values:
* 'now': in which case the current date will be taken as the value +
the now value must be used for an ongoing end position (INSPIRE)
* 'before': in which case the actual date is unknown but known to be
before the specified date
* 'after': in which case the actual date is unknown but known to be
after the specified date
. Example Four shows encoding examples using these values.

|Example a|
` Example One (datasets/series) : (gml:TimePeriod)                   `

....
            
<gmd:MD_Metadata>
  ...
  <gmd:identificationInfo>
    <gmd:MD_DataIdentification id="ABC-123456">
      ...
      <gmd:extent>
        <gmd:EX_Extent>
        ...
        <gmd:temporalElement>
              <gmd:EX_TemporalExtent>
                <gmd:extent>
              <gml:TimePeriod gml:id='_70093470-47df-45ce-b33a-60450e251c4c'>
                <gml:beginPosition>2009-01-01</gml:beginPosition>
                <gml:endPosition>2010-01-25</gml:endPosition>
              </gml:TimePeriod>
              </gmd:extent>
            </gmd:EX_TemporalExtent>
          </gmd:temporalElement>
          ...
        </gmd:EX_Extent>
      </gmd:extent>
      ...
    </gmd:MD_DataIdentification>
  </gmd:identificationInfo>
  ...
</gmd:MD_Metadata>
....

Example Two (datasets/series): (gml:TimeInstant)

....
                  
<gmd:MD_Metadata>
  ...
  <gmd:identificationInfo>
    <gmd:MD_DataIdentification id="ABC-234567">
      ...
      <gmd:extent>
        <gmd:EX_Extent>
      ...
      <gmd:temporalElement>
        <gmd:EX_TemporalExtent>
          <gmd:extent>
            <gml:TimeInstant gml:id='t1'>
          <gml:timePosition>2011-04-20</gml:timePosition>
            </gml:TimeInstant>
          </gmd:extent>
        </gmd:EX_TemporalExtent>
      </gmd:temporalElement>
      ...
        </gmd:EX_Extent>
      </gmd:extent>
      ...
    </gmd:MD_DataIdentification>
  </gmd:identificationInfo>
  ...
</gmd:MD_Metadata>
....

Example Three (datasets/series): unknown dates

....
<gmd:temporalElement>
  <gmd:EX_TemporalExtent>
    <gmd:extent>
      <gml:TimePeriod gml:id='_184029eb-4865-4503-9631-e51ab1f23588'>
        <gml:beginPosition>2009-01-01</gml:beginPosition>
        <gml:endPosition indeterminatePosition='unknown' />
      </gml:TimePeriod>
    </gmd:extent>
  </gmd:EX_TemporalExtent>
</gmd:temporalElement>
....

Example Four: other unkown or unspecified dates

....
<gml:endPosition indeterminatePosition='now'/>
<gml:endPosition indeterminatePosition='before'>2010-01-25</gml:endPosition>
<gml:endPosition indeterminatePosition='after'>2010-01-25</gml:endPosition>
....

|===

Metadata errors observed...

[[errors7]]
No error information available

[[8]]

Name : Dataset reference date

[[requirements8]]
[width="100%",cols="50%,50%",]
|===
|UK GEMINI id |8

|Definition |Reference date for the data resource

|Purpose and meaning |Dataset reference date is an identifying date for
the data resource. It is a notional date of 'publication' of the data
resource. It is different from Temporal extent which is the actual date
of the currency of the data. For example, an atlas might have the
reference date '2007', but the data will have been collected over a
period prior to this.

|Obligation |Mandatory

|Occurrence |Multiple

|Data type |Class

|Domain a|
This class comprises two elements:

* Date as defined by BS ISO 8601
* Date type (publication/revision/creation).

The extended date format (YYYY-MM-DD) defined in BS ISO 8601 should be
used, where YYYY is the year, MM is the month and DD is the day. It may
be extended to include time (HH:MM:SS), where HH is the hour, MM the
minutes and SS the seconds, with the two parts separated by the
character 'T'.

[width="100%",cols="34%,33%,33%",options="header",]
!===
! !Date !Date Type
!Definition !date used to reference data resource !event used to
describe reference date

!Obligation !mandatory !mandatory

!Occurrence !single !single

!Data type !Date !CodeList

!Domain !date as defined in ISO8601 !
!===

|Guidance a|
. Dates may be to any degree of precision, from year (YYYY) to full date
and time. The extended date format (YYYY-MM-DD) defined in BS ISO 8601
should be used, where YYYY is the year, MM the month and DD the day. It
may be extended to include time (-HH:MM:SS, where HH is the hour, MM the
minute and SS the second), with 'T' separating the two parts.
. Identify whether date refers to creation, last revision or
publication.
. More than one Dataset Reference Date may be defined, but there must
only be one of type 'creation' and only one of type 'revision'
. The date should be completed to a resolution sufficient to identify
the version. Thus if the data resource is updated annually, only a year
is required, whilst if it is updated weekly, a day is required.
. If the resource is continuously updated or is a dataset series (e.g. a
map series), then a notional current date should be provided at a
suitable level of resolution.

|Comment |INSPIRE recommends that at least the date of the last revision
should be reported for spatial datasets

|Examples a|
* 2001, publication
* 2005-05, publication
* 1997-10-01, publication
* 2009-05-02T09:10:01, publication

|Revision date |March 2019
|===

Corresponding element in other standards...

[[compare8]]
[cols=",,",]
|===
|Standard |Name |Comparison

|INSPIRE Metadata |Date of publication |Equivalent

|ISO 19115:2003 |MD_Identification.citation > CI_Citation.date
|Equivalent

|ISO 19139:2007
|/gmd:MD_Metadata/gmd:identificationInfo/gmd:MD_DataIdentification/gmd:citation/gmd:CI_Citation/gmd:date
|Equivalent
|===

Change history...

[[history8]]
GEMINI 1 to 2.0: Addition of date type

Encoding guidelines...

[[coding8]]
[width="100%",cols="50%,50%",]
|===
|Guidelines a|
* The encoding for dataset reference date is shown in Example One.
* Dates may be expressed with low precision, as shown in the example.
GEMINI2 also allows the date and time to be published in metadata. In
this case the date encoding shown in Example Two must be used.
* The format of date and date-time values is described at
link:component/content/article?id=1048#2.2.3[Dates and Times]
* Dataset reference date shall include a date type. The content of this
XML element is drawn from a
link:component/content/article?id=1048#2.2.9[code list].

|Example a|
`Example One (datasets/series): dataset reference date encoding                   example                   `

....
<gmd:MD_Metadata>
  ...
  <gmd:identificationInfo>
    <gmd:MD_DataIdentification id="BCD-012345">
      <gmd:citation>
        <gmd:CI_Citation>
          ...
          <gmd:date>
            <gmd:CI_Date>
              <gmd:date>
                <gco:Date>1995</gco:Date>
              </gmd:date>
              <gmd:dateType>
                <gmd:CI_DateTypeCode 
                    codeList='https://schemas.isotc211.org/schemas/19139/resources/codelist/gmxCodelists.xml#CI_DateTypeCode' 
                    codeListValue='publication'>publication</gmd:CI_DateTypeCode>
              </gmd:dateType>
            </gmd:CI_Date>
          </gmd:date>
          ...
        </gmd:CI_Citation>
      </gmd:citation>
      ...
    </gmd:MD_DataIdentification>
  </gmd:identificationInfo>
  ...
</gmd:MD_Metadata>
....

` Example Two - date and time                   `

....
...
<gmd:date>
  <gco:DateTime>1995-06-10T12:30:59</gco:DateTime>
</gmd:date>
...
....

|===

Metadata errors observed...

[[errors8]]
[width="100%",cols="50%,50%",]
|===
|Errors observed a|
*Confusion of Date and DateTime* +
In ISO 19115, Date and DateTime are distinct types. Although in many
elements, either is allowed, the XML encoding needs to be explicit about
which is given. It is an error to put a date (such as 2010-05-12) in a
DateTime element. +
Example of invalid structure: +

....
      
<gmd:dateStamp>
  <gco:DateTime>2012-11-15</gco:DateTime>
</gmd:dateStamp>
       
....

This should either include the time, for example: +

....
<gmd:dateStamp>
  <gco:DateTime>2012-11-15T13:50:38</gco:DateTime>
</gmd:dateStamp>
       
....

Or be explicit that it doesn't: +

....
<gmd:dateStamp>
  <gco:Date>2012-11-15</gco:Date>
</gmd:dateStamp>
....

|===

[[10]]

Name : Lineage

[[requirements10]]
[width="100%",cols="50%,50%",]
|===
|UK GEMINI id |10

|Definition |Information about the events or source data used in the
construction of the data resource

|Purpose and meaning |The purpose of this element is to give an
indication of how the data resource was created. It is useful in
determining its fitness for purpose.

|Obligation |Mandatory

|Occurrence |Single

|Data type |CharacterString

|Domain |Free text

|Guidance a|
. Some information should be provided. Include statements on the
following:
* source material
* processes used to create the data, including resolution of measurement
* method of updating
* any quality control processes
. Acronyms should be expanded to the full name along with the
abbreviated version at the beginning of the lineage. The abbreviated
version can then be used.

|Comment |This element is similar to Abstract, and some information may
be included in either element. +
Further details included in an external file may be referenced under
link:#27[Additional information].

|Examples |Addresses are taken from the Postcode Address File (PAF) and
the property found on the large-scale Ordnance Survey map. The
coordinates of an approximate centroid for the property are recorded to
a resolution of 1 metre. The dataset is updated from the PAF monthly
updates. All results are checked by plotting a group of related
addresses on the map and visually checking for errors.

|Revision date |March 2019
|===

Corresponding element in other standards...

[[compare10]]
[cols=",,",]
|===
|Standard |Name |Comparison

|INSPIRE Metadata |Lineage |Equivalent

|ISO 19115:2003 |DQ_DataQuality.lineage > LI_Lineage.statement
|Equivalent

|ISO 19139:2007
|/gmd:MD_Metadata/gmd:dataQualityInfo/gmd:DQ_DataQuality/gmd:lineage
|Equivalent
|===

Change history...

[[history10]]
GEMINI 1 to 2.0: Made mandatory for datasets and dataset series to
conform to INSPIRE

Encoding guidelines...

[[coding10]]
[width="100%",cols="50%,50%",]
|===
|Guidelines a|
. The encoding for lineage is shown in the example below.
. Note that, in addition to the lineage statement, the data quality
scope shall be encoded. For dataset metadata instances the MD_ScopeCode
code list value shall be 'dataset'. For series metadata instances the
code list value shall be 'series'.
. For INSPIRE, the lineage statement must appear in the
gmd:dataQualityInfo/gmd:DQ_DataQuality element scoped to the entire
described dataset or series

|Example a|
`                   `

....
<gmd:MD_Metadata>
  ...
  <gmd:dataQualityInfo>
    <gmd:DQ_DataQuality>
      <gmd:scope>
        <gmd:DQ_Scope>
          <gmd:level>
            <gmd:MD_ScopeCode codeListValue='dataset' 
              codeList='https://schemas.isotc211.org/schemas/19139/resources/codelist/gmxCodelists.xml#MD_ScopeCode'>dataset</gmd:MD_ScopeCode>
          </gmd:level>
        </gmd:DQ_Scope>
      </gmd:scope>
      <gmd:lineage>
        <gmd:LI_Lineage>
          <gmd:statement>
            <gco:CharacterString>The data shows polygonal and selected linear geological information, sourced from published 
              BGS 1:625 000 scale maps.</gco:CharacterString>
          </gmd:statement>
        </gmd:LI_Lineage>
      </gmd:lineage>
    </gmd:DQ_DataQuality>
  </gmd:dataQualityInfo>
</gmd:MD_Metadata>
....

|===

Metadata errors observed...

[[errors10]]
No error information available

[[15]]

Name : Extent

[[requirements15]]
[width="100%",cols="50%,50%",]
|===
|UK GEMINI id |15

|Definition |Extent of data resource

|Purpose and meaning |This element defines the geographical extent of
coverage of the data resource relative to an administrative hierarchy.
It enables searches to be carried out to find data relevant to the area
of interest. Extent polygons can be implied through reference to an
external gazetteer. Note that Extent is the coverage of the data
resource, not the individual objects in the data resource. Thus if the
data resource was national parks in England, the Extent would be
'England', even though many parts of England do not have National Parks.

|Obligation |Optional

|Occurrence |Multiple

|Data type |Class

|Domain a|
The class comprises two elements:

* (Optional) Authority code
* Code identifying the extent

|Guidance a|
. An area approximating to the extent of coverage of the data resource
should be chosen. Where the extent does not coincide with any defined
area or areas, then either the nearest equivalent including the area of
coverage, or a set of multiple areas that make up the coverage should be
provided.
. This should not be over-generalised (i.e. do not take it as Great
Britain if it only covers England and Wales).

|Comment |

|Examples a|
* England
* East Anglia
* The Wash
* http://data.os.uk/id/7000000000041546 Central Scotland, using OS
linked data as a gazetteer
* https://local-authority-eng.register.gov.uk/record/GLA, Greater London
Authority, using GDS "Local authorities in England" as a controlled list
* http://vocab.nerc.ac.uk/collection/C64/current/5/, Irish Sea, in the
NERC Vocabulary "C64, United Kingdom Charting Progress 2 sea regions"

|Revision date |August 2010
|===

Corresponding element in other standards...

[[compare15]]
[cols=",,",]
|===
|Standard |Name |Comparison

|INSPIRE Metadata |None |

|ISO 19115:2003 |MD_DataIdentification.extent > EX_Extent >
EX_GeographicExtent > EX_ GeographicDescription.geographicIdentifier
|Identical

|ISO 19139:2007
|/gmd:MD_Metadata/gmd:identificationInfo/gmd:MD_DataIdentification/gmd:extent/gmd:EX_Extent/gmd:geographicElement/gmd:EX_GeographicDescription/gmd:geographicIdentifier
|Identical
|===

Change history...

[[history15]]
GEMINI 1 to 2.0: Made optional

Encoding guidelines...

[[coding15]]
[width="100%",cols="50%,50%",]
|===
|Guidelines a|
. The examples shown below use codes (URIs in URL form) from the
http://data.os.uk[Ordnance Survey Linked Data]
link:component/content/article?id=1047[[22]]
http://data.os.uk/datasets/boundary-line[boundary data]. The code
element can be used as a URL returning a page on the internet providing
further information. The code in Example One, ending in
7000000000041546, is the URL for Central Scotland. Associated with this
code is further information, such as the geometry of Central Scotland.
. The entity responsible for managing the extent code can be expressed
in GEMINI metadata. An example of the encoding is shown in Example Two
. Recommended best practice is to select a human readable value from a
controlled vocabulary. An example from the Marine Geospatial community
is http://seadatanet.maris2.nl/v_bodc_vocab_v2/search.asp?lib=C19
. INSPIRE recommendations for encoding free text values which reference
a specific external resource or registry is to use gmx:Anchor instead of
gco:CharacterString

Note that the extent XML element is in the gmd namespace for
datasets/series. This differs from service metadata instances where the
extent XML element will be in the srv namespace.

|Example a|
` Example One (datasets/series)                   `

....
<gmd:MD_Metadata>
  ...
  <gmd:identificationInfo>
    <gmd:MD_DataIdentification id="OS-415463">
      ...
      <gmd:extent>
        <gmd:EX_Extent>
          <gmd:geographicElement>
            <gmd:EX_GeographicDescription>
              <gmd:geographicIdentifier>
                <gmd:MD_Identifier>
                  <gmd:code>
                    <gco:CharacterString>http://data.os.uk/id/7000000000041546</gco:CharacterString>
                  </gmd:code>
                </gmd:MD_Identifier>
              </gmd:geographicIdentifier>
            </gmd:EX_GeographicDescription>
          </gmd:geographicElement>
          ...
        </gmd:EX_Extent>
      </gmd:extent>
      ...
    </gmd:MD_DataIdentification>
  </gmd:identificationInfo>
  ...
</gmd:MD_Metadata>
....

Example Two (datasets/series) - Extent encoding example with authority

....
<gmd:MD_Metadata>
  ...
  <gmd:identificationInfo>
    <gmd:MD_DataIdentification id="OS-IOIOIO">
      ...
      <gmd:extent>
        <gmd:EX_Extent>
          <gmd:geographicElement>
            <gmd:EX_GeographicDescription>
              <gmd:geographicIdentifier>
                <gmd:MD_Identifier>
                  <gmd:authority>
                    <gmd:CI_Citation>
                      <gmd:title>
                        <gco:CharacterString>Ordnance Survey Linked Data</gco:CharacterString>
                      </gmd:title>
                      <gmd:date>
                        <gmd:CI_Date>
                          <gmd:date>
                            <gco:Date>2010-10-25</gco:Date>
                          </gmd:date>
                          <gmd:dateType>
                             <gmd:CI_DateTypeCode 
                               codeList='https://schemas.isotc211.org/schemas/19139/resources/codelist/gmxCodelists.xml#CI_DateTypeCode' 
                               codeListValue='revision'>revision</gmd:CI_DateTypeCode>
                          </gmd:dateType>
                        </gmd:CI_Date>
                      </gmd:date>
                    </gmd:CI_Citation>
                  </gmd:authority>
                  <gmd:code>
                    <gco:CharacterString>http://data.os.uk/id/7000000000017765</gco:CharacterString>
                  </gmd:code>
                </gmd:MD_Identifier>
              </gmd:geographicIdentifier>
            </gmd:EX_GeographicDescription>
          </gmd:geographicElement>
          ...
        </gmd:EX_Extent>
      </gmd:extent>
      ...
    </gmd:MD_DataIdentification>
  </gmd:identificationInfo>
  ...
</gmd:MD_Metadata>
....

|===

Metadata errors observed...

[[errors15]]
No error information available

[[16]]

Name : Vertical extent information

[[requirements16]]
[width="100%",cols="50%,50%",]
|===
|UK GEMINI id |16

|Definition |Vertical domain of the data resource

|Purpose and meaning |The purpose of this element is to describe the
vertical range of the data resource (where relevant).

|Obligation |Optional

|Occurrence |Multiple

|Data type |Class

|Domain a|
EX_VerticalExtent, which comprises of three elements

[width="100%",cols="25%,25%,25%,25%",]
!===
! !minimum value !maximum value !coordinate reference system

!Definition !lowest vertical extent contained in the data resource
!highest vertical extent contained in the data resource !vertical
coordinate reference system to which the maximum and minimum values are
measured

!Obligation !mandatory !mandatory !mandatory

!Occurrence !single !single !single

!Data type !real !real !class

!Domain !real number !real number !

!Other comments !- !- !For example, code provided in the EPSG Geodetic
Parameter Registry
!===

|Guidance a|
. Minimum value: Identify approximate lowest vertical extent in the
specified coordinate reference system
. Maximum value: Identify approximate highest vertical extent in the
specified coordinate reference system
. Coordinate reference system: Identify coordinate reference system used
for the vertical extent measurements. This should be recorded as a name
or as a code, for example as provided in the EPSG Geodetic Parameter
Registry produced by The International Association of Oil & Gas
Producers (see http://www.epsg-registry.org/)

|Comment |This element should be used only where vertical extent is
significant, e.g. in geology, mining, meteorology etc.

|Examples a|
* Minimum value: -100.0
* Maximum value: 0.0
* Coordinate reference system: height in metres above Newlyn Datum

|Revision date |March 2019
|===

Corresponding element in other standards...

[[compare16]]
[cols=",,",]
|===
|Standard |Name |Comparison

|INSPIRE Metadata |None |

|ISO 19115:2003 |MD_DataIdentification.extent > EX_Extent >
EX_VerticalExtent |Equivalent

|ISO 19139:2007
|/gmd:MD_Metadata/gmd:identificationInfo/gmd:MD_DataIdentification/gmd:extent/gmd:EX_Extent/gmd:verticalElement
|Equivalent
|===

Change history...

[[history16]]
* GEMINI 1 to 2.0: made optional; +
occurrence changed from multiple to single; +
description of class EX_VerticalExtent changed to match change to ISO
19115.
* GEMINI 2.1 to 2.2: made multiple again

Encoding guidelines...

[[coding16]]
[width="100%",cols="50%,50%",]
|===
|Guidelines a|
. The encoding of the vertical extent information is explained. The
vertical extent information is expressed by a minimum and maximum
coordinate value and a vertical CRS. The vertical CRS expresses the CRS
of the vertical extent coordinates alone. It does not necessarily
express the vertical CRS to which vertical coordinates in the data are
referenced - in other words it is possible that the vertical extent is
defined in a different CRS from the vertical CRS of the data. This is
convenient if it were the case that datasets within a domain were
referenced to many different vertical CRSs because it could be decided
that all vertical extents in metadata are to be referenced to a single
common vertical CRS to aid searching or understanding by users.
Searching by vertical extent, referenced to different vertical CRSs,
across metadata sets would be complicated by the need to undertake many
coordinate operations - which is not necessarily a trivial task - or
even possible in all cases.
. The CRS of vertical extent elements must be provided in order to give
meaning to the minimum and maximum coordinates. From the CRS, for
example, it is possible to determine the orientation of the coordinate
system axis (i.e. do positive values increase upwards or downwards from
the zero reference) and the units of the coordinate values.
. There are two approaches to encoding the vertical CRS: by reference
(Example One) or by value (Example Two). These examples express the same
information: that the vertical extent coordinates are referenced to
Ordnance Datum (Newlyn). Codes and GML CRS data are from the
http://www.epsg-registry.org/[EPSG Registry].
. Additionally, the gco:nilReason attribute can be used if the vertical
CRS is unknown (Example Three) but this renders the vertical extent
information ambiguous at best. Consequently it would be better to
refrain from including vertical extent information in the metadata
instance altogether.

|Example a|
`Example One (datasets/series) - Vertical CRS by reference                   `

....
<gmd:MD_Metadata>
  ...
  <gmd:identificationInfo>
    <gmd:MD_DataIdentification id="XYZ-000010">
      ...
      <gmd:extent>
        <gmd:EX_Extent>
          ...
          <gmd:verticalElement>
            <gmd:EX_VerticalExtent>
              <gmd:minimumValue>
                <gco:Real>42</gco:Real>
              </gmd:minimumValue>
              <gmd:maximumValue>
                <gco:Real>94</gco:Real>
              </gmd:maximumValue>
              <gmd:verticalCRS xlink:href='http://www.opengis.net/def/crs/EPSG/0/5701'/>
            </gmd:EX_VerticalExtent>
          </gmd:verticalElement>
        </gmd:EX_Extent>
      </gmd:extent>
      ...
    </gmd:MD_DataIdentification>
  </gmd:identificationInfo>
  ...
</gmd:MD_Metadata>
....

Example Two (datasets/series) - Vertical CRS by value

....
<gmd:MD_Metadata>
  ...
  <gmd:dataIdentification>
    <gmd:MD_DataIdentification id="XYZ-101010">
      ...
      <gmd:extent>
        <gmd:EX_Extent>
          ...
          <gmd:verticalElement>
            <gmd:EX_VerticalExtent>
              <gmd:minimumValue>
                <gco:Real>42</gco:Real>
              </gmd:minimumValue>
              <gmd:maximumValue>
                <gco:Real>94</gco:Real>
              </gmd:maximumValue>
              <gmd:verticalCRS>
                <gml:VerticalCRS gml:id='epsg-crs-5701'>
                  <gml:identifier codeSpace='OGP'>
                    urn:ogc:def:crs:EPSG::5701</gml:identifier>
                  <gml:name>ODN height</gml:name>
                  <gml:scope>Geodetic and engineering surveying.</gml:scope>
                  <gml:verticalCS>
                    <gml:VerticalCS gml:id='epsg-cs-6499'>
                      <gml:identifier codeSpace='OGP'>urn:ogc:def:cs:EPSG::6499</gml:identifier>
                      <gml:name>Vertical CS. Axis: height (H). Orientation: up. UoM: m.</gml:name>
                      <gml:remarks>Used in vertical coordinate reference systems.</gml:remarks>
                      <gml:axis>
                        <gml:CoordinateSystemAxis gml:id='epsg-axis-114' gml:uom='urn:ogc:def:uom:EPSG::9001'>
                          <gml:descriptionReference xlink:href='http://www.opengis.net/def/crs/EPSG/0/9904'/>
                          <gml:identifier codeSpace='OGP'>urn:ogc:def:axis:EPSG::114</gml:identifier>
                          <gml:axisAbbrev>H</gml:axisAbbrev>
                          <gml:axisDirection codeSpace='EPSG'>up</gml:axisDirection>
                        </gml:CoordinateSystemAxis>
                      </gml:axis>
                    </gml:VerticalCS>
                  </gml:verticalCS>
                  <gml:verticalDatum>
                    <gml:VerticalDatum gml:id='epsg-datum-5101'>
                      <gml:identifier codeSpace='OGP'>urn:ogc:def:datum:EPSG::5101</gml:identifier>
                      <gml:name>Ordnance Datum Newlyn</gml:name>
                      <gml:remarks>Orthometric heights.</gml:remarks>
                      <gml:scope>Topographic mapping, geodetic survey.</gml:scope>
                      <gml:anchorDefinition>Mean Sea Level at Newlyn between 1915 and 1921.</gml:anchorDefinition>
                    </gml:VerticalDatum>
                  </gml:verticalDatum>
                </gml:VerticalCRS>
              </gmd:verticalCRS>
            </gmd:EX_VerticalExtent>
          </gmd:verticalElement>
        </gmd:EX_Extent>
      </gmd:extent>
      ...
    </gmd:MD_DataIdentification>
  </gmd:dataIdentification>
  ...
</gmd:MD_Metadata>
....

Example Three - Vertical CRS unknown

....
<gmd:verticalElement>
  <gmd:EX_VerticalExtent>
    <gmd:minimumValue>
      <gco:Real>42</gco:Real>
    </gmd:minimumValue>
    <gmd:maximumValue>
      <gco:Real>94</gco:Real>
    </gmd:maximumValue>
    <gmd:verticalCRS gco:nilReason='unknown'/>
  </gmd:EX_VerticalExtent>
</gmd:verticalElement>
....

|===

Metadata errors observed...

[[errors16]]
No error information available

[[17]]

Name : Spatial reference system

[[requirements17]]
[width="100%",cols="50%,50%",]
|===
|UK GEMINI id |17

|Definition |Identifier, name or description of the system of spatial
referencing, whether by coordinates or geographic identifiers, used in
the data resource

|Purpose and meaning |The purpose of this element is to identify the way
in which the data is spatially referenced in the data resource. This may
be by coordinates (e.g. the National Grid of Great Britain) or
geographic identifiers (e.g. unit postcodes).

|Obligation |At least one coordinate reference system shall be given

|Occurrence |Multiple

|Data type |Class

|Domain a|
The class comprises two elements:

* Code identifying the spatial reference system
* (Conditional) codeSpace, +
- to be used if the code alone does not uniquely identify the referred
spatial reference system. +
- not to be used if the spatial reference system is listed in the
Default Coordinate Reference Systems

|Guidance a|
. For each spatial reference system
* Identify the spatial reference systems used to spatially reference the
data in the data resource;
* Check if the spatial reference system is listed in Annex D.4 (Default
Coordinate Reference Systems) of the INSPIRE
https://inspire.ec.europa.eu/Technical-Guidelines2/Metadata/[Metadata
Technical Guidelines]
. If the spatial reference system is not listed in the defaults,
identify a well-known register that defines the coordinate reference
system or, if the spatial reference system is using geographic
identifiers (such as Post Codes, NUTS, what3words, Geohashing), supply a
resolveable HTTP-URI that provides more information about the geographic
identifier system.
. Where there appears to be more than one spatial reference system used,
take the one that is used in resolving any conflict between the spatial
referencing systems (e.g. if the data is recorded referenced by unit
postcodes, and a coordinate is then associated, then unit postcode is
the spatial reference system, whereas if the data is recorded by
coordinate, and unit postcodes are added as an attribute, then it is
'National Grid of Great Britain').

|Comment a|
. Only coordinate reference systems identifiers specified in a
well-known common register shall be used
. Note that the data resource may be supplied in a range of other
reference systems in addition to that in which it is recorded.

|Examples |British National Grid

|Revision date |March 2019
|===

Corresponding element in other standards...

[[compare17]]
[cols=",,",]
|===
|Standard |Name |Comparison

|INSPIRE Metadata |crs coordinate reference system |Equivalent

|ISO 19115:2003 |MD_ReferenceSystem.referenceSystemIdentifier >
RS_Identifier.code |Equivalent

|ISO 19139:2007
|gmd:referenceSystemInfo/gmd:MD_ReferenceSystem/gmd:referenceSystemIdentifier/gmd:RS_identifier
|Equivalent
|===

Change history...

[[history17]]
GEMINI 1 to 2.0: Changed from enumerated list

Encoding guidelines...

[[coding17]]
[width="100%",cols="50%,50%",]
|===
|Guidelines a|
* When the provided text is a term or code from an externally defined
explanation or registry value, gmx:Anchor should be used instead of
gco:CharacterString
* The content of gmx:Anchor or gco:CharacterString must not be empty

|Example a|
`Example One - using gmx:Anchor for a default Coordinate Reference System (as defined                   in Annex D.4 of the INSPIRE metadata technical guidance v.2)                   `

....
<gmd:MD_Metadata>
  ...
  <gmd:referenceSystemInfo>
    <gmd:MD_ReferenceSystem>
      <gmd:referenceSystemIdentifier>
        <gmd:RS_Identifier>
          <gmd:code>
            <gmx:Anchor xlink:href='http://www.opengis.net/def/crs/EPSG/0/4258'>
            2D geodetic in ETRS89 on GRS80 (Latitude, Longitude) / ETRS89-GRS80</gmx:Anchor>
          </gmd:code>
        </gmd:RS_Identifier>
      </gmd:referenceSystemIdentifier>
    </gmd:MD_ReferenceSystem>
  </gmd:referenceSystemInfo>
  ...
</gmd:MD_Metadata>
....

Example Two - using gmx:Anchor for a non default CRS.

....
<referenceSystemInfo>
  <MD_ReferenceSystem>
    <referenceSystemIdentifier>
      <RS_Identifier>
        <code>
          <gmx:Anchor xlink:href='http://www.opengis.net/def/crs/EPSG/0/27700'>
            British National Grid (EPSG::27700)</gmx:Anchor>
        </code>
      </RS_Identifier>
    </referenceSystemIdentifier>
  </MD_ReferenceSystem>
</referenceSystemInfo>
....

Example Three - encoding example with authority

....
<gmd:MD_Metadata>
  ...
  <gmd:referenceSystemInfo>
    <gmd:MD_ReferenceSystem>
      <gmd:referenceSystemIdentifier>
        <gmd:RS_Identifier>
          <gmd:authority>
            <gmd:CI_Citation>
              <gmd:title>
                <gco:CharacterString>EPSG Geodetic Parameter Registry</gco:CharacterString>
              </gmd:title>
              <gmd:date>
               <gmd:CI_Date>
                 <gmd:date>
                   <gco:Date>2010-11-02</gco:Date>
                 </gmd:date>
                  <gmd:dateType>
                    <gmd:CI_DateTypeCode 
                      codeList='https://schemas.isotc211.org/schemas/19139/resources/codelist/gmxCodelists.xml#CI_DateTypeCode' 
                        codeListValue='revision'>revision</gmd:CI_DateTypeCode>
                  </gmd:dateType>
                </gmd:CI_Date>
              </gmd:date>
            </gmd:CI_Citation>
          </gmd:authority>
          <gmd:code>
            <gmx:Anchor xlink:href='http://www.opengis.net/def/crs/EPSG/0/4258'>
            EPSG:4258</gmx:Anchor>
          </gmd:code>
        </gmd:RS_Identifier>
      </gmd:referenceSystemIdentifier>
    </gmd:MD_ReferenceSystem>
  </gmd:referenceSystemInfo>
  ...
</gmd:MD_Metadata>
....

Example Four - encoding example for spatial reference systems using
geographic identifiers

....
<referenceSystemInfo>
  <MD_ReferenceSystem>
    <referenceSystemIdentifier>
      <RS_Identifier>
        <code>
          <gmx:Anchor xlink:href='http://www.postcodeaddressfile.co.uk/products/postcodes/postcodes_table_list.htm'>
            UK Postcodes</gmx:Anchor>
        </code>
      </RS_Identifier>
    </referenceSystemIdentifier>
  </MD_ReferenceSystem>
</referenceSystemInfo>
....

|===

Metadata errors observed...

[[errors17]]
No error information available

[[18]]

Name : Spatial resolution

[[requirements18]]
[width="100%",cols="50%,50%",]
|===
|UK GEMINI id |18

|Definition |Measure of the granularity of the data (in metres)

|Purpose and meaning |The purpose of this element is to provide an
indication of how detailed the spatial data is. It is equivalent to the
ground sample distance. It should not be confused with the scale of a
map which is purely a display attribute (the spatial resolution should
be defined in the specification of the data resource).

|Obligation |Conditional - where a resolution distance can be specified

|Occurrence |Multiple

|Data type |Real

|Domain |Value > 0

|Guidance a|
. For data capture in the field, it is the precision at which the data
is captured. This may be the accuracy for topographic surveys, or the
average sampling distance in an environmental survey.
. For data taken from maps, it is the positional accuracy of the map
(defined in the specification of the map series).
. For image data, it is the resolution of the image.
. In many given cases, only approximate values can be given.

|Comment |This should not be confused with precision which refers to the
resolution of the measurements themselves. Thus for a buildings dataset,
a building seed could be recorded to a precision of 0.1 metres, but
since the requirement is for the seed only to be within the building
footprint for the purpose of discriminating between buildings, the
spatial resolution of the buildings dataset would be the typical size of
the building, i.e. about 10 metres.

|Examples a|
* 10.0
* 0.001

|Revision date |March 2019
|===

Corresponding element in other standards...

[[compare18]]
[cols=",,",]
|===
|Standard |Name |Comparison

|INSPIRE Metadata |Spatial resolution |INSPIRE allows the option of
either Distance or Equivalent scale.

|ISO 19115:2003 |MD_DataIdentification.spatialResolution >
MD_Resolution.distance |Equivalent

|ISO 19139:2007
|/gmd:MD_Metadata/gmd:identificationInfo/gmd:MD_DataIdentification/gmd:spatialResolution
|Equivalent
|===

Change history...

[[history18]]
GEMINI 1 to 2.0: made conditional

Encoding guidelines...

[[coding18]]
[width="100%",cols="50%,50%",]
|===
|Guidelines a|
. The encoding example for spatial resolution is shown in the example
below.
. A distance measurement shall be encoded and the unit of measurement
shall be identified. The unit of measurement is identified using the uom
attribute of the XML element gco:Distance. In the case of GEMINI2 all
spatial resolution distance measurements shall be in metres. The value
of the uom attribute shall be: urn:ogc:def:uom:EPSG::9001
. This defines the unit of measure as metres by reference to the
http://www.epsg-registry.org/[EPSG registry]
link:component/content/article?id=1047[[12]].

|Example a|
`                   `

....
<gmd:MD_Metadata>
  ...
  <gmd:identificationInfo>
    <gmd:MD_DataIdentification id="OS-100100">
      ...
      <gmd:spatialResolution>
        <gmd:MD_Resolution>
          <gmd:distance>
            <gco:Distance uom='urn:ogc:def:uom:EPSG::9001'>20</gco:Distance>
          </gmd:distance>
        </gmd:MD_Resolution>
      </gmd:spatialResolution>
      ...
    </gmd:MD_DataIdentification>
  </gmd:identificationInfo>
  ...
</gmd:MD_Metadata>
....

|===

Metadata errors observed...

[[errors18]]
No error information available

[[19]]

Name : Resource locator

[[requirements19]]
[width="100%",cols="50%,50%",]
|===
|UK GEMINI id |19

|Definition |Location (address) for online access using a Uniform
Resource Locator (URL) address or similar addressing scheme

|Purpose and meaning |The purpose of this element is to point to where
the dataset, or dataset series may be directly accessed online +
OR, if no direct access is available, to an online resource providing
more information about accessing the dataset or dataset series.

|Obligation |Conditional - Must be supplied when online access is
available

|Occurrence |Multiple

|Data type |CharacterString

|Domain |Valid URL

|Guidance a|
. Identify whether the resource may be accessed.
. Determine the location of the resource (may be a URL).
. The URL of a DOI landing page should be given as a Resource locator
with a CI_OnlineFunctionCode value of "information".
. If no online access for the dataset or dataset series is available,
but there is a publicly available online resource providing additional
information about how to access the dataset of dataset series being
described, the URL pointing to this shall be given instead.
. Although not mandatory, the following ISO 19115 sub-elements should be
included, for best results with data.gov.uk:
* function (if provided, the gmd:CI_OnLineFunctionCode element should
point to one of the values of the ISO 19139 code list
CI_OnLineFunctionCode)
* name (this appears on the data.gov.uk site)
* description (data.gov.uk uses this if no 'name' provided)

|Comment a|
The URL provided as the value of the gmd:linkage element should point to
one of following type of resources:

* direct access for downloading the described dataset
* a service metadata (capabilities) document of a Spatial Data Service
used for providing this dataset
* a service WSDL document of a Spatial Data Service used for providing
this data set
* a client application that directly accesses the described dataset
* a web page with further instructions for accessing the described
dataset

|Examples |A DOI landing page:
http://doi.org/10.5285/1e7d5e08-9e24-471b-ae37-49b477f695e3

|Revision date |July 2009
|===

Corresponding element in other standards...

[[compare19]]
[cols=",,",]
|===
|Standard |Name |Comparison

|INSPIRE Metadata |Resource locator |Equivalent

|ISO 19115:2003 |MD_Distribution > MD_DigitalTransferOptions.online >
CI_OnlineResource.linkage |Equivalent

|ISO 19139:2007
|/gmd:MD_Metadata/gmd:distributionInfo/gmd:MD_Distribution/gmd:transferOptions/gmd:MD_DigitalTransferOptions/gmd:onLine/gmd:CI_OnlineResource/gmd:linkage
|Equivalent
|===

Change history...

[[history19]]
GEMINI 1 to 2.0: Modification of Online resource

Encoding guidelines...

[[coding19]]
[width="100%",cols="50%,50%",]
|===
|Guidelines a|
. The two examples illustrate different uses of Resource locator.
Example one gives direct access to the dataset. Example two gives the
location of further information about ordering the dataset. ISO 19115
and the ISO 19139 encoding provides a means of indicating the function
of the online resource using the CI_OnLineFunctionCode code list. Two
values from this code list provide a means of discriminating between a
URL that is provided for information (code list value of 'information')
and a URL that is the address used for downloading (code list value of
'download') the data.
. The gmd:transferOptions XML element of gmd:MD_Distribution is used to
encode a URL. Note that it is necessary to encode distribution format
information in all cases. If the URL that is provided is the location of
a point of contact then the distribution format is moot. However, the
distribution format property is required by an ISO 19115 constraint. In
this case the INSPIRE guidelines show the encoding using gmd:MD_Format.
Note that the element gmd:MD_Distribution must have the element
gmd:distributionFormat as its first child according to a constraint in
ISO 19115. Format information may not always be known in which case the
encoding of the element gmd:MD_Format shown in Example One shall be
used, following the
https://inspire.ec.europa.eu/documents/inspire-metadata-implementing-rules-technical-guidelines-based-en-iso-19115-and-en-iso-1[INSPIRE
guidance] link:component/content/article?id=1047[[9]]. If the format and
version values are known, then they should be given (see link:#21[Data
format]).

|Example a|
`Example one, showing only required linkage content (for a dataset)                   `

....
<gmd:MD_Metadata>
  ...
  <gmd:distributionInfo>
    <gmd:MD_Distribution>
      <gmd:distributionFormat>
        <gmd:MD_Format>
          <gmd:name>
            <gco:CharacterString>Unknown</gco:CharacterString>
          </gmd:name>
          <gmd:version gco:nilReason="inapplicable" />
        </gmd:MD_Format>
      </gmd:distributionFormat>
      ...
      <gmd:transferOptions>
        <gmd:MD_DigitalTransferOptions>
          <gmd:onLine>
            <gmd:CI_OnlineResource>
              <gmd:linkage>
                <gmd:URL>http://ogc.bgs.ac.uk/dppp/wmc/digmap625.xml</gmd:URL>
              </gmd:linkage>
            </gmd:CI_OnlineResource>
          </gmd:onLine>
        </gmd:MD_DigitalTransferOptions>
      </gmd:transferOptions>
    </gmd:MD_Distribution>
  </gmd:distributionInfo>
  ...
</gmd:MD_Metadata>
....

Example two - including name, description, and indication of function
(for a dataset ordering page)

....
<gmd:MD_Metadata>
  ...
  <gmd:distributionInfo>
    <gmd:MD_Distribution>
      <gmd:distributionFormat>
        ...
      </gmd:distributionFormat>
      ...
      <gmd:transferOptions>
        <gmd:MD_DigitalTransferOptions>
          <gmd:onLine>
            <gmd:CI_OnlineResource>
              <gmd:linkage>
                <gmd:URL>https://os.uk/opendatadownload/products.html</gmd:URL>
              </gmd:linkage>
              <gmd:name>
                <gco:CharacterString>Order OS OpenData</gco:CharacterString>
              </gmd:name>
              <gmd:description>
                <gco:CharacterString>general ordering page for all OS Open Data</gco:CharacterString>
              </gmd:description>
              <gmd:function>
                <gmd:CI_OnLineFunctionCode 
                  codeList='https://schemas.isotc211.org/schemas/19139/resources/codelist/gmxCodelists.xml#CI_OnLineFunctionCode' 
                  codeListValue='information'/>
              </gmd:function>
            </gmd:CI_OnlineResource>
          </gmd:onLine>
        </gmd:MD_DigitalTransferOptions>
      </gmd:transferOptions>
    </gmd:MD_Distribution>
  </gmd:distributionInfo>
  ...
</gmd:MD_Metadata>
....

|===

Metadata errors observed...

[[errors19]]
[width="100%",cols="50%,50%",]
|===
|Errors observed a|
In a Resource Locator, a WMS service that does not end in an ampersand
or question mark is incorrect, for example: +

....
<gmd:linkage>
  <gmd:URL>https://map.bgs.ac.uk/ArcGIS/services/BGS_Detailed_Geology/MapServer/WMSServer</gmd:URL>
</gmd:linkage>
....

Should be: +

....
<gmd:linkage>
  <gmd:URL>https://map.bgs.ac.uk/ArcGIS/services/BGS_Detailed_Geology/MapServer/WMSServer?service=WMS&request=GetCapabilities&</gmd:URL>
</gmd:linkage>
....

or: +

....
<gmd:linkage>
  <gmd:URL>https://map.bgs.ac.uk/ArcGIS/services/BGS_Detailed_Geology/MapServer/WMSServer?</gmd:URL>
</gmd:linkage>
....

 +
Defra metadata audit, October 2015: Very few records included direct
links to WMS end points.

|===

[[21]]

Name : Data format

[[requirements21]]
[width="100%",cols="50%,50%",]
|===
|UK GEMINI id |21

|Definition |Format in which the digital data is provided

|Purpose and meaning |The purpose of this element is to identify the
various options for data formats that may be provided.

|Obligation |Mandatory

|Occurrence |Multiple

|Data type |Class MD_Format from ISO 19115

|Domain a|
The following properties are expected:

* name of format
* version of format (date, number etc)

|Guidance a|
. Entries should be recognised formats for data transfer, either
standard or proprietary.
. Recommended best practice is to use a human readable term from a
controlled vocabulary.
. If the data resource is not downloadable (e.g. is view only), then
this should be stated.

|Comment |If the version of the data encoding is unknown or not
versioned, a nil reason attribute shall be specified with either
"unknown" or "inapplicable" values used correspondingly.

|Examples a|
* GML, 3.2.1
* DTF, 6.3

|Revision date |March 2019
|===

Corresponding element in other standards...

[[compare21]]
[cols=",,",]
|===
|Standard |Name |Comparison

|INSPIRE Metadata |Data encoding |Equivalent

|ISO 19115:2003 |MD_Distribution.distributionFormat > MD_Format |ISO
19115 has this element single valued

|ISO 19139:2007 |gmd:distributionFormat/gmd:MD_Format |
|===

Change history...

[[history21]]
. GEMINI 1 to 2.0: made optional
. GEMINI 2.2 to 2.3: made mandatory, but removed from services

Encoding guidelines...

[[coding21]]
[width="100%",cols="50%,50%",]
|===
|Guidelines |Both a gmd:name and gmd:version shall be provided for the
format

|Example a|
`Example One                   `

....
<gmd:MD_Metadata>
  ...
  <gmd:distributionInfo>
    <gmd:MD_Distribution>
      <gmd:distributionFormat>
        <gmd:MD_Format>
          <gmd:name>
            <gco:CharacterString>GML</gco:CharacterString>
          </gmd:name>
          <gmd:version>
            <gco:CharacterString>3.2.1</gco:CharacterString>
          </gmd:version>
        </gmd:MD_Format>
      </gmd:distributionFormat>
      ...
    </gmd:MD_Distribution>
  </gmd:distributionInfo>
  ...
</gmd:MD_Metadata>
....

Example Two - unknown version

....
   ...
     <gmd:distributionFormat>
        <gmd:MD_Format>
          <gmd:name>
            <gmx:Anchor xlink:href="https://inspire.ec.europa.eu/media-types/application/x-shapefile">Esri shapefile</gmx:Anchor>
          </gmd:name>
          <gmd:version gco:nilReason="unknown"/> 
        </gmd:MD_Format>
      </gmd:distributionFormat>
      ...
....

|===

Metadata errors observed...

[[errors21]]
[width="100%",cols="50%,50%",]
|===
|Errors observed |*No Format provided* - +
ISO 19139 requires that a format is given, either within the
'distribution' section or the 'distributor' section. +
INSPIRE & UK GEMINI encoding guidance only expects the distribution
section, as the place to encode the Resource locator, +
which effectively renders distribution format mandatory.
|===

[[23]]

Name : Responsible organisation

[[requirements23]]
[width="100%",cols="50%,50%",]
|===
|UK GEMINI id |23

|Definition |Details of the organisation(s) responsible for the
establishment, management, maintenance and distribution of the data
resource

|Purpose and meaning |This informs the user about who is responsible for
the data resource

|Obligation |Mandatory

|Occurrence |Multiple

|Data type |Class

|Domain a|
This class comprises eight elements relating to the responsible
organisation:

[width="99%",cols="16%,14%,14%,14%,14%,14%,14%",options="header",]
!===
!Metadata element name !Definition !Obligation !Occurrence !Data type
!Domain !Rules for how to fill in the entry
!contact position !role or position of the responsible person !optional
!single !CharacterString !free text !A general job title or generic role
should be identified for someone in a position of responsibility for the
data resource. +
Do not identify an individual by name, as this is subject to change
without warning and the information is impossible to keep up-to-date.

!organisation name !name of organisation !mandatory !single
!CharacterString !free text !The name of the organisation should be
given in full, without abbreviations

!postal address !postal address of the organisation !optional !single
!CharacterString !free text !The full formal postal address (as defined
for example by Royal Mail) should be given, including the postcode.

!telephone number !telephone number by which individuals can talk to the
organisation or individual !optional !single !CharacterString !free text
!The full telephone number should be given.

!email address !internet email address which individuals can use to
contact the organisation or individual !mandatory !single
!CharacterString !free text !A valid email address should be given. Do
not provide a personal email address.

!web address !World Wide Web address of organisation !optional !single
!CharacterString !free text !A valid World Wide Web address should be
given.

!responsible party role !role of the responsible organisation !mandatory
!multiple !CodeList !see
http://inspire.ec.europa.eu/metadata-codelist/ResponsiblePartyRole[INSPIRE
registry] !The role of the responsible party should be identified. +
For datasets and dataset series, at least a distributor should be given.
!===

|Guidance a|
. The organisation name, email address and responsible party role are
mandatory. Other entries should only be given that are relevant and
known.
. Where no single individual is responsible, a generic role may be
given.
. Where there are multiple Distributors / Responsible Organisations,
then a separate entry should be given for each.
. For dataset and dataset series, one of the Responsible Organisations
must be in the role of Distributor (If there is only one Responsible
Organisation recorded, then it must be in the role of Distributor.).
. Where there are several distributors, a separate entry should be given
for each.
. For best result with data.gov.uk:
* Enter 'Owner' for UK Location Data Provider role.
* Enter 'Publisher' For UK Location Data Publisher role.
+
These appear in the data.gov.uk search results.
. If the data was created by someone other than the Data Provider, this
should also be recorded, using the role value 'Originator'.

|Comment |Facsimile number is no longer required

|Examples a|
See individual elements below. +

[cols=",,",options="header",]
!===
!Metadata element name !Purpose and Meaning !Examples
!contact position !Role or post of the person to contact in the
organisation !The mapping product manager

!organisation name ! !Ordnance Survey, Great Britain

!postal address ! !Adanac Drive, Southampton, United Kingdom, SO16 0AS

!telephone number ! !+44 8456 050505

!email address ! !customerservices@os.uk

!web address !for further information about the organisation
!http://os.uk

!responsible party role !indicates whether this responsible party is
acting as distributor, publisher, author, etc. !distributor
!===

|Revision date |July 2009
|===

Corresponding element in other standards...

[[compare23]]
[cols=",,",]
|===
|Standard |Name |Comparison

|INSPIRE Metadata |Responsible party |Equivalent

|ISO 19115:2003 |MD_Identification.pointOfContact |Similar high-level
class

|ISO 19139:2007
|/gmd:MD_Metadata/gmd:identificationInfo/gmd:MD_DataIdentification/gmd:pointOfContact/gmd:CI_ResponsibleParty
|Equivalent
|===

Change history...

[[history23]]
GEMINI 1 to 2.0: This has been generalised from Distributor (and
Originator) to cover a range of possible roles, by the addition of
'responsible party role' and minor errors in the class details have been
corrected.

Encoding guidelines...

[[coding23]]
[width="100%",cols="50%,50%",]
|===
|Guidelines a|
. The encoding example for responsible organisation is shown below. The
example shows the minimum required information.
. The format of address and contact information is described at
link:component/content/article?id=1048#2.2.8[Responsible party], with a
more fully populated example.
. Note on role code: the UK Location portal (data.gov.uk site)
interprets ISO 'owner' as Data Provider, and ISO 'publisher' as Data
Publisher.

|Example a|
`Example One (datasets/series)                   `

....
<gmd:MD_Metadata>
  ...
  <gmd:identificationInfo>
    <gmd:MD_DataIdentification id="SZ-OO53">
      ...
      <gmd:pointOfContact>
        <gmd:CI_ResponsibleParty>
          <gmd:organisationName>
            <gco:CharacterString>SeaZone Solutions</gco:CharacterString>
          </gmd:organisationName>
          <gmd:contactInfo>
            <gmd:CI_Contact>
              <gmd:address>
                <gmd:CI_Address>
                  <gmd:electronicMailAddress>
                    <gco:CharacterString>info@seazone.com</gco:CharacterString>
                  </gmd:electronicMailAddress>
                </gmd:CI_Address>
              </gmd:address>
            </gmd:CI_Contact>
          </gmd:contactInfo>
          <gmd:role>
            <gmd:CI_RoleCode 
              codeList='https://schemas.isotc211.org/schemas/19139/resources/codelist/gmxCodelists.xml#CI_RoleCode' 
              codeListValue='distributor'>distributor</gmd:CI_RoleCode>
          </gmd:role>
        </gmd:CI_ResponsibleParty>
      </gmd:pointOfContact>
      ...
    </gmd:MD_DataIdentification>
  </gmd:identificationInfo>
  ...
</gmd:MD_Metadata>
....

|===

Metadata errors observed...

[[errors23]]
No error information available

[[25]]

Name : Limitations on public access

[[requirements25]]
[width="100%",cols="50%,50%",]
|===
|UK GEMINI id |25

|Definition |Restrictions imposed on accessing the data resource for
security and other reasons

|Purpose and meaning |The purpose of this element is to identify any
external restrictions on access to the data such as licence
arrangements.

|Obligation |Mandatory

|Occurrence |Multiple

|Data type |CharacterString

|Domain |Free text

|Guidance a|
. Provide information on any limitations.
. The most common access restriction should be identified.
. Where there are no limitations on public access, this should be
stated.
. More than one value may be included.
. For INSPIRE: If no limitations apply, enter 'No limitations'.
. INSPIRE recognises the following kinds of reasons for limiting public
access, listed in Article 13(1):
* (a) confidentiality of the proceedings of public authorities
* (b) international relations, public security or national defence
* (c) the course of justice
* (d) confidentiality of commercial or industrial information
* (e) intellectual property rights
* (f) confidentiality of personal data
* (g) interests of a person who supplied the data on a voluntary basis
* (h) protection of the environment
+
Each has an entry with the full text, in the INSPIRE registry,
http://inspire.ec.europa.eu/metadata-codelist/LimitationsOnPublicAccess
. At least one limitation on public access shall give an INSPIRE reason

|Comment |Limitations on public access are different from Use
constraints which are warnings about its suitability for particular
types of usage, or constraints on the use that can be made of the data.

|Examples |No restriction on public access.

|Revision date |June 2021
|===

Corresponding element in other standards...

[[compare25]]
[cols=",,",]
|===
|Standard |Name |Comparison

|INSPIRE Metadata |Limitations on public access |Equivalent

|ISO 19115:2003 |MD_Identification.resourceConstraints >
MD_LegalConstraints.accessConstraints & otherConstraints |Equivalent

|ISO 19139:2007
|/gmd:MD_Metadata/gmd:identificationInfo/gmd:MD_DataIdentification/gmd:resourceConstraints/gmd:MD_LegalConstraints/gmd:accessConstraints
& otherConstraints |Equivalent
|===

Change history...

[[history25]]
. GEMINI 1 to 2.0: Change of name from 'access constraint', and
modification of definition. +
Made mandatory, to conform to INSPIRE.
. GEMINI 2.0 to 2.1: Change to equivalent ISO 19115 element from
accessConstraint making domain free text.
. GEMINI 2.2 to 2.3: Change of encoding
. GEMINI 2.3 June 2021 fixed typo in Guidance 6 (a) and (f)

Encoding guidelines...

[[coding25]]
[width="100%",cols="50%,50%",]
|===
|Guidelines a|
. This element shall be encoded in a different
resourceConstraints/MD_LegalConstraints XML element to GEMINI element 26
Use constraints
. The LegalConstraints element shall contain a
accessConstraints/MD_RestrictionCode element with code list value
"otherRestrictions"
. The LegalConstraints element shall also contain a gmd:otherConstraints
element, with free text.
. If there are no limitations the value of gmd:otherConstraints shall be
'no limitations' (see Example Two).
. The free text shall be encoded in a gmx:Anchor element, with
xlink:href pointing to the relevant kind of limitation from the INSPIRE
Metadata registry:
http://inspire.ec.europa.eu/metadata-codelist/LimitationsOnPublicAccess
. Free text content cannot be empty
. To encode multiple limitations, include more than one
gmd:otherConstraints element

|Example a|
`Example One                   `

....
<gmd:MD_Metadata>
  ...
  <gmd:identificationInfo>
    <gmd:MD_DataIdentification id="DEF-2000">
      ...
      <gmd:resourceConstraints>
        <gmd:MD_LegalConstraints>
          ...
          <gmd:accessConstraints>
            <gmd:MD_RestrictionCode 
            codeList='https://schemas.isotc211.org/schemas/19139/resources/codelist/gmxCodelists.xml#MD_RestrictionCode' 
            codeListValue='otherRestrictions'>otherRestrictions</gmd:MD_RestrictionCode>
          </gmd:accessConstraints>
          <gmd:otherConstraints>
            <gmx:Anchor xlink:href="http://inspire.ec.europa.eu/metadata-codelist/LimitationsOnPublicAccess/INSPIRE_Directive_Article13_1e">
            [Document other restrictions here - the example 1e covers IPR]</gmx:Anchor>
          </gmd:otherConstraints>
        </gmd:MD_LegalConstraints>
      </gmd:resourceConstraints>
      ...
    </gmd:MD_DataIdentification>
  </gmd:identificationInfo>
  ...
</gmd:MD_Metadata>
....

`                   Example Two - no limitations                   `

....
...
<gmd:otherConstraints>
  <gmx:Anchor xlink:href="http://inspire.ec.europa.eu/metadata-codelist/LimitationsOnPublicAccess/noLimitations">no limitations</gmx:Anchor>
</gmd:otherConstraints>
...
          
....

Example Three - two limitations

....
...
      <gmd:resourceConstraints>
        <gmd:MD_LegalConstraints>
          ...
          <gmd:accessConstraints>
            <gmd:MD_RestrictionCode 
              codeList='https://schemas.isotc211.org/schemas/19139/resources/codelist/gmxCodelists.xml#MD_RestrictionCode' 
              codeListValue='otherRestrictions'>otherRestrictions</gmd:MD_RestrictionCode>
          </gmd:accessConstraints>
          <gmd:otherConstraints>
            <gmx:Anchor xlink:href="http://inspire.ec.europa.eu/metadata-codelist/LimitationsOnPublicAccess/INSPIRE_Directive_Article13_1b">
            publishing this data could prejudice public security</gmx:Anchor>
          </gmd:otherConstraints>
          <gmd:otherConstraints>
            <gmx:Anchor xlink:href="http://example.com/dsra_report.htm">
            Report of Data Sharing Risk Assessment</gmx:Anchor>
          </gmd:otherConstraints>
        </gmd:MD_LegalConstraints>
      </gmd:resourceConstraints>
...          
....

|===

Metadata errors observed...

[[errors25]]
[width="100%",cols="50%,50%",]
|===
|Errors observed |*Missing or incorrect information* +
Licence information should be provided, preferably by a URL. +
It is an error to state 'no limitations' in Limitations on Public
Access, when the resource is not open access. +
Defra metadata audit, October 2015: In many cases either this field has
been left empty or where the PSMA (or similar) licensing arrangements
are referenced there is either a lack of detail or no links to the
appropriate sites.
|===

[[26]]

Name : Use constraints

[[requirements26]]
[width="100%",cols="50%,50%",]
|===
|UK GEMINI id |26

|Definition |Restrictions and legal restraints on using the data
resource

|Purpose and meaning |The purpose of this element is to describe any
restrictions on usage of the data (as opposed to access)

|Obligation |Mandatory

|Occurrence |Multiple

|Data type |CharacterString

|Domain |Free text

|Guidance a|
. Provide information on any constraints to using the resource, e.g.
licensing, fees, usage restrictions, or refer to a URL where this
information is available, e.g. a licence document. If entering a URL,
enter this as a sub-element, not as part of free text. Where relevant,
Data Provider licence information should be provided in the form of a
Licence Title, and where possible, a licence URL. If more than one type
of licence is included then the URL should point to a Data Providers
page.
. Any known constraints should be identified. If no conditions apply,
then 'no conditions apply' should be recorded.

|Comment |Use constraints are different from Restrictions on public
access which describe limitations on access to the data. A data resource
can have open access (e.g. to look at it), but restricted use.

|Examples |Should not be used for navigation purposes.

|Revision date |September 2018
|===

Corresponding element in other standards...

[[compare26]]
[cols=",,",]
|===
|Standard |Name |Comparison

|INSPIRE Metadata |Conditions applying to access and use |Equivalent

|ISO 19115:2003 |MD_Identification.resourceConstraints >
MD_LegalConstraints.useConstraints & otherConstraints |Equivalent

|ISO 19139:2007
|/gmd:MD_Metadata/gmd:identificationInfo/gmd:MD_DataIdentification/gmd:resourceConstraints/gmd:MD_LegalConstraints/gmd:useConstraints
& gmd:otherConstraints |Equivalent
|===

Change history...

[[history26]]
* GEMINI 1 to 2.0: Change to free text field from enumerated list, and
making mandatory to conform with INSPIRE.
* GEMINI 2.2 to 2.3: Change of encoding

Encoding guidelines...

[[coding26]]
[width="100%",cols="50%,50%",]
|===
|Guidelines a|
. This element shall be encoded in a different
resourceConstraints/MD_LegalConstraints XML element to GEMINI element 25
Limitations on public access
. The MD_LegalConstraints element shall contain a useConstraints element
. Note: INSPIRE allows an accessConstraints element here; GEMINI
recommends using Limitations on public access for these
. The useConstraints element shall contain an MD_RestrictionCode element
with code list value "otherRestrictions"
. The LegalConstraints element shall also contain a gmd:otherConstraints
element, with free text.
. "No conditions" and "conditions unknown" shall be specified using a
gmx:Anchor link to the relevant entry in the INSPIRE metadata registry,
http://inspire.ec.europa.eu/metadata-codelist/ConditionsApplyingToAccessAndUse
. In certain circumstances it might be appropriate to refer to an
external document describing constraints. In this case the encoding
shown in Example Two may be used. This is recommended for licenses, even
the use of ISO 19115 otherRestrictions would not generally include
license restrictions, as they have their own term in the ISO 19115 code
list.
. If there are no limitations the value of gmd:otherConstraints shall be
'no limitations' (see Example Three).
. There may be more than one gmd:otherConstraints element

|Example a|
`Example One                   `

....
<gmd:MD_Metadata>
  ...
  <gmd:identificationInfo>
    <gmd:MD_DataIdentification id="bgs-0000-1">
      ...
      <gmd:resourceConstraints>
        <gmd:MD_LegalConstraints>
          <gmd:useConstraints>
            <gmd:MD_RestrictionCode 
              codeList='https://schemas.isotc211.org/schemas/19139/resources/codelist/gmxCodelists.xml#MD_RestrictionCode' 
              codeListValue='otherRestrictions'>otherRestrictions</gmd:MD_RestrictionCode>
          </gmd:useConstraints>
          <gmd:otherConstraints>
            <gco:CharacterString>Not to be used for navigation</gco:CharacterString>
          </gmd:otherConstraints>
          ...
        </gmd:MD_LegalConstraints>
      </gmd:resourceConstraints>
      ...
    </gmd:MD_DataIdentification>
  </gmd:identificationInfo>
  ...
</gmd:MD_Metadata>
....

`                   Example Two - with external file                   `

....
...
        <gmd:MD_LegalConstraints>
          <gmd:useConstraints>
            <gmd:MD_RestrictionCode 
              codeList='https://schemas.isotc211.org/schemas/19139/resources/codelist/gmxCodelists.xml#MD_RestrictionCode' 
              codeListValue='otherRestrictions'>otherRestrictions</gmd:MD_RestrictionCode>
          </gmd:useConstraints>
          <gmd:otherConstraints>
      <gmx:Anchor xlink:href='http://www.nationalarchives.gov.uk/doc/open-government-licence/version/3/'>Open Government Licence</gmx:Anchor>
          </gmd:otherConstraints>
          ...
        </gmd:MD_LegalConstraints>
...
....

Example Three - no conditions apply

....
        <gmd:MD_LegalConstraints>
          <gmd:useConstraints>
            <gmd:MD_RestrictionCode 
              codeList='https://schemas.isotc211.org/schemas/19139/resources/codelist/gmxCodelists.xml#MD_RestrictionCode' 
              codeListValue='otherRestrictions'>otherRestrictions</gmd:MD_RestrictionCode>
          </gmd:useConstraints>
          <gmd:otherConstraints>
      <gmx:Anchor xlink:href='http://inspire.ec.europa.eu/metadata-codelist/ConditionsApplyingToAccessAndUse/noConditionsApply'>no conditions apply</gmx:Anchor>
          </gmd:otherConstraints>
          ...
        </gmd:MD_LegalConstraints>
          
....

|===

Metadata errors observed...

[[errors26]]
[width="100%",cols="50%,50%",]
|===
|Errors observed |*Missing or incorrect constraints information* +
Licence information should be provided, preferably by a URL. +
It is an error to state 'no conditions apply' in Use Constraints, when
restrictions do in fact exist.
|===

[[27]]

Name : Additional information

[[requirements27]]
[width="100%",cols="50%,50%",]
|===
|UK GEMINI id |27

|Definition |Other descriptive information about the data resource

|Purpose and meaning |The purpose of this element is to record relevant
information that does not clearly belong in another element. This may be
a reference (e.g. a URL).

|Obligation |Optional

|Occurrence |Single

|Data type |CharacterString

|Domain |Free text

|Guidance a|
. Information about access to the resource should be in
link:#19[Resource locator].
. Information about fees should be in link:#25[Limitations on public
access]
. Other relevant information should be in this element, or provided by a
link which is given in this element.
. References to other documents may be by URL, DOI, or other means.

|Comment |

|Examples |For full details about this dataset, see
'https://os.uk/business-and-government/products/addressbase.html'

|Revision date |June 2021
|===

Corresponding element in other standards...

[[compare27]]
[cols=",,",]
|===
|Standard |Name |Comparison

|INSPIRE Metadata |supplemental information |

|ISO 19115:2003 |MD_Identification >
MD_DataIdentification.supplementalInformation |Equivalent

|ISO 19139:2007
|/gmd:MD_Metadata/gmd:identificationInfo/gmd:MD_DataIdentification/gmd:supplementalInformation
|Equivalent
|===

Change history...

[[history27]]
* GEMINI 2.3 20181031 Rename 'Additional information source' to
'Additional information'
* GEMINI 2.3 June 2021 fixed typo (XML syntax error) in example 2

Encoding guidelines...

[[coding27]]
[width="100%",cols="50%,50%",]
|===
|Guidelines |No specific rules for this metadata element

|Example a|
`                   Example one                   `

....
<gmd:MD_Metadata>
  ...
  <gmd:identificationInfo>
    <gmd:MD_DataIdentification id="BGS-625-001">
      ...
      <gmd:supplementalInformation>
        <gco:CharacterString>Ongoing modifications to dataset as appropriate. UK coverage except for western and southern margin 
          of Northern Ireland. As accurate as the underlying geological interpretation. 1:625k scale resolution. Bedrock theme 
          numerically coded. Superficial theme lex-rock coded.
        </gco:CharacterString>
      </gmd:supplementalInformation>
    </gmd:MD_DataIdentification>
  </gmd:identificationInfo>
  ...
</gmd:MD_Metadata>
....

`                   Example two - a link, using gmx:Anchor                   `

....
      <gmd:supplementalInformation>
        <gmx:Anchor xlink:href="http://www.bgs.ac.uk/mineralsuk/statistics/worldStatistics.html/">Background information</gmx:Anchor>
      </gmd:supplementalInformation>
          
....

|===

Metadata errors observed...

[[errors27]]
No error information available

[[36]]

Name : Resource identifier

[[requirements36]]
[width="100%",cols="50%,50%",]
|===
|UK GEMINI id |36

|Definition |Value uniquely identifying the data resource

|Purpose and meaning |The purpose of this is to uniquely identify the
data resource.

|Obligation |Mandatory for datasets and dataset series

|Occurrence |Multiple

|Data type |Class

|Domain a|
The class comprises the following elements:

* Code - Identifier code or name, often from a controlled list or
pattern defined by a code space.
* Codespace - Identifier of a code space within which one or more codes
are defined.

These elements are described in the table below

[cols=",,",]
!===
!Metadata element name !code !codeSpace

!Definition !Identifier code or name, often from a controlled list or
pattern defined by a code pace !Identifier of a code space within which
one or more codes are defined

!Obligation !mandatory !conditional ~ must be suppled if the code by
itself does not uniquely identify the resource.

!Occurrence !single !single

!Data type !CharacterString !CharacterString

!Domain !free text !free text

!Other comments !- !This code space is often defined by some authority
organization, were one organization may define multiple code spaces. The
range and format of each code space identifier is defined by that code
space authority.
!===

|Guidance a|
. The code is generally assigned by some authority, with a codespace
uniquely identifying the context of the identifier code.
. The codespace must be a character string that uniquely identifies the
namespace for the identifier code. This should be the internet domain of
the data owner/provider, +
e.g.: data.bgs.ac.uk/id/dataHolding/
. The resource is identified by a unique identifier code, generally
assigned by the data owner. A character string namespace uniquely
identifying the context of the identifier code may be added for
uniqueness. This is usually allocated by an appropriate authority such
as the manager of the spatial data infrastructure.
. Where present, a DOI should be recorded as a resource identifier, with
the codespace being doi. If a DOI landing page is also available, then
include this using an Anchor.

|Comment |Since INSPIRE metadata technical guidance version 2, it is no
longer required to use RS_Identifier if a value for code space value is
provided. +
In such cases (where there is a code space provided) it is now strongly
recommended to use MD_Identifier and encode the complete URI in the code
element.

|Examples a|
* image2000_1_nl2_multi
* doi:10.5285/1e7d5e08-9e24-471b-ae37-49b477f695e3
* 527c4cac-070c-4bca-9aaf-92bece7be902

|Revision date |May 2018
|===

Corresponding element in other standards...

[[compare36]]
[cols=",,",]
|===
|Standard |Name |Comparison

|INSPIRE Metadata |Unique resource identifier |Equivalent

|ISO 19115:2003 |MD_Identification.citation > CI_Citation.identifier
|Equivalent

|ISO 19139:2007
|/gmd:MD_Metadata/gmd:identificationInfo/gmd:MD_DataIdentification/gmd:citation/gmd:CI_Citation/gmd:identifier
|Equivalent
|===

Change history...

[[history36]]
. GEMINI 1 to 2.0: New item 'Unique resource identifier', required for
INSPIRE
. GEMINI 2.2 to 2.3: Name changed from Unique resource identifier, to
reduce confusion with W3C URI

Encoding guidelines...

[[coding36]]
[width="100%",cols="50%,50%",]
|===
|Guidelines a|
. The resource identifier can be a globally unique identifier such as a
UUID, in which case it is encoded as shown in Example One.
. The form used in Example One can also be used if the identifier is
expressed as a code space and code in URI form like
http://image2000.jrc.it#image2000_1_nl2_multi However a better way to do
this is to use the gmx:Anchor as in Example Two.
. Note that the identifier is encoded in the citation of the metadata
instance
. A resource identifier (which may be the same as the code) should also
be added to the 'id' attribute of the gmd:MD_DataIdentification type.
This follows the examples in the
https://inspire.ec.europa.eu/documents/inspire-metadata-implementing-rules-technical-guidelines-based-en-iso-19115-and-en-iso-1[INSPIRE
guidance] link:component/content/article?id=1047[[9]].
. Care must be taken with the value of the id attribute code. The
attribute 'id' has the data type xs:ID which must have as its value an
XML name. This means that it cannot start with a number, and has a
restricted set of characters it can include. This means that normally it
cannot be an UUID or an URI. The id must also be unique across all id
attributes in the metadata document
. See notes on link:component/content/article?id=1048#2.2.12[XML
Identifiers].

|Example a|
`Example One                   `

....
<gmd:MD_Metadata>
  ...
  <gmd:identificationInfo>
    <gmd:MD_DataIdentification id="_99999-def">
      <gmd:citation>
        <gmd:CI_Citation>
          ...
          <gmd:identifier>
            <gmd:MD_Identifier>
              <gmd:code>
                <gco:CharacterString>527c4cac-070c-4bca-9aaf-92bece7be902</gco:CharacterString>
              </gmd:code>
              ...
            </gmd:MD_Identifier>
          </gmd:identifier>
          ...
        </gmd:CI_Citation>
      </gmd:citation>
      ...
    </gmd:MD_DataIdentification>
  </gmd:identificationInfo>
  ...
</gmd:MD_Metadata>
....

Example Two - resolveable identifier using gmx:Anchor

....
<gmd:MD_Metadata>
  ...
  <gmd:identificationInfo>
    <gmd:MD_DataIdentification id="image2000_1_nl2_multi">
      <gmd:citation>
        <gmd:CI_Citation>
          ...
            <gmd:MD_Identifier>
              <gmd:code>
                <gmx:Anchor xlink:href='http://image2000.jrc.it#image2000_1_nl2_multi'>Image 2000 and Corine Land Cover 2000 Project</gmx:Anchor>
              </gmd:code>
            </gmd:MD_Identifier>
          </gmd:identifier>
          ...
        </gmd:CI_Citation>
      </gmd:citation>
      ...
    </gmd:MD_DataIdentification>
  </gmd:identificationInfo>
  ...
</gmd:MD_Metadata>
....

|===

Metadata errors observed...

[[errors36]]
No error information available

[[41]]

Name : Conformity

[[requirements41]]
[width="100%",cols="50%,50%",]
|===
|UK GEMINI id |41

|Definition |Statement of conformity with the product specification or
user requirement against which the data is being evaluated

|Purpose and meaning |The purpose of this is to record the conformity to
the INSPIRE or other data specification

|Obligation |Mandatory

|Occurrence |Multiple

|Data type |Class

|Domain a|
This class comprises the following elements:

* Specification
* Degree
* Explanation

For details see below. +

[width="100%",cols="25%,25%,25%,25%",options="header",]
!===
!Metadata element name !specification !degree !explanation
!Definition !Citation of the product specification or user requirement
against which data resource is evaluated !degree of conformity with the
specification !meaning of conformance for this result

!Meaning !The purpose of this element is to identify the specification
against which conformity is evaluated !The purpose of this element is to
identify the conformity of the data resource to the cited specification
!The purpose of this element is to explain the meaning of conformity in
this context

!Obligation !Mandatory !Mandatory !Mandatory

!Occurrence !single !single !single

!Data type !Class CI_Citation (from ISO19115) !Boolean !CharacterString

!Domain ! !true if conformant +
false if not conformant !free text

!Rules !Cite the specification to which the data resource should conform
!The data resource should be evaluated against the specification and the
result recorded !Include a statement about which aspects of the
specification the data resource conforms and any exceptions

!Examples !D2.8.I.5 INSPIRE Data Specification on Addresses -
Guidelines, publication, 2010-04-26 !true !Only mandatory items included
!===

|Guidance a|
. At least one conformity statement shall be to an INSPIRE
specification, even if simply to say that the data set is not conformant
or not tested
. Other conformity statements may be added, citing INSPIRE technical
guidance or other specifications
. Each conformity statement shall relate to only one specification
. Assess the conformity of the data resource against its product
specification or the INSPIRE thematic data specification.
. State the data specification to which the degree of conformity applied
and optionally an 'Explanation', for example to reference the
conformance criteria in the specification against which conformance is
being claimed.
. For INSPIRE, Datasets and dataset series shall declare conformity to
[Regulation 1089/2010].

|Comment a|
. The specification is identified in the element Specification.
. The conformance of a data resource may be considered with respect to
more than one specification.
. For INSPIRE, the citation title shall be the official title of the
INSPIRE Implementing Rule, specification document or Conformance Class
. For INSPIRE, the date given will be the date of publication of the
INSPIRE Implementing Rule, specification document or Conformance Class
. For INSPIRE Implementing Rule documents, the value of the title
element shall match exactly the official title of the cited document in
the language of the metadata.

|Examples |Conformance of a dataset to Regulation 1089/2010 would have
the title: +
Commission Regulation (EU) No 1089/2010 of 23 November 2010 implementing
Directive 2007/2/EC of the European Parliament and of the Council as
regards interoperability of spatial data sets and services., +
and would give a publication date of 2010-12-08

|Revision date |April 2020
|===

Corresponding element in other standards...

[[compare41]]
[cols=",,",]
|===
|Standard |Name |Comparison

|INSPIRE Metadata |Conformity |Equivalent

|ISO 19115:2003 |DQ_DataQuality > DQ_Element.result >
DQ_ConformanceResult |Equivalent

|ISO 19139:2007
|/gmd:MD_Metadata/gmd:dataQualityInfo/gmd:DQ_DataQuality/gmd:report/gmd:DQ_DomainConsistency/gmd:result/gmd:DQ_ConformanceResult
|Equivalent
|===

Change history...

[[history41]]
* GEMINI 1 to 2.0: New element
* GEMINI 2.2 to 2.3: changed the way to encode that a resource has not
been tested against the relevant INSPIRE specification

Encoding guidelines...

[[coding41]]
[width="100%",cols="50%,50%",]
|===
|Guidelines a|
. The encoding for Conformity is shown in the example.
. Note that the encoding of conformity requires a specification (encoded
using gmd:CI_Citation), an explanation and a pass.
. INSPIRE Metadata Implementing Rules state that there are three
possible conformance results: conformant, not conformant and not
evaluated. Not evaluated is expressed by a conformity statement with a
nilReason (unknown) specified in the pass element.

[start=4]
. All gmd:dataQualityInfo XML element shall have a gmd:scope XML
element, set to 'dataset' or 'series' as appropriate.

|Example a|
`                   `

....
<gmd:MD_Metadata>
  ...
  <gmd:dataQualityInfo>
    <gmd:DQ_DataQuality>
      <gmd:scope>
        <gmd:DQ_Scope>
          <gmd:level>
            <gmd:MD_ScopeCode codeListValue='dataset' 
              codeList='https://schemas.isotc211.org/schemas/19139/resources/codelist/gmxCodelists.xml#MD_ScopeCode'>dataset</gmd:MD_ScopeCode>
          </gmd:level>
          ...
        </gmd:DQ_Scope>
      </gmd:scope>
      <gmd:report>
        <gmd:DQ_DomainConsistency>
          <gmd:result>
            <gmd:DQ_ConformanceResult>
              <gmd:specification>
                <gmd:CI_Citation>
                  <gmd:title>
                    <gco:CharacterString>INSPIRE Implementing rules laying down technical arrangements for the interoperability 
                      and harmonisation of orthoimagery</gco:CharacterString>
                  </gmd:title>
                  <gmd:date>
                    <gmd:CI_Date>
                      <gmd:date>
                        <gco:Date>2011-05-15</gco:Date>
                      </gmd:date>
                      <gmd:dateType>
                        <gmd:CI_DateTypeCode
                          codeList='https://schemas.isotc211.org/schemas/19139/resources/codelist/                            gmxCodelists.xml#CI_DateTypeCode' 
                          codeListValue='publication'>publication</gmd:CI_DateTypeCode>
                      </gmd:dateType>
                    </gmd:CI_Date>
                  </gmd:date>
                </gmd:CI_Citation>
              </gmd:specification>
              <gmd:explanation>
                <gco:CharacterString>See the referenced specification</gco:CharacterString>
              </gmd:explanation>
              <gmd:pass>
                <gco:Boolean>true</gco:Boolean>
              </gmd:pass>
            </gmd:DQ_ConformanceResult>
          </gmd:result>
        </gmd:DQ_DomainConsistency>
      </gmd:report>
      ...
    </gmd:DQ_DataQuality>
  </gmd:dataQualityInfo>
</gmd:MD_Metadata>
....

Example of a conformity report for Implementing Rule 1089/2010, where
conformance is not evaluated. +
Example follows updated guidance to use gmx:Anchor over
gco:CharacterString for Citation titles

....
 <gmd:report 
    xmlns:gmd="http://www.isotc211.org/2005/gmd" 
    xmlns:gco="http://www.isotc211.org/2005/gco" 
    xmlns:gmx="http://www.isotc211.org/2005/gmx" 
    xmlns:xlink="http://www.w3.org/1999/xlink">
    <gmd:DQ_DomainConsistency>
        <gmd:result>
            <gmd:DQ_ConformanceResult>
                <gmd:specification>
                    <gmd:CI_Citation>
                        <gmd:title>
                            <gmx:Anchor xlink:href="http://data.europa.eu/eli/reg/2010/1089">
                                Commission Regulation (EU) No 1089/2010 of 23 November 2010 implementing Directive 
                                2007/2/EC of the European Parliament and of the Council as regards interoperability 
                                of spatial data sets and services</gmx:Anchor>
                        </gmd:title>
                        <gmd:date>
                            <gmd:CI_Date>
                                <gmd:date>
                                    <gco:Date>2010-12-08</gco:Date>
                                </gmd:date>
                                <gmd:dateType>
                                    <gmd:CI_DateTypeCode 
                                        codeList='https://schemas.isotc211.org/schemas/19139/resources/codelist/gmxCodelists.xml#CI_DateTypeCode' 
                                        codeListValue='publication' />
                                </gmd:dateType>
                            </gmd:CI_Date>
                        </gmd:date>
                    </gmd:CI_Citation>
                </gmd:specification>
                <!-- Explanation is a required element but can be empty -->
                <gmd:explanation gco:nilReason="inapplicable"/>
                <!-- Conformance has not been evaluated -->
                <gmd:pass gco:nilReason="unknown" />
            </gmd:DQ_ConformanceResult>
        </gmd:result>
    </gmd:DQ_DomainConsistency>
</gmd:report>
....

Example three ~ Topological consistency, showing mandatory elements for
a descriptive topological consistency report

....
<gmd:report>
   <gmd:DQ_TopologicalConsistency>
      <gmd:result>
         <gmd:DQ_ConformanceResult>
            <gmd:specification>
               <gmd:CI_Citation>
                  <gmd:title>
                     <!-- The title for this report shall always be "INSPIRE Data Specifications - Base Models - Generic Network Model" -->
                     <gco:CharacterString>INSPIRE Data Specifications - Base Models - Generic Network Model</gco:CharacterString>
                  </gmd:title>
                  <gmd:date>
                     <gmd:CI_Date>
                        <gmd:date>
                           <!-- The date shall be the date of publication of the Generic Network Model -->
                           <gco:Date>2013-04-05</gco:Date>
                        </gmd:date>
                        <gmd:dateType>
                           <!-- The code list value shall always be publication -->
                           <gmd:CI_DateTypeCode codeList='https://schemas.isotc211.org/schemas/19139/resources/codelist/gmxCodelists.xml' 
                           codeListValue='publication'/>
                        </gmd:dateType>
                     </gmd:CI_Date>
                  </gmd:date>
               </gmd:CI_Citation>
            </gmd:specification>
            <!-- An explanation must be provided -->
            <gmd:explanation><gco:CharacterString>[Some statement on topological consistency]</gco:CharacterString></gmd:explanation>
            <gmd:pass>
               <!-- The value shall always be false to indicate that the data does not assure the centerline topology for the network -->
               <gco:Boolean>false</gco:Boolean>
            </gmd:pass>
         </gmd:DQ_ConformanceResult>
      </gmd:result>
   </gmd:DQ_TopologicalConsistency>
</gmd:report>
....

|===

Metadata errors observed...

[[errors41]]
[width="100%",cols="50%,50%",]
|===
|Errors observed |*Conformity statement missing* +
INSPIRE requires a 'conformity' statement, which can say that the
resource conforms, or does not conform to a specification, or that it
hasn't been tested. +
This is encoded with an ISO 19139 quality report. +
*Incorrect citation of INSPIRE regulation* +
When citing the INSPIRE regulation, the title and publication date need
to match exactly. +
Any deviation may result in the validation failure message "The gmd:pass
element is not nillable and shall have a value" - even if the error is
in the spelling of the title.
|===

[[43]]

Name : Equivalent scale

[[requirements43]]
[cols=",",]
|===
|UK GEMINI id |43

|Definition |Level of detail expressed as the scale denominator of a
comparable hardcopy map or chart

|Purpose and meaning |This is purely to conform to INSPIRE, and has
little meaning for most digital data

|Obligation |Optional

|Occurrence |Multiple

|Data type |Integer

|Domain |Positive integer

|Guidance |Where the data is captured from a map, the scale of that map
should be recorded.

|Comment |Expression of spatial resolution by distance is preferred.
Spatial resolution should only be expressed by equivalent scale where a
distance cannot be determined.

|Examples |5,000

|Revision date |July 2009
|===

Corresponding element in other standards...

[[compare43]]
[cols=",,",]
|===
|Standard |Name |Comparison

|INSPIRE Metadata |Spatial resolution |Spatial resolution may also be
expressed as distance

|ISO 19115:2003 |MD_DataIdentification.spatialResolution >
MD_Resolution.equivalentScale > MD_RepresentativeFraction.denominator
|Equivalent

|ISO 19139:2007
|/gmd:MD_Metadata/gmd:identificationInfo/gmd:MD_DataIdentification/gmd:spatialResolution/gmd:MD_Resolution/gmd:equivalentScale
|Equivalent
|===

Change history...

[[history43]]
GEMINI 1 to 2.0: New element

Encoding guidelines...

[[coding43]]
[width="100%",cols="50%,50%",]
|===
|Guidelines |
|Example a|
`                   `

....
   
<gmd:MD_Metadata>
  ...
  <gmd:identificationInfo>
    <gmd:MD_DataIdentification id="def-005000">
      ...
      <gmd:spatialResolution>
        <gmd:MD_Resolution>
          <gmd:equivalentScale>
            <gmd:MD_RepresentativeFraction>
              <gmd:denominator>
                <gco:Integer>50000</gco:Integer>
              </gmd:denominator>
            </gmd:MD_RepresentativeFraction>
          </gmd:equivalentScale>
        </gmd:MD_Resolution>
      </gmd:spatialResolution>
      ...
    </gmd:MD_DataIdentification>
  </gmd:identificationInfo>
  ...
</gmd:MD_Metadata>
....

|===

Metadata errors observed...

[[errors43]]
No error information available

[[44]]

Name : Bounding box

[[requirements44]]
[width="100%",cols="50%,50%",]
|===
|UK GEMINI id |44

|Definition |Rectangle enclosing the extent of the data resource
described in latitude and longitude

|Purpose and meaning |This is to enable the resource to be located
geographically

|Obligation |Mandatory

|Occurrence |Multiple

|Data type |Class

|Domain a|
EX_GeographicBoundingBox

[cols=",,,,",]
!===
!Metadata element name !West bounding longitude !East bounding longitude
!South bounding latitude !North bounding latitude

!Definition !western-most limit of the data resource extent, expressed
in longitude in decimal degrees (positive east) !eastern-most limit of
the data resource extent, expressed in longitude in decimal degrees
(positive east) !southern-most limit of the data resource extent,
expressed in latitude in decimal degrees (positive north) !northern-most
limit of the data resource extent, expressed in latitude in decimal
degrees (positive north)

!Obligation !mandatory !mandatory !mandatory !mandatory

!Occurrence !single !single !single !single

!Data type !Decimal, expressed in degrees to at least two decimal places
! ! !

!Domain !-180.00 <= west bounding longitude <= 180.00 !-180.00 <= east
bounding longitude <= 180.00 !-90.00 <= south bounding latitude <= north
bounding latitude !south bounding latitude <= north bounding latitude <=
90.00

!Other comments !The West bounding coordinate usually has a value less
than the value of the East bounding coordinate, except when the extent
straddles the 180 degree meridian. !The East bounding longitude usually
has a value greater than the value of the West bounding longitude,
except when the extent straddles the 180 degree meridian. ! !
!===

|Guidance a|
. Identify a bounding box slightly larger than the extent of the data
resource, and determine the coordinates of the boundaries. It may be
necessary to convert from another coordinate system (e.g. National Grid)
into lat/long.
. Only approximate values are required, sufficient to identify the
extent on a global basis. The bounding box is implicitly in WGS84.

|Comment |The bounding box will often cover areas that are not directly
related to the area covered by the resource.

|Examples |-9.23, 2.69, 49.84, 60.85

|Revision date |December 2012
|===

Corresponding element in other standards...

[[compare44]]
[cols=",,",]
|===
|Standard |Name |Comparison

|INSPIRE Metadata |Geographic bounding box |Identical

|ISO 19115:2003 |MD_DataIdentification.extent > EX_Extent >
EX_GeographicExtent > EX_GeographicBoundingBox |Minor difference in name

|ISO 19139:2007
|/gmd:MD_Metadata/gmd:identificationInfo/gmd:MD_DataIdentification/gmd:extent/gmd:EX_Extent/gmd:geographicElement/gmd:EX_GeographicBoundingBox
|
|===

Change history...

[[history44]]
* GEMINI 1 to 2.0: Slight change of name of each element
* GEMINI 2.1 to 2.2: the four separate elements were merged to form
Bounding box, which was made multiple

Encoding guidelines...

[[coding44]]
[width="100%",cols="50%,50%",]
|===
|Guidelines a|
. The encoding example for geographic bounding box for datasets is shown
in the example
. Note that the extent XML element is in the gmd namespace. This differs
from service metadata instances where the extent XML element will be in
the srv namespace.
. The definition of the equivalent ISO 19115 class,
EX_GeographicBoundingBox, is 'Geographic area of the entire dataset
referenced to WGS 84'. Consequently, the CRS of the coordinates
expressed in metadata is always WGS 84 (identified by the EPSG URI
http://www.opengis.net/def/crs/EPSG/0/4326). This means that the
coordinate values shall be expressed in units of degrees (encoded using
decimal numbers) with axes orientated north and east. The geodetic datum
is WGS 84.

|Example a|
`                   `

....
<gmd:MD_Metadata>
  ...
  <gmd:identificationInfo>
    <gmd:MD_DataIdentification id="xxx-27700-x">
      ...
      <gmd:extent>
        <gmd:EX_Extent>
          <gmd:geographicElement>
            <gmd:EX_GeographicBoundingBox>
              <gmd:westBoundLongitude>
                <gco:Decimal>-8.14</gco:Decimal>
              </gmd:westBoundLongitude>
              <gmd:eastBoundLongitude>
                <gco:Decimal>2.96</gco:Decimal>
              </gmd:eastBoundLongitude>
              <gmd:southBoundLatitude>
                <gco:Decimal>49.79</gco:Decimal>
              </gmd:southBoundLatitude>
              <gmd:northBoundLatitude>
                <gco:Decimal>60.77</gco:Decimal>
              </gmd:northBoundLatitude>
            </gmd:EX_GeographicBoundingBox>
          </gmd:geographicElement>
          ...
        </gmd:EX_Extent>
      </gmd:extent>
      ...
    </gmd:MD_DataIdentification>
  </gmd:identificationInfo>
  ...
</gmd:MD_Metadata>
....

|===

Metadata errors observed...

[[errors44]]
[width="100%",cols="50%,50%",]
|===
|Errors observed a|
*Overly precise bounding box* +
GEMINI states that the bounding latitude and longitude should be stated
to at least two decimal places. The INSPIRE geoportal used to report two
decimal places as an error; it does not now. However, some software
defaults to values that are unnecessarily "precise". For example: +

....
<gmd:westBoundLongitude>
  <gco:Decimal>-8.17548890898914</gco:Decimal>
</gmd:westBoundLongitude>
....

Six decimal places of a degree is something like 1cm, so the longitude
above is being given to roughly the nearest molecule.

|===

[[48]]

Name : Quality scope

[[requirements48]]
[width="100%",cols="50%,50%",]
|===
|UK GEMINI id |48

|Definition |The specific data to which the data quality information
applies

|Purpose and meaning |To enable data quality to be reported on a subset
of the data resource

|Obligation |Mandatory

|Occurrence |Multiple

|Data type |Class

|Domain |DQ_Scope from ISO 19115

|Guidance a|
. For the conformity statement and lineage of metadata describing:
* a dataset, set quality scope to 'dataset'
* a dataset series, set quality scope 'series'
. If using a Data Quality element to describe something other than the
whole dataset or series, then provide additional DQ_DataQuality elements
with their Scope set appropriately

|Comment |Required in the ISO 19115 encoding of GEMINI 2 metadata
records, to assist in managing related metadata records.

|Examples |

|Revision date |March 2019
|===

Corresponding element in other standards...

[[compare48]]
[cols=",,",]
|===
|Standard |Name |Comparison

|INSPIRE Metadata
|metadata/2.0/req/datasets-and-series/one-data-quality-element |INSPIRE
only allows a maximum of one Data quality element, so only one scope -
the whole resource

|ISO 19115:2003 |DQ_DataQuality.scope |Equivalent

|ISO 19139:2007
|/gmd:MD_Metadata/gmd:dataQualityInfo/gmd:DQ_DataQuality/gmd:scope
|Equivalent
|===

Change history...

[[history48]]
New element in GEMINI 2.3

Encoding guidelines...

[[coding48]]
[width="100%",cols="50%,50%",]
|===
|Guidelines a|
All gmd:dataQualityInfo XML element shall have a gmd:scope XML element,
set to as appropriate.

There shall be exactly one gmd:dataQualityInfo/gmd:DQ_DataQuality
element scoped to the entire described data set or data set series. This
shall contain the Conformity and Lineage elements, and any Quality
measures that relate to the the entire dataset or series

Other quality measures, e.g. for specific feature types, shall be
separate DQ_DataQuality elements, with the relevant Quality scope. In
these cases the Level Description must also be set

|Example a|
`                   `

....
<gmd:MD_Metadata>
  ...
  <gmd:dataQualityInfo>
    <gmd:DQ_DataQuality>
      <gmd:scope>
        <gmd:DQ_Scope>
          <gmd:level>
            <gmd:MD_ScopeCode codeListValue='dataset' 
              codeList='https://schemas.isotc211.org/schemas/19139/resources/codelist/gmxCodelists.xml#MD_ScopeCode'>dataset</gmd:MD_ScopeCode>
          </gmd:level>
          ...
        </gmd:DQ_Scope>
      </gmd:scope>
      ...
    </gmd:DQ_DataQuality>
  </gmd:dataQualityInfo>
</gmd:MD_Metadata>
....

|===

Metadata errors observed...

[[errors48]]
No error information available

[[50]]

Name : Spatial representation type

[[requirements50]]
[width="100%",cols="50%,50%",]
|===
|UK GEMINI id |50

|Definition |The method used to spatially represent geographic
information

|Purpose and meaning |The type in which the spatial data is represented
may be of importance when evaluating the fit for purpose of the dataset.
The code list value of this element is intended for describing this
information.

|Obligation |Mandatory

|Occurrence |Multiple

|Data type |Class (CodeList)

|Domain a|
MD_SpatialRepresentationTypeCode from ISO 19115. Codes to be used are:

. vector
. grid
. tin
. textTable

|Guidance a|
. tin stands for triangulated irregular network. TIN is a digital data
structure used in a geographic information system (GIS) for the
representation of a surface
. textTable should be used for datasets with an indirect spatial
reference
. grid should be used for images and coverage data

|Comment |This element is regarded by the INSPIRE metadata technical
guidance as interoperability metadata for datasets and dataset series

|Examples |vector

|Revision date |May 2018
|===

Corresponding element in other standards...

[[compare50]]
[width="100%",cols="34%,33%,33%",]
|===
|Standard |Name |Comparison

|INSPIRE Metadata |Spatial representation type
(metadata/2.0/req/isdss/spatial-representation-type) |

|ISO 19115:2003 |MD_DataIdentification.spatialRepresentationType +
references: B.5.26 MD_SpatialRepresentationTypeCode CodeList |CodeList
is a superset of values used by INSPIRE

|ISO 19139:2007
|/gmd:MD_Metadata/gmd:identificationInfo/gmd:MD_DataIdentification/gmd:spatialRepresentationType/gmd:MD_SpatialRepresentationTypeCode
|
|===

Change history...

[[history50]]
* In original GEMINI, but removed in 2
* Reintroduced in GEMINI 2.3

Encoding guidelines...

[[coding50]]
[width="100%",cols="50%,50%",]
|===
|Guidelines |Only the codeListValue is required, the codeList and the
free text content are optional and informative only

|Example a|
`                   `

....
   <gmd:identificationInfo>
      <gmd:MD_DataIdentification id="CEH-barrcj2015">
        ...
         <gmd:resourceConstraints>
            ...
         </gmd:resourceConstraints>
         <gmd:spatialRepresentationType>
            <gmd:MD_SpatialRepresentationTypeCode 
            codeList='https://schemas.isotc211.org/schemas/19139/resources/codelist/gmxCodelists.xml#MD_SpatialRepresentationTypeCode' 
            codeListValue='textTable' />
         </gmd:spatialRepresentationType>
         <gmd:language>
            ...
         </gmd:language>
        ...
      </gmd:MD_DataIdentification>
....

|===

Metadata errors observed...

[[errors50]]
No error information available

[[51]]

Name : Character encoding

[[requirements51]]
[cols=",",]
|===
|UK GEMINI id |51

|Definition |The character encoding used in the dataset

|Purpose and meaning |To enable data in non-standard character encodings
to be handled

|Obligation |Conditional (mandatory if an encoding is used that is not
based on UTF-8, otherwise optional)

|Occurrence |Multiple

|Data type |Class (CodeList)

|Domain |MD_CharacterSetCode from ISO 19115

|Guidance |If more than one charater encoding is used within the dataset
or dataset series, all used character encodings Including UTF-8, shall
be given.

|Comment |This element is regarded by the INSPIRE metadata technical
guidance as interoperability metadata for datasets and dataset series

|Examples |

|Revision date |May 2018
|===

Corresponding element in other standards...

[[compare51]]
[width="100%",cols="34%,33%,33%",]
|===
|Standard |Name |Comparison

|INSPIRE Metadata |Character encoding
(metadata/2.0/req/isdss/character-encoding) |

|ISO 19115:2003 |MD_DataIdentification.characterSet +
references: B.5.10 MD_CharacterSetCode CodeList |Equivalent

|ISO 19139:2007
|/gmd:MD_Metadata/gmd:identificationInfo/gmd:MD_DataIdentification/gmd:characterSet/gmd:MD_CharacterSetCode
|Equivalent
|===

Change history...

[[history51]]
New element in GEMINI 2.3

Encoding guidelines...

[[coding51]]
[width="100%",cols="50%,50%",]
|===
|Guidelines |Only the codeListValue is required, the codeList and the
free text content are optional and informative only

|Example a|
`                   `

....
   <gmd:identificationInfo>
      <gmd:MD_DataIdentification id="UKHO-12mfihlimit">
         <gmd:citation>
            ...
         </gmd:citation>
        ...
         <gmd:language>
            ...
         </gmd:language>
         <gmd:characterSet>
            <gmd:MD_CharacterSetCode 
              codeList='https://schemas.isotc211.org/schemas/19139/resources/codelist/gmxCodelists.xml#MD_CharacterSetCode' 
              codeListValue='8859part1'>ISO/IEC 8859-1 (also known as Latin 1)</gmd:MD_CharacterSetCode>
         </gmd:characterSet>
         <gmd:topicCategory>
            ...
         </gmd:topicCategory>
         <gmd:extent>
            ...
         </gmd:extent>
            ...
      </gmd:MD_DataIdentification>
   </gmd:identificationInfo>
....

|===

Metadata errors observed...

[[errors51]]
No error information available

[[52]]

Name : Data quality

[[requirements52]]
[width="100%",cols="50%,50%",]
|===
|UK GEMINI id |52

|Definition |Quantitative aspects of data quality

|Purpose and meaning |To allow quantitative description of the
completeness, consistency, accuracy, and correctness of the data

|Obligation |Conditional: Topological consistency report is mandatory if
the dataset includes types from the INSPIRE Generic Network Model and
does not assure centerline topology (connectivity of centrelines) for
the network, otherwise optional

|Occurrence |Multiple

|Data type |Class, subtypes of DQ_Element

|Domain a|
DQ_Element from ISO 19115

DQ_Element is an abstract complex type and has to be expressed by a
corresponding DQ_xxx subelement concerning the particular data quality
issue e.g. DQ_ConceptualConsistency. All these types have the same
sub-attributes, such as nameOfMeasure, dateTime, result. It is important
to choose the correct subelement, to clearly indicate the type of
quality statement being made. Only the result sub-element (value, value
type) is mandatory. All DQ_Element subtypes have the same sub-elements.

.Table 1 Data Quality sub-elements
[cols=",,,",options="header",]
!===
!Data Quality sub-element name !result !dateTime !nameOfMeasure
!Definition !value (or set of values) obtained from applying a data
quality measure or the outcome of evaluating the obtained value (or set
of values) against a specified acceptable conformance quality level
!date or range of dates on which a data quality measure was applied
!name of the test applied to the data

!Obligation !mandatory !optional !optional

!Occurence !single !single !single

!Data type !DQ_QuantitativeResult !DateTime !CharacterString

!Domain !see table two below ! !see table three below
!===

.Table 2: DQ_QuantitativeResult
[cols=",,,",options="header",]
!===
!Data Quantitative Result sub-element name !valueUnit !value !valueType
!Definition !the units in which the result is reported !the quantitative
result !the data type of the result

!Obligation !mandatory !mandatory !mandatory

!Occurence !single !multiple !single

!Data type !UnitOfMeasure !Record !RecordType

!Domain !see table three below ! !see table three below
!===

.Table 3: Details for various types of quality measure
[width="99%",cols="20%,16%,16%,16%,16%,16%",options="header",]
!===
!Name !DQ_Element subtype !Definition !nameOfMeasure !Value type
!Example INSPIRE themes
! ! ! !As given in the
https://inspire.ec.europa.eu/Themes/Data%20Specifications/2892[INSPIRE
Data Specifications] ! !See the relevant specification for more details
of each measure

!Completeness - Commission !DQ_CompletenessCommission !excess data
present in the dataset, as described by the scope !Rate of excess items
!Real !AU, AD, TN, HY, PS, EL, LC, SU, BU, LU, US

! ! ! !Number of duplicate feature instances !Integer !TN

!Completeness - Omission !DQ_CompletenessOmission !data absent from the
dataset, as described by the scope !Rate of missing items !Real !GN, AU,
AD, CP, TN, HY, PS, EL, LC, OI, (not GE), SU, BY, SO, LU, US, PF, AF, OF

!Conceptual consistency !DQ_ConceptualConsistency !adherence to rules of
the conceptual schema !Non-compliance rate with respect to the rules of
the conceptual schema !Real !EL

! ! ! !Number of items not compliant with the rules of the conceptual
schema !Integer !AU, TN

! ! ! !Conceptual schema non-compliance !Boolean !LC

!Domain consistency !DQ_DomainConsistency !adherence of values to the
value domains !Number of items not in conformance with their value
domain !Integer !AU

! ! ! !Value domain non-conformance rate !Real !EL

! ! ! !Value domain conformance rate !Real !HY

! ! ! !Value domain non-conformance !Boolean !LC

!Topological consistency !DQ_TopologicalConsistency !Correctness of the
explicitly encoded topological characteristics of the dataset +
Note: Only use this if the topological consistency can be quantified,
otherwise provide a descriptive result with a DQ_ConformanceResult
element; see GEMINI Conformity element !Number of faulty point-curve
connections !Integer !AU, TN, HY

! ! ! !Number of missing connections due to undershoots !Integer !AU,
TN, HY

! ! ! !Rate of missing connections due to undershoots !Real !EL

! ! ! !Number of missing connections due to overshoots !Integer !TN, HY

! ! ! !Rate of missing connections due to overshoots !Real !EL

! ! ! !Number of missing connections due to crossing of bridge/road
!Integer !HY

! ! ! !Number of invalid overlaps of surfaces !Integer !HY

! ! ! !Slivers !Integer !SU

! ! ! !Number of invalid slivers !Integer !

! ! ! !Number of invalid self-intersect errors !Integer !TN, HY, LC

! ! ! !Rate of invalid self-intersect errors !Real !EL

! ! ! !Number of invalid self-overlap errors !Integer !TN, HY

! ! ! !Rate of invalid self-overlap errors !Rate !EL

! ! ! !Number of watercourse links below threshold length !Integer !HY

! ! ! !Number of closed watercourse links !Integer !HY

! ! ! !Number of multi-part watercourse links !Integer !HY

!Format consistency !DQ_FormatConsistency !Degree to which data is
stored in accordance with the physical structure of the dataset
!Physical structure conflict rate ! !EL

! ! ! !Physical structure conflicts !Boolean !LC

!Absolute or external accuracy !DQ_AbsoluteExternalPositionalAccuracy
!closeness of reported coordinate values to values accepted as or being
true !Mean value of positional uncertainties !Measure !

! ! ! !Positional accuracy !Measure !SU

! ! ! !Root mean square error of planimetry !Measure !EL, LC

! ! ! !Root mean square error !Measure !EL

!Gridded positional accuracy !DQ_GriddedDataPositionalAccuracy
!Closeness of gridded data position values to values accepted as or
being true !Root mean square error of planimetry !Measure !EL

!Relative positional accuracy !DQ_RelativeInternalPositionalAccuracy
!closeness of the relative positions of features in the scope to their
respective relative positions accepted as or being true !Relative
horizontal error !Measure !

! ! ! !Root mean square error of planimetry !Real !LC

!Temporal validity !DQ_TemporalValidity ! !Temporal accuracy !Boolean
!SU

!Thematic accuracy - classification
!DQ_ThematicClassificationCorrectness !Comparison of the classes
assigned to features or their attributes to a universe of discourse
!Misclassification rate !Real !TN, LC

! ! ! !Thematic accuracy !Real !SU

! ! ! !Misclassification matrix !Matrix of integers !LC

!Quantitative attribute accuracy !DQ_QuantitativeAttributeAccuracy
!Accuracy of quantitative attributes !Attribute value uncertainty at 95%
significance level !Real !HY

! ! ! !Scatter plot !Graphical !LC

!non-quantitative attribute correctness
!DQ_NonQuantitiveAttributeAccuracy !correctness of non-quantitative
attributes !Rate of incorrect attribute values !Real !

! ! ! !Number of incorrect attribute values !Integer !
!===

Other attributes of ISO 19115 DQ_Element may be included, e.g.:

.Table 4 Optional data quality sub-elements
[width="100%",cols="34%,33%,33%",]
!===
! !evaluationMethodType !evaluationMethodDescription

!Definition !type of method used to evaluate quality of the dataset
!description of the evaluation method

!Obligation !optional !optional

!Occurence !single !single

!Data type !DQ_EvaluationMethodTypeCode !free text

!Domain ! !For example, in the INSPIRE Metadata Technical Guidelines,
recommendation 2.3 says “It is recommended to provide a short
description of the evaluation method used for topological consistency
check”.
!===

|Guidance |

|Comment |This element is regarded by the INSPIRE metadata technical
guidance as interoperability metadata for datasets and dataset series

|Examples |

|Revision date |May 2018
|===

Corresponding element in other standards...

[[compare52]]
[width="100%",cols="34%,33%,33%",]
|===
|Standard |Name |Comparison

|INSPIRE Metadata |Topological consistency +
either:
metadata/2.0/req/isdss/topological-consistency-quantitative-results +
or: metadata/2.0/req/isdss/topological-consistency-descriptive-results +
Other types are specified in the data specifications |

|ISO 19115:2003 |DQ_DataQuality.report->__DQ_Element__ |Equivalent

|ISO 19139:2007
|/gmd:MD_Metadata/gmd:dataQualityInfo/gmd:DQ_DataQuality/gmd:report/gmd:DQ_********
|Equivalent
|===

Change history...

[[history52]]
New element in GEMINI 2.3

Encoding guidelines...

[[coding52]]
[width="100%",cols="50%,50%",]
|===
|Guidelines a|
There shall be exactly one gmd:dataQualityInfo/gmd:DQ_DataQuality
element scoped to the entire described data set or data set series. So
if the scope of the quality measure is the entire dataset or series,
then the result shall be in the same DQ_DataQuality element as the
Conformity and Lineage elements

Other quality measures, e.g. for specific feature types, shall be
separate DQ_DataQuality elements, with the relevant Quality scope

Quantitative results shall be reported using the relevant
gmd:report/gmd:DQ_XXXXX element with a gmd:DQ_QuantitativeResult element
as the value of its mandatory gmd:result property.

The gmd:valueUnit and gmd:value/gco:Record child elements of
gmd:DQ_QuantitativeResult shall be used for giving a numerical or
otherwise quantitative value.

The value type of the result shall be declared using the xsi:type
attribute of the gco:Record element. Note that many of the INSPIRE Data
Specifications give a value type of “Real, percentage, ratio”; GEMINI
recommends using real numbers in all these cases, which should be
declared as xs:double.

As well as the mandatory elements, it is also recommended to supply a
name of the measure, a short description of the evaluation method, and a
date for the evaluation of the consistency check

|Example a|
`                   `

....
<gmd:dataQualityInfo>
    <gmd:DQ_DataQuality>
        <gmd:scope>
            <gmd:DQ_Scope>
                <gmd:level>
            <gmd:MD_ScopeCode codeListValue='dataset' 
              codeList='https://schemas.isotc211.org/schemas/19139/resources/codelist/gmxCodelists.xml#MD_ScopeCode'>dataset</gmd:MD_ScopeCode>
                </gmd:level>
            </gmd:DQ_Scope>
        </gmd:scope>
        <gmd:report>
            <gmd:DQ_CompletenessCommission>
                <gmd:nameOfMeasure>
                    <gco:CharacterString>Rate of excess items</gco:CharacterString>
                </gmd:nameOfMeasure>
                <gmd:dateTime>
                    <gco:DateTime>2017-04-01T01:00:00</gco:DateTime>
                </gmd:dateTime>
                <gmd:result>
                    <gmd:DQ_QuantitativeResult>
                        <gmd:valueUnit gco:nilReason="inapplicable"/>
                        <gmd:value>
                            <gco:Record
                                xmlns:xs="http://www.w3.org/2001/XMLSchema"
                                xsi:type="xs:double">0.01</gco:Record>
                        </gmd:value>
                    </gmd:DQ_QuantitativeResult>
                </gmd:result>
            </gmd:DQ_CompletenessCommission>
        </gmd:report>
        <gmd:report>
            <gmd:DQ_AbsoluteExternalPositionalAccuracy>
                <gmd:nameOfMeasure><gco:CharacterString>Root mean square error</gco:CharacterString></gmd:nameOfMeasure>
                <gmd:dateTime><gco:DateTime>2017-04-01T02:00:00</gco:DateTime></gmd:dateTime>
                <gmd:result><gmd:DQ_QuantitativeResult>
                    <gmd:valueUnit>
                        <gml:BaseUnit gml:id="ID001">
                            <gml:identifier codeSpace="SI">meters</gml:identifier>
                            <gml:unitsSystem xlink:href="http://www.bipm.org/en/si/"/>
                        </gml:BaseUnit>
                    </gmd:valueUnit>
                    <gmd:value>
                     <gco:Record
                        xmlns:xs="http://www.w3.org/2001/XMLSchema"
                        xsi:type="xs:real">0.1</gco:Record></gmd:value>
                </gmd:DQ_QuantitativeResult></gmd:result>
            </gmd:DQ_AbsoluteExternalPositionalAccuracy>
        </gmd:report>
    </gmd:DQ_DataQuality>
</gmd:dataQualityInfo>
          
....

Example two - Topological consistency

....
 <gmd:report>
    <gmd:DQ_TopologicalConsistency>
       <gmd:result>
          <gmd:DQ_QuantitativeResult>
             <!--The mandatory elements are valueUnit and value/Record with xsi:type  -->
             <gmd:valueUnit xlink:href="http://www.opengis.net/def/uom/OGC/1.0/unity"/>
             <gmd:value>
                 <gco:Record 
                   xmlns:xs="http://www.w3.org/2001/XMLSchema"
                   xsi:type="xs:integer">12</gco:Record>
             </gmd:value>
          </gmd:DQ_QuantitativeResult>
       </gmd:result>
    </gmd:DQ_TopologicalConsistency>
</gmd:report>
....

Example three ~ Topological consistency, showing a quantitative
topological consistency report with recommended elements included

....
 <gmd:report>
   <gmd:DQ_TopologicalConsistency>
      <gmd:nameOfMeasure>
         <gco:CharacterString>
         Number of faulty point-curve connections
         </gco:CharacterString>
      </gmd:nameOfMeasure>
      <gmd:evaluationMethodType>
         <gmd:DQ_EvaluationMethodTypeCode 
           codeList='https://schemas.isotc211.org/schemas/19139/resources/codelist/gmxCodelists.xml#DQ_EvaluationMethodTypeCode' 
           codeListValue='indirect' />
      </gmd:evaluationMethodType>
      <gmd:evaluationMethodDescription>
         <gco:CharacterString>
           A point-curve connection exists where different curves touch... 
         </gco:CharacterString>
      </gmd:evaluationMethodDescription>
      <gmd:dateTime>2017-01-21T19:21:30</gmd:dateTime>
      <gmd:result>
         <gmd:DQ_QuantitativeResult>
            <!--The mandatory elements are valueUnit and value/Record with xsi:type  -->
            <gmd:valueUnit xlink:href="http://www.opengis.net/def/uom/OGC/1.0/unity"/>
            <gmd:value>
               <gco:Record 
                 xmlns:xs="http://www.w3.org/2001/XMLSchema"
                 xsi:type="xs:integer">12</gco:Record>
            </gmd:value>
         </gmd:DQ_QuantitativeResult>
      </gmd:result>
   </gmd:DQ_TopologicalConsistency>
</gmd:report>
....

|===

Metadata errors observed...

[[errors52]]
No error information available

[[53]]

Name : Maintenance information

[[requirements53]]
[width="100%",cols="50%,50%",]
|===
|UK GEMINI id |53

|Definition |Information about the scope and frequency of updating

|Purpose and meaning |

|Obligation |Optional

|Occurrence |Single

|Data type |MD_MaintenanceInformation

|Domain a|
ISO 19115 MD_MaintenanceInformation

At least maintenanceAndUpdateFrequency should be used, in addition it is
recommended to supply updateScope/MD_ScopeCode and maintenanceNote, but
only one of each

.Table 1 Maintenance information sub-elements
[cols=",,,",]
!===
!Sub element name !maintenance and update frequency !update scope
!maintenance note

!Definition !frequency with which changes and additions are made to the
resource after the initial resource is completed !scope of data to which
maintenance is applied !information regarding specific requirements for
maintaining the resource

!Obligation !Mandatory !Optional !Optional

!Occurence !single !single !single

!Domain !Maintenance frequency code (ISO 19115) !Scope code (ISO 19115)
!free text
!===

Maintenance frequency code has values such as _continual, weekly,
monthly, annually, notPlanned, unknown_

Scope code has values such as _dataset, series, feature, tile_

|Guidance |

|Comment |Recommended for all INSPIRE themes +
See the relevant INSPIRE data specifications, section 8.3.1 for further
theme specific information

|Examples |

|Revision date |April 2020
|===

Corresponding element in other standards...

[[compare53]]
[cols=",,",]
|===
|Standard |Name |Comparison

|INSPIRE Metadata |Maintenance information |identical

|ISO 19115:2003 |MD_DataIdentification.resourceMaintenance |19115 allows
more than one resourceMaintenance

|ISO 19139:2007
|/gmd:MD_Metadata/gmd:identificationInfo[1]/gmd:MD_DataIdentification/gmd:resourceMaintenance/
|19139 allows more than one resourceMaintenance
|===

Change history...

[[history53]]
New element in GEMINI 2.3

Encoding guidelines...

[[coding53]]
[width="100%",cols="50%,50%",]
|===
|Guidelines |No specific rules for this metadata element

|Example a|
`                   `

....
         <gmd:resourceMaintenance>
            <gmd:MD_MaintenanceInformation>
               <!-- At least maintenanceAndUpdateFrequency should be used -->
               <gmd:maintenanceAndUpdateFrequency>
                  <gmd:MD_MaintenanceFrequencyCode 
                     codeList='https://schemas.isotc211.org/schemas/19139/resources/codelist/gmxCodelists.xml#MD_MaintenanceFrequencyCode' 
                     codeListValue='annually'>annually</gmd:MD_MaintenanceFrequencyCode>
               </gmd:maintenanceAndUpdateFrequency>
               <!-- The following elements are recommended-->
               <gmd:updateScope>
            <gmd:MD_ScopeCode codeListValue='dataset' 
              codeList='https://schemas.isotc211.org/schemas/19139/resources/codelist/gmxCodelists.xml#MD_ScopeCode'>dataset</gmd:MD_ScopeCode>
               </gmd:updateScope>
               <gmd:maintenanceNote>
                  <gco:CharacterString>[Information regarding specific requirements for maintaining the resource]</gco:CharacterString>
               </gmd:maintenanceNote>
            </gmd:MD_MaintenanceInformation>
         </gmd:resourceMaintenance>
....

|===

Metadata errors observed...

[[errors53]]
No error information available
